
'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  vi: {
    // ============== NAVIGATION GROUPS ==============
    // 1. Tổng quan
    'nav.overview': 'Tổng quan',
    'nav.homepage': 'Trang chủ',
    'nav.mainDashboard': 'Dashboard Tổng hợp',
    'nav.commandDashboard': 'Dashboard Ban Chỉ huy',
    'nav.autoDashboard': 'Dashboard Tự động',
    'nav.myDashboard': 'Dashboard Cá nhân',
    'nav.realtimeMonitor': 'Giám sát Thời gian thực',
    'nav.dashboardManagement': 'Quản lý Widgets',
    'nav.masterData': 'Danh mục Dùng chung (MDM)',

    // 2. Hồ sơ cá nhân
    'nav.personalProfile': 'Hồ sơ Cá nhân',
    'nav.myProfile': 'Hồ sơ của tôi',
    'nav.scientificCV': 'Lý lịch Khoa học',

    // 3. CSDL Nhân sự
    'nav.personnelDatabase': 'CSDL Cán bộ, Quân nhân',
    'nav.personnelOverview': 'Tổng quan CSDL Cán bộ, Quân nhân',
    'nav.personnelList': 'CSDL Sĩ quan, Quân nhân HVHC',
    'nav.personnelCreate': 'Thêm mới Cán bộ, Quân nhân',
    'nav.personnelStats': 'Thống kê Nhân sự',
    'nav.officerManagement': 'Quản lý Sĩ quan',
    'nav.soldierManagement': 'Quản lý Quân nhân',
    'nav.personnelAdvancedSearch': 'Tìm kiếm nâng cao',
    'nav.personnelSearch': 'Tìm kiếm cán bộ',
    'nav.personnelPlanning': 'Quy hoạch cán bộ',
    'nav.personnelImport': 'Nhập dữ liệu CSV',

    // 3. CSDL Đảng viên
    'nav.partyOverview': 'Tổng quan CTĐ',
    'nav.partyDatabase': 'CSDL Đảng viên',
    'nav.welfareDatabase': 'CSDL Phúc lợi',
    'nav.partyMemberList': 'Danh sách Đảng viên',
    'nav.partyMemberProfile360': 'Hồ sơ Đảng viên 360°',
    'nav.partyOrgStructure': 'Cơ cấu tổ chức Đảng',
    'nav.partyRecruitmentPipeline': 'Pipeline Kết nạp Đảng',
    'nav.partyMemberCreate': 'Thêm Đảng viên',
    'nav.partyAdmissions': 'Quy trình kết nạp',
    'nav.partyMeetings': 'Sinh hoạt Chi bộ',
    'nav.partyEvaluations': 'Đánh giá phân loại',
    'nav.partyActivities': 'Sinh hoạt Đảng',
    'nav.partyFees': 'Quản lý Đảng phí',
    'nav.partyAwards': 'Khen thưởng Đảng',
    'nav.partyAnnualReviews': 'Đánh giá thường niên',
    'nav.partyDisciplines': 'Kỷ luật Đảng',
    'nav.partyTransfers': 'Chuyển sinh hoạt Đảng',
    'nav.partyInspections': 'Kiểm tra, giám sát UBKT',

    // 4. CSDL Chính sách
    'nav.policyDatabase': 'CSDL Chính sách',
    'nav.policyOverview': 'Tổng quan Chính sách',
    'nav.policyList': 'Danh sách Chính sách',
    'nav.policyCreate': 'Thêm Chính sách',
    'nav.policyCategories': 'Danh mục Chính sách',
    'nav.policyApproval': 'Phê duyệt Chính sách',
    'nav.welfare': 'Chế độ Chính sách',
    'nav.policyRequests': 'Đề nghị Chính sách',
    'nav.policyRewards': 'Chế độ Khen thưởng',
    'nav.policyDiscipline': 'Chế độ Kỷ luật',
    'nav.policyWelfare': 'Chính sách Phúc lợi',
    
    // 5. CSDL Bảo hiểm Xã hội
    'nav.insuranceDatabase': 'CSDL Bảo hiểm Xã hội',
    'nav.insurance': 'Bảo hiểm Xã hội',
    'nav.insuranceOverview': 'Tổng quan BHXH',
    'nav.insuranceList': 'Danh sách BHXH',
    'nav.insuranceCreate': 'Thêm hồ sơ BHXH',
    'nav.insuranceContributions': 'Quản lý Đóng góp',
    'nav.insuranceBenefits': 'Quyền lợi BHXH',
    'nav.insuranceDependents': 'Người phụ thuộc',
    'nav.insuranceClaims': 'Yêu cầu Chế độ',
    'nav.medicalFacilities': 'Cơ sở KCB',
    
    // 6. CSDL Thi đua Khen thưởng
    'nav.awardsDatabase': 'CSDL Thi đua Khen thưởng',
    'nav.emulationRewardsDatabase': 'CSDL Thi đua Khen thưởng',
    'nav.emulationOverview': 'Tổng quan Thi đua KT',
    'nav.awardsOverview': 'Tổng quan Khen thưởng',
    'nav.awardsList': 'Danh sách Khen thưởng',
    'nav.awardsCreate': 'Thêm Khen thưởng',
    'nav.rewardsList': 'Danh sách Khen thưởng',
    'nav.rewardsCreate': 'Thêm Khen thưởng',
    'nav.emulationManagement': 'Quản lý Thi đua',
    'nav.emulationStats': 'Thống kê theo Đơn vị',
    'nav.rewards': 'Khen thưởng',
    'nav.discipline': 'Kỷ luật',

    // 6. CSDL Giảng viên - Học viên
    'nav.facultyStudentDatabase': 'CSDL Giảng viên - Học viên',
    'nav.facultyStudentOverview': 'Tổng quan CSDL GV-HV',
    'nav.facultyOverview': 'Tổng quan Giảng viên',
    'nav.facultyList': 'Danh sách Giảng viên',
    'nav.facultyProfile': 'Hồ sơ Giảng viên',
    'nav.facultyResearch': 'NCKH của Giảng viên',
    'nav.facultyScientificProfile': 'Lý lịch Khoa học GV',
    'nav.studentGuidance': 'Học viên hướng dẫn',
    'nav.teachingStats': 'Thống kê Giảng dạy',
    'nav.studentList': 'Danh sách Học viên',
    'nav.studentStats': 'Thống kê Học viên',
    'nav.scientificProfile': 'Lý lịch Khoa học',
    'nav.facultyImport': 'Import Giảng viên (CSV)',
    'nav.myStudents': 'HV do tôi hướng dẫn',
    
    // 6.1 CSDL Giáo dục - Đào tạo
    'nav.educationDatabase': 'CSDL Giáo dục - Đào tạo',
    'nav.educationDatabaseOverview': 'Tổng quan CSDL GD-ĐT',
    'nav.educationModule': 'Giáo dục - Đào tạo',
    // Menu groups (new restructured)
    'nav.educationOverviewGroup':    'Tổng quan Đào tạo',
    'nav.facultyManagementGroup':    'Quản lý Giảng viên',
    'nav.trainingSystemGroup':       'Hệ đào tạo & Tiểu đoàn',
    'nav.studentManagementGroup':    'Quản lý Người học',
    'nav.educationProgramGroup':     'Chương trình & Vận hành',
    // Menu items
    'nav.educationOverview': 'Tổng quan GD-ĐT',
    'nav.facultyOverview':   'Quản lý Giảng viên',
    'nav.trainingSystems':   'Hệ đào tạo & Tiểu đoàn',
    'nav.militaryStudents':  'Học viên Quân sự',
    'nav.civilStudents':     'Sinh viên Dân sự',
    'nav.educationConduct':  'Điểm rèn luyện',
    'nav.educationThesis':   'Khóa luận tốt nghiệp',
    'nav.educationGraduation': 'Xét tốt nghiệp',
    'nav.educationStudents': 'Toàn bộ Người học',
    'nav.educationPlanning': 'Kế hoạch Đào tạo',
    'nav.educationCourseSections': 'Lớp học phần',
    'nav.educationAttendance': 'Điểm danh',
    'nav.educationGrades': 'Quản lý Điểm',
    'nav.educationWarnings': 'Cảnh báo Học vụ',
    'nav.educationPrograms': 'Chương trình ĐT',
    'nav.educationCurriculum': 'Khung CTĐT',
    'nav.educationSubjects': 'Môn học',
    'nav.educationCoefficients': 'Hệ số môn học',
    'nav.educationSchedule': 'Lịch học/Huấn luyện',
    'nav.educationTeachingAssignment': 'Phân công GV',
    'nav.educationRooms': 'Phòng học',
    'nav.educationExamPlan': 'Kế hoạch thi',
    'nav.educationQuestionBank': 'Ngân hàng câu hỏi',
    'nav.educationLearningMaterials': 'Học liệu',
    'nav.educationLab': 'Phòng thí nghiệm',
    'nav.programOverview': 'Tổng quan CTĐT',
    'nav.programs': 'Chương trình đào tạo',
    'nav.curriculum': 'Khung CTĐT',
    'nav.subjectManagement': 'Quản lý môn học',
    'nav.courseCoefficients': 'Hệ số môn học',
    'nav.trainingSchedule': 'Lịch huấn luyện',
    'nav.teachingAssignment': 'Phân công giảng dạy',
    'nav.classroomManagement': 'Quản lý phòng học',
    'nav.examPlan': 'Khảo thí & BĐCL',
    'nav.questionBank': 'Ngân hàng câu hỏi',
    'nav.learningMaterials': 'Học liệu',
    'nav.labManagement': 'Phòng thí nghiệm',
    
    // 9b. CSDL Khoa học Quản lý (CSDL-KHQL)
    'nav.scienceDatabase':    'CSDL Khoa học Quản lý',
    'nav.scienceDashboard':   'Tổng quan KHQL',
    'nav.scienceProjects':    'Quản lý Đề tài',
    'nav.scienceActivities':  'Vòng đời Đề tài',
    'nav.scienceScientists':  'Nhà Khoa học',
    'nav.scienceCouncils':    'Hội đồng KH',
    'nav.scienceBudgets':     'Kinh phí NCKH',
    'nav.scienceLibrary':     'Thư viện số',
    'nav.scienceCatalogs':    'Danh mục KH',
    'nav.scienceWorks':             'Công trình KH',
    'nav.scienceSearch':            'Tìm kiếm thông minh',
    'nav.scienceDataQuality':       'Chất lượng Dữ liệu',
    'nav.scienceDataHubOverview':   'Kho dữ liệu KH (M22)',
    'nav.scienceDataHubRecords':    'Unified Records',
    'nav.scienceAiTools':           'AI Tools',
    'nav.scienceReports':           'Xuất báo cáo BQP',

    // 7. CSDL Nghiên cứu Khoa học
    'nav.researchDatabase': 'CSDL Nghiên cứu Khoa học',
    'nav.researchOverview': 'Tổng quan CSDL NCKH',
    'nav.researchManagement': 'Quản lý CSDL Khoa học',
    'nav.researchCreate': 'Thêm Đề tài NCKH',
    'nav.scientistsList': 'Danh sách Nhà Khoa học',
    'nav.researchScientists': 'Danh sách Nhà Khoa học',
    'nav.researchDetailOverview': 'Tổng quan Chi tiết',
    'nav.researchIntegration': 'Kết nối QLKH',
    'nav.aiResearchTrends': 'AI xu hướng NCKH',
    'nav.aiTrends': 'AI Xu hướng NCKH',
    'nav.teachingResearch': 'Giảng dạy & NCKH',
    'nav.teachingSubjects': 'Môn giảng dạy',
    'nav.teachingAnalytics': 'Thống kê Giảng dạy',
    'nav.researchProjects': 'Đề tài NCKH',
    'nav.researchPublications': 'Kho Công bố KH',
    'nav.researchCapacityMap': 'Bản đồ Năng lực',
    'nav.researchRepository': 'Kho Nghiên cứu',
    'nav.researchCenter': 'Trung tâm NCKH',
    'nav.trainingPrograms': 'Chương trình Đào tạo',
    
    // 7. Phân tích & AI
    'nav.analyticsAI': 'Phân tích & AI',
    'nav.analyticsReports': 'Phân tích & Báo cáo',
    'nav.basicAnalytics': 'Phân tích Cơ bản',
    'nav.advancedAnalytics': 'Phân tích Nâng cao',
    'nav.aiAdvisor': 'Trí tuệ Chỉ huy AI',
    'nav.aiDashboard': 'Dashboard AI',
    'nav.aiPersonnel': 'AI Nhân sự',
    'nav.reports': 'Báo cáo',
    'nav.templates': 'Mẫu biểu & Xuất file',
    'nav.templateLibrary': 'Thư viện mẫu biểu',
    'nav.exportJobs': 'Lịch sử xuất file',
    'nav.scheduledExports': 'Xuất định kỳ',
    'nav.kpis': 'KPIs & Chỉ tiêu',
    'nav.realtimeKpis': 'KPIs Thời gian thực',

    // M18/M19. Mẫu biểu & Xuất dữ liệu
    'nav.templateExport': 'Mẫu biểu & Xuất dữ liệu',

    // W. Quy trình nghiệp vụ (M13)
    'nav.workflowModule': 'Quy trình nghiệp vụ',
    'nav.workflowDashboard': 'Tổng quan Quy trình',
    'nav.workflowDefinitions': 'Định nghĩa quy trình',
    'nav.workflowMyWork': 'Công việc của tôi',
    'nav.workflowInstances': 'Danh sách quy trình',
    'nav.workflowDesigner': 'Thiết kế quy trình',

    // D. Văn bản số (M16)
    'nav.digitalDocsModule': 'Văn bản số',
    'nav.documentRegistry': 'Kho văn bản',
    'nav.documentSearch': 'Tìm kiếm toàn văn',
    'nav.documentOCR': 'Nhận dạng văn bản (OCR)',

    // 8. Quản lý Dữ liệu
    'nav.dataManagement': 'Hạ tầng & Dữ liệu',
    'nav.datalake': 'Kho dữ liệu HVHC',
    'nav.uploadData': 'Tải lên Dữ liệu',
    'nav.queryData': 'Truy vấn Dữ liệu',
    'nav.manageData': 'Quản lý Dataset',
    'nav.etlAutomation': 'Tự động hóa ETL',
    'nav.files': 'Quản lý File',
    'nav.governanceCompliance': 'Tuân thủ Quy định',
    'nav.governanceLineage': 'Luồng dữ liệu (Lineage)',
    'nav.governanceRetention': 'Chính sách Lưu trữ',
    'nav.securityPolicy': 'Chính sách Bảo mật',
    
    // 9. ML & Mô hình
    'nav.mlModule': 'ML/AI - Machine Learning',
    'nav.mlModels': 'Mô hình ML',
    'nav.mlTraining': 'Huấn luyện',
    'nav.mlExperiments': 'Thí nghiệm ML',
    'nav.mlWorkflows': 'Quy trình ML',
    'nav.mlVersions': 'Phiên bản Model',
    'nav.mlTracking': 'Theo dõi ML',
    'nav.models': 'Danh sách Mô hình',
    'nav.experiments': 'Thí nghiệm',
    
    // 10. Quản trị Hệ thống
    'nav.systemAdmin': 'Quản trị Hệ thống',
    'nav.adminDashboard': 'Dashboard Admin',
    'nav.accountManagement': 'Quản lý Tài khoản',
    'nav.rbacManagement': 'Trung tâm RBAC',
    'nav.positionManagement': 'Quản lý Chức vụ',
    'nav.functionManagement': 'Quản lý Chức năng',
    'nav.sodManagement': 'Separation of Duties',
    'nav.linkPersonnel': 'Liên kết Nhân sự',
    'nav.unitManagement': 'Quản lý Đơn vị',
    'nav.departmentManagement': 'Quản lý Khoa/Phòng',
    'nav.permissionGrants': 'Ủy quyền Hồ sơ',
    'nav.rbacSoD': 'Phân tách Quyền hạn (SoD)',
    'nav.gradeCoefficients': 'Hệ số Môn học',
    'nav.auditLogs': 'Nhật ký Hoạt động',
    'nav.sessionManagement': 'Quản lý Phiên Đăng Nhập',
    'nav.securityHardening': 'Bảo mật & Hardening',
    'nav.aiSettings': 'Cấu hình AI',

    // 11. Hạ tầng & Dịch vụ
    'nav.infrastructure': 'Hạ tầng & Dịch vụ',
    'nav.services': 'Dịch vụ',
    'nav.apiGateway': 'Cổng API',
    'nav.infrastructureManagement': 'Cấu hình Hạ tầng',
    'nav.acceptanceDocs': 'Hồ sơ Nghiệm thu',
    'nav.projectReport': 'Báo cáo Sáng kiến',

    // 12. Giám sát & Bảo mật
    'nav.monitoringSecurity': 'Giám sát & Bảo mật',
    'nav.systemMonitoring': 'Giám sát Hệ thống',
    'nav.realtimeMonitoring': 'Giám sát Real-time',
    'nav.systemHealth': 'Sức khỏe Hệ thống',
    'nav.alerts': 'Cảnh báo',
    'nav.securityAudit': 'Kiểm toán Bảo mật',
    'nav.loginAudit': 'Nhật ký Đăng nhập',
    'nav.systemLogs': 'Nhật ký Hệ thống',
    
    // 13. Cài đặt
    'nav.settings': 'Cài đặt',
    'nav.generalSettings': 'Cài đặt Chung',
    'nav.notifications': 'Thông báo',
    'nav.accountSettings': 'Cài đặt Tài khoản',
    
    // Legacy keys (backward compatibility)
    'nav.dashboards': 'Bảng điều khiển',
    'nav.dashboard': 'Tổng quan',
    'nav.csdlQuanNhan': 'CSDL Quân nhân',
    'nav.csdlDangVien': 'CSDL Đảng viên',
    'nav.csdlThiDua': 'CSDL Thi đua KT',
    'nav.csdlChinhSach': 'CSDL Chính sách',
    'nav.csdlBaoHiem': 'CSDL Bảo hiểm XH',
    'nav.csdlGiangVien': 'CSDL Giảng viên',
    'nav.csdlHocVien': 'CSDL Học viên',
    'nav.personnelManagement': 'CSDL Quân nhân',
    'nav.partyWork': 'CSDL Đảng viên',
    'nav.policyEmulation': 'CSDL Chính sách',
    'nav.facultyManagement': 'CSDL Giảng viên',
    'nav.studentManagement': 'CSDL Học viên',
    'nav.personnelDirectory': 'CSDL Cán bộ',
    'nav.partyDashboard': 'Tổng quan CTĐ',
    'nav.partyMembers': 'Danh sách ĐV',
    'nav.policyDashboard': 'Tổng quan CS',
    'nav.facultyAnalytics': 'Phân tích Giảng viên',
    'nav.studentAnalytics': 'Phân tích Học viên',
    'nav.aiAnalytics': 'Trí tuệ Nhân tạo',
    'nav.trainingML': 'Đào tạo ML',
    'nav.monitoring': 'Giám sát',
    'nav.securityGovernance': 'Bảo mật & QT',
    'nav.configuration': 'Cấu hình',
    'nav.training': 'Huấn luyện',
    'nav.aiTraining': 'Huấn luyện AI',
    'nav.aiMonitor': 'Giám sát AI',
    'nav.aiUsageLogs': 'Nhật ký sử dụng AI',
    'nav.research': 'NCKH',
    'nav.data': 'Dữ liệu',
    'nav.upload': 'Tải lên',
    'nav.query': 'Truy vấn',
    'nav.preview': 'Xem trước',
    'nav.analytics': 'Phân tích',
    'nav.users': 'Người dùng',
    'nav.humanResources': 'Nhân sự',
    'nav.personnel': 'Hồ sơ CB',
    'nav.ml': 'Học máy',
    'nav.versions': 'Phiên bản',
    'nav.workflows': 'Quy trình',
    'nav.security': 'Bảo mật',
    'nav.audit': 'Kiểm toán',
    'nav.permissions': 'Phân quyền',
    'nav.policy': 'CS Bảo mật',
    'nav.tracking': 'Theo dõi HL',
    'nav.governance': 'Quản trị DL',
    'nav.compliance': 'Tuân thủ',
    'nav.retention': 'Lưu trữ',
    'nav.logs': 'Nhật ký',
    'nav.appearance': 'Giao diện',
    'nav.infrastructureServices': 'Hạ tầng',
    'nav.teachingManagement': 'Giảng dạy',
    'nav.csdlCanBo': 'CSDL Cán bộ',
    'nav.csdlQuanLuc': 'CSDL Quân lực',
    'code': 'vi',
    
    // Dashboard
    'dashboard.title': 'Hệ thống Quản lý BigData HVHC',
    'dashboard.welcome': 'Chào mừng',
    'dashboard.services': 'Dịch vụ',
    'dashboard.users': 'Người dùng',
    'dashboard.alerts': 'Cảnh báo',
    'dashboard.systemHealth': 'Tình trạng hệ thống',
    'dashboard.healthy': 'Khỏe mạnh',
    'dashboard.degraded': 'Suy giảm',
    'dashboard.down': 'Dừng',
    'dashboard.active': 'Hoạt động',
    'dashboard.total': 'Tổng',
    'dashboard.critical': 'Nghiêm trọng',
    'dashboard.warning': 'Cảnh báo',
    'dashboard.recentLogs': 'Nhật ký gần đây',
    'dashboard.serviceStatus': 'Trạng thái dịch vụ',
    'dashboard.resourceUsage': 'Sử dụng tài nguyên',
    
    // Users
    'users.title': 'Quản lý Người dùng',
    'users.addUser': 'Thêm người dùng',
    'users.searchPlaceholder': 'Tìm kiếm theo tên, email...',
    'users.name': 'Họ tên',
    'users.email': 'Email',
    'users.role': 'Vai trò',
    'users.status': 'Trạng thái',
    'users.department': 'Đơn vị',
    'users.actions': 'Thao tác',
    
    // Roles
    'role.ADMIN': 'Quản trị viên',
    'role.QUAN_TRI_HE_THONG': 'Quản trị hệ thống',
    'role.CHI_HUY_HOC_VIEN': 'Chỉ huy học viện',
    'role.CHI_HUY_KHOA_PHONG': 'Chỉ huy khoa/phòng',
    'role.CHU_NHIEM_BO_MON': 'Chủ nhiệm bộ môn',
    'role.GIANG_VIEN': 'Giảng viên',
    'role.NGHIEN_CUU_VIEN': 'Nghiên cứu viên',
    'role.HOC_VIEN_SINH_VIEN': 'Học viên/Sinh viên',
    'role.HOC_VIEN': 'Học viên quân sự',
    'role.KY_THUAT_VIEN': 'Kỹ thuật viên',
    
    // Status
    'status.ACTIVE': 'Hoạt động',
    'status.INACTIVE': 'Không hoạt động',
    'status.SUSPENDED': 'Tạm ngưng',
    'status.HEALTHY': 'Khỏe mạnh',
    'status.DEGRADED': 'Suy giảm',
    'status.DOWN': 'Dừng',
    'status.UNKNOWN': 'Không xác định',
    
    // Common
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.edit': 'Sửa',
    'common.delete': 'Xóa',
    'common.view': 'Xem',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.export': 'Xuất',
    'common.logout': 'Đăng xuất',
    'common.profile': 'Hồ sơ',
    'common.department': 'Khoa/Phòng',
    'common.clearFilters': 'Xóa bộ lọc',

    // Faculty
    'faculty.list': 'Danh sách Giảng viên',
    'faculty.listDescription': 'Quản lý và xem thông tin giảng viên',
    'faculty.searchPlaceholder': 'Tìm kiếm theo tên, email, mã số...',
    'faculty.allRanks': 'Tất cả học hàm',
    'faculty.allDegrees': 'Tất cả học vị',
    'faculty.academicRank': 'Học hàm',
    'faculty.academicDegree': 'Học vị',
    'faculty.noResults': 'Không tìm thấy giảng viên',
  },
  en: {
    // ============== NAVIGATION GROUPS ==============
    // 1. Overview
    'nav.overview': 'Overview',
    'nav.homepage': 'Homepage',
    'nav.mainDashboard': 'Main Dashboard',
    'nav.commandDashboard': 'Command Dashboard',
    'nav.autoDashboard': 'Auto Dashboard',
    'nav.myDashboard': 'My Dashboard',
    'nav.realtimeMonitor': 'Real-time Monitor',
    'nav.dashboardManagement': 'Widget Manager',
    'nav.masterData': 'Master Data (MDM)',

    // 2. Personal Profile
    'nav.personalProfile': 'Personal Profile',
    'nav.myProfile': 'My Profile',
    'nav.scientificCV': 'Scientific CV',

    // 3. Personnel Database
    'nav.personnelDatabase': 'Personnel Database',
    'nav.personnelOverview': 'Personnel DB Overview',
    'nav.personnelList': 'HVHC Personnel Database',
    'nav.personnelCreate': 'Add New Personnel',
    'nav.personnelStats': 'Personnel Statistics',
    'nav.officerManagement': 'Officer Management',
    'nav.soldierManagement': 'Soldier Management',
    'nav.personnelAdvancedSearch': 'Advanced Search',
    'nav.personnelSearch': 'Personnel Search',
    'nav.personnelPlanning': 'Personnel Planning',
    'nav.personnelImport': 'Import CSV Data',

    // 3. Party Database
    'nav.partyOverview': 'Party Overview',
    'nav.partyDatabase': 'Party Members DB',
     'nav.welfareDatabase': 'Welfare Database',    
    'nav.partyMemberList': 'Party Member List',
    'nav.partyMemberProfile360': 'Party Profile 360°',
    'nav.partyOrgStructure': 'Party Organization Structure',
    'nav.partyRecruitmentPipeline': 'Party Recruitment Pipeline',
    'nav.partyMemberCreate': 'Add Party Member',
    'nav.partyAdmissions': 'Admission Process',
    'nav.partyMeetings': 'Party Meetings',
    'nav.partyEvaluations': 'Member Evaluations',
    'nav.partyActivities': 'Party Activities',
    'nav.partyFees': 'Party Fee Management',
    'nav.partyAwards': 'Party Awards',
    'nav.partyAnnualReviews': 'Annual Reviews',
    'nav.partyDisciplines': 'Party Disciplines',
    'nav.partyTransfers': 'Party Transfer Management',
    'nav.partyInspections': 'Inspection & Supervision',

    // 4. Policy Database
    'nav.policyDatabase': 'Policy Database',
    'nav.policyOverview': 'Policy Overview',
    'nav.policyList': 'Policy List',
    'nav.policyCreate': 'Add Policy',
    'nav.policyCategories': 'Policy Categories',
    'nav.policyApproval': 'Approval Queue',
    'nav.welfare': 'Welfare Benefits',
    'nav.policyRequests': 'Policy Requests',
    'nav.policyRewards': 'Reward Policy',
    'nav.policyDiscipline': 'Discipline Policy',
    'nav.policyWelfare': 'Welfare Policy',

    // 5. Social Insurance Database
    'nav.insuranceDatabase': 'Social Insurance DB',
    'nav.insurance': 'Social Insurance',
    'nav.insuranceOverview': 'Insurance Overview',
    'nav.insuranceList': 'Insurance List',
    'nav.insuranceCreate': 'Add Insurance Record',
    'nav.insuranceContributions': 'Contributions',
    'nav.insuranceBenefits': 'Benefits',
    'nav.insuranceDependents': 'Dependents',
    'nav.insuranceClaims': 'Insurance Claims',
    'nav.medicalFacilities': 'Medical Facilities',
    
    // 6. Emulation & Rewards Database
    'nav.awardsDatabase': 'Awards Database',
    'nav.emulationRewardsDatabase': 'Emulation & Rewards DB',
    'nav.emulationOverview': 'Emulation Overview',
    'nav.awardsOverview': 'Awards Overview',
    'nav.awardsList': 'Awards List',
    'nav.awardsCreate': 'Add Award',
    'nav.rewardsList': 'Rewards List',
    'nav.rewardsCreate': 'Add Reward',
    'nav.emulationManagement': 'Emulation Management',
    'nav.emulationStats': 'Statistics by Unit',
    'nav.rewards': 'Rewards',
    'nav.discipline': 'Discipline',
    
    // 6. Faculty & Student Database
    'nav.facultyStudentDatabase': 'Faculty & Student DB',
    'nav.facultyStudentOverview': 'Faculty-Student Overview',
    'nav.facultyOverview': 'Faculty Overview',
    'nav.facultyList': 'Faculty List',
    'nav.facultyProfile': 'Faculty Profile',
    'nav.facultyResearch': 'Faculty Research',
    'nav.facultyScientificProfile': 'Faculty Scientific Profile',
    'nav.studentGuidance': 'Student Guidance',
    'nav.teachingStats': 'Teaching Statistics',
    'nav.studentList': 'Student List',
    'nav.studentStats': 'Student Statistics',
    'nav.scientificProfile': 'Scientific Profile',
    'nav.facultyImport': 'Bulk Import',
    'nav.myStudents': 'My Students',
    
    // 6.1 Education Database
    'nav.educationDatabase': 'Education Database',
    'nav.educationDatabaseOverview': 'Education DB Overview',
    'nav.educationModule': 'Education & Training',
    // Menu groups (new restructured)
    'nav.educationOverviewGroup':   'Education Overview',
    'nav.facultyManagementGroup':   'Faculty Management',
    'nav.trainingSystemGroup':      'Training Systems & Battalions',
    'nav.studentManagementGroup':   'Student Management',
    'nav.educationProgramGroup':    'Programs & Operations',
    // Menu items
    'nav.educationOverview': 'Education Overview',
    'nav.facultyOverview':   'Faculty Management',
    'nav.trainingSystems':   'Training Systems & Battalions',
    'nav.militaryStudents':  'Military Students',
    'nav.civilStudents':     'Civil Students',
    'nav.educationConduct':  'Conduct Records',
    'nav.educationThesis':   'Thesis Projects',
    'nav.educationGraduation': 'Graduation Review',
    'nav.educationStudents': 'All Students',
    'nav.educationPlanning': 'Training Planning',
    'nav.educationCourseSections': 'Course Sections',
    'nav.educationAttendance': 'Attendance',
    'nav.educationGrades': 'Grade Management',
    'nav.educationWarnings': 'Academic Warnings',
    'nav.educationPrograms': 'Training Programs',
    'nav.educationCurriculum': 'Curriculum',
    'nav.educationSubjects': 'Subjects',
    'nav.educationCoefficients': 'Course Coefficients',
    'nav.educationSchedule': 'Schedule',
    'nav.educationTeachingAssignment': 'Teaching Assignment',
    'nav.educationRooms': 'Classrooms',
    'nav.educationExamPlan': 'Exam Plan',
    'nav.educationQuestionBank': 'Question Bank',
    'nav.educationLearningMaterials': 'Learning Materials',
    'nav.educationLab': 'Laboratory',
    'nav.programOverview': 'Program Overview',
    'nav.programs': 'Training Programs',
    'nav.curriculum': 'Curriculum Framework',
    'nav.subjectManagement': 'Subject Management',
    'nav.courseCoefficients': 'Course Coefficients',
    'nav.trainingSchedule': 'Training Schedule',
    'nav.teachingAssignment': 'Teaching Assignment',
    'nav.classroomManagement': 'Classroom Management',
    'nav.examPlan': 'Exam & QA',
    'nav.questionBank': 'Question Bank',
    'nav.learningMaterials': 'Learning Materials',
    'nav.labManagement': 'Laboratory',
    
    // 9b. Science Management Database (CSDL-KHQL)
    'nav.scienceDatabase':    'Science Management DB',
    'nav.scienceDashboard':   'Science Overview',
    'nav.scienceProjects':    'Research Projects',
    'nav.scienceActivities':  'Project Lifecycle',
    'nav.scienceScientists':  'Scientists',
    'nav.scienceCouncils':    'Scientific Councils',
    'nav.scienceBudgets':     'Research Budget',
    'nav.scienceLibrary':     'Digital Library',
    'nav.scienceCatalogs':    'Science Catalogs',
    'nav.scienceWorks':             'Scientific Works',
    'nav.scienceSearch':            'Smart Search',
    'nav.scienceDataQuality':       'Data Quality',
    'nav.scienceDataHubOverview':   'Science Data Hub (M22)',
    'nav.scienceDataHubRecords':    'Unified Records',
    'nav.scienceAiTools':           'AI Tools',
    'nav.scienceReports':           'Export BQP Reports',

    // 7. Research Database
    'nav.researchDatabase': 'Research Database',
    'nav.researchOverview': 'Research DB Overview',
    'nav.researchManagement': 'Research Management',
    'nav.researchCreate': 'Add Research Project',
    'nav.scientistsList': 'Scientists List',
    'nav.researchScientists': 'Scientists List',
    'nav.researchDetailOverview': 'Detailed Overview',
    'nav.researchIntegration': 'Research Integration',
    'nav.aiResearchTrends': 'AI Research Trends',
    'nav.aiTrends': 'AI Research Trends',
    'nav.teachingResearch': 'Teaching & Research',
    'nav.teachingSubjects': 'Teaching Subjects',
    'nav.teachingAnalytics': 'Teaching Analytics',
    'nav.researchProjects': 'Research Projects',
    'nav.researchPublications': 'Publications',
    'nav.researchCapacityMap': 'Capacity Map',
    'nav.researchRepository': 'Research Repository',
    'nav.researchCenter': 'Research Center',
    'nav.trainingPrograms': 'Training Programs',
    
    // 7. Analytics & AI
    'nav.analyticsAI': 'Analytics & AI',
    'nav.analyticsReports': 'Analytics & Reports',
    'nav.basicAnalytics': 'Basic Analytics',
    'nav.advancedAnalytics': 'Advanced Analytics',
    'nav.aiAdvisor': 'AI Command Intelligence',
    'nav.aiDashboard': 'AI Dashboard',
    'nav.aiPersonnel': 'AI Personnel',
    'nav.reports': 'Reports',
    'nav.templates': 'Templates & Exports',
    'nav.templateExport': 'Templates & Data Export',
    'nav.templateLibrary': 'Template Library',
    'nav.exportJobs': 'Export History',
    'nav.scheduledExports': 'Scheduled Exports',
    'nav.kpis': 'KPIs & Metrics',
    'nav.realtimeKpis': 'Realtime KPIs',

    // W. Workflow Engine (M13)
    'nav.workflowModule': 'Workflow Engine',
    'nav.workflowDashboard': 'Workflow Dashboard',
    'nav.workflowDefinitions': 'Workflow Definitions',
    'nav.workflowMyWork': 'My Work',
    'nav.workflowInstances': 'All Instances',
    'nav.workflowDesigner': 'Workflow Designer',

    // D. Digital Documents (M16)
    'nav.digitalDocsModule': 'Digital Documents',
    'nav.documentRegistry': 'Document Registry',
    'nav.documentSearch': 'Full-Text Search',
    'nav.documentOCR': 'OCR Recognition',

    // 8. Data Management
    'nav.dataManagement': 'Data Management',
    'nav.datalake': 'HVHC Data Lake',
    'nav.uploadData': 'Upload Data',
    'nav.queryData': 'Query Data',
    'nav.manageData': 'Manage Dataset',
    'nav.files': 'File Management',
    
    // 9. ML & Models
    'nav.mlModule': 'ML/AI - Machine Learning',
    'nav.mlModels': 'ML Models',
    'nav.mlTraining': 'Training',
    'nav.mlExperiments': 'Experiments',
    'nav.mlWorkflows': 'Workflows',
    'nav.mlVersions': 'Model Versions',
    'nav.mlTracking': 'ML Tracking',
    'nav.models': 'Model List',
    'nav.experiments': 'Experiments',
    
    // 10. System Administration
    'nav.systemAdmin': 'System Admin',
    'nav.adminDashboard': 'Admin Dashboard',
    'nav.accountManagement': 'Account Management',
    'nav.rbacManagement': 'RBAC Center',
    'nav.positionManagement': 'Position Management',
    'nav.functionManagement': 'Function Management',
    'nav.sodManagement': 'Separation of Duties',
    'nav.linkPersonnel': 'Link Personnel',
    'nav.unitManagement': 'Unit Management',
    'nav.departmentManagement': 'Department Management',
    'nav.permissionGrants': 'Permission Grants',
    'nav.auditLogs': 'Audit Logs',
    'nav.sessionManagement': 'Session Management',
    'nav.securityHardening': 'Security Hardening',
    'nav.aiSettings': 'AI Settings',

    // 11. Infrastructure & Services
    'nav.infrastructure': 'Infrastructure',
    'nav.services': 'Services',
    'nav.apiGateway': 'API Gateway',
    'nav.infrastructureManagement': 'Infrastructure Config',
    'nav.acceptanceDocs': 'Acceptance Documents',
    'nav.projectReport': 'Project Report',

    // 12. Monitoring & Security
    'nav.monitoringSecurity': 'Monitoring & Security',
    'nav.systemMonitoring': 'System Monitoring',
    'nav.realtimeMonitoring': 'Real-time Monitoring',
    'nav.systemHealth': 'System Health',
    'nav.alerts': 'Alerts',
    'nav.securityAudit': 'Security Audit',
    'nav.loginAudit': 'Login Audit',
    'nav.systemLogs': 'System Logs',
    
    // 13. Settings
    'nav.settings': 'Settings',
    'nav.generalSettings': 'General Settings',
    'nav.notifications': 'Notifications',
    'nav.accountSettings': 'Account Settings',
    
    // Legacy keys (backward compatibility)
    'nav.dashboards': 'Dashboards',
    'nav.dashboard': 'Dashboard',
    'nav.csdlQuanNhan': 'Personnel DB',
    'nav.csdlDangVien': 'Party Members DB',
    'nav.csdlThiDua': 'Awards DB',
    'nav.csdlChinhSach': 'Policy DB',
    'nav.csdlBaoHiem': 'Insurance DB',
    'nav.csdlGiangVien': 'Faculty DB',
    'nav.csdlHocVien': 'Students DB',
    'nav.personnelManagement': 'Personnel DB',
    'nav.partyWork': 'Party Members DB',
    'nav.policyEmulation': 'Policy DB',
    'nav.facultyManagement': 'Faculty DB',
    'nav.studentManagement': 'Students DB',
    'nav.personnelDirectory': 'Personnel Directory',
    'nav.partyDashboard': 'Party Overview',
    'nav.partyMembers': 'Party Members',
    'nav.policyDashboard': 'Policy Overview',
    'nav.facultyAnalytics': 'AI Analytics - EIS',
    'nav.studentAnalytics': 'AI Student Analytics',
    'nav.aiAnalytics': 'AI Analytics',
    'nav.trainingML': 'ML Training',
    'nav.monitoring': 'Monitoring',
    'nav.securityGovernance': 'Security & Governance',
    'nav.configuration': 'Configuration',
    'nav.training': 'Training',
    'nav.aiTraining': 'AI Training',
    'nav.aiMonitor': 'AI Monitor',
    'nav.aiUsageLogs': 'AI Usage Logs',
    'nav.research': 'Research',
    'nav.data': 'Data',
    'nav.upload': 'Upload',
    'nav.query': 'Query',
    'nav.preview': 'Preview',
    'nav.analytics': 'Analytics',
    'nav.users': 'Users',
    'nav.humanResources': 'Human Resources',
    'nav.personnel': 'Personnel Records',
    'nav.ml': 'Machine Learning',
    'nav.versions': 'Versions',
    'nav.workflows': 'Workflows',
    'nav.security': 'Security',
    'nav.audit': 'Audit Trail',
    'nav.permissions': 'Permissions',
    'nav.policy': 'Security Policy',
    'nav.tracking': 'Training Tracking',
    'nav.governance': 'Governance',
    'nav.compliance': 'Compliance',
    'nav.retention': 'Retention',
    'nav.logs': 'Logs',
    'nav.appearance': 'Appearance',
    'nav.infrastructureServices': 'Infrastructure',
    'nav.teachingManagement': 'Teaching',
    'nav.csdlCanBo': 'Officer DB',
    'nav.csdlQuanLuc': 'Soldier DB',
    'code': 'en',
    
    // Dashboard
    'dashboard.title': 'HVHC BigData Management System',
    'dashboard.welcome': 'Welcome',
    'dashboard.services': 'Services',
    'dashboard.users': 'Users',
    'dashboard.alerts': 'Alerts',
    'dashboard.systemHealth': 'System Health',
    'dashboard.healthy': 'Healthy',
    'dashboard.degraded': 'Degraded',
    'dashboard.down': 'Down',
    'dashboard.active': 'Active',
    'dashboard.total': 'Total',
    'dashboard.critical': 'Critical',
    'dashboard.warning': 'Warning',
    'dashboard.recentLogs': 'Recent Logs',
    'dashboard.serviceStatus': 'Service Status',
    'dashboard.resourceUsage': 'Resource Usage',
    
    // Users
    'users.title': 'User Management',
    'users.addUser': 'Add User',
    'users.searchPlaceholder': 'Search by name, email...',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.department': 'Department',
    'users.actions': 'Actions',
    
    // Roles
    'role.ADMIN': 'Administrator',
    'role.QUAN_TRI_HE_THONG': 'System Administrator',
    'role.CHI_HUY_HOC_VIEN': 'Academy Commander',
    'role.CHI_HUY_KHOA_PHONG': 'Faculty/Department Commander',
    'role.CHU_NHIEM_BO_MON': 'Department Head',
    'role.GIANG_VIEN': 'Instructor',
    'role.NGHIEN_CUU_VIEN': 'Researcher',
    'role.HOC_VIEN_SINH_VIEN': 'Student',
    'role.HOC_VIEN': 'Military Student',
    'role.KY_THUAT_VIEN': 'Technician',
    
    // Status
    'status.ACTIVE': 'Active',
    'status.INACTIVE': 'Inactive',
    'status.SUSPENDED': 'Suspended',
    'status.HEALTHY': 'Healthy',
    'status.DEGRADED': 'Degraded',
    'status.DOWN': 'Down',
    'status.UNKNOWN': 'Unknown',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.logout': 'Logout',
    'common.profile': 'Profile',
    'common.department': 'Department',
    'common.clearFilters': 'Clear Filters',

    // Faculty
    'faculty.list': 'Faculty List',
    'faculty.listDescription': 'Manage and view faculty information',
    'faculty.searchPlaceholder': 'Search by name, email, ID...',
    'faculty.allRanks': 'All Ranks',
    'faculty.allDegrees': 'All Degrees',
    'faculty.academicRank': 'Academic Rank',
    'faculty.academicDegree': 'Academic Degree',
    'faculty.noResults': 'No faculty found',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('vi');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
