/**
 * Seed M19 – Master Data Management
 * Run: npx tsx --require dotenv/config prisma/seed/seed_master_data.ts
 *
 * Options (env):
 *   SEED_OVERWRITE=true   – ghi đè tất cả kể cả item đã admin chỉnh
 *   SEED_SKIP_VERSION=true – bỏ qua category đã ở đúng version
 */
import { PrismaClient } from '@prisma/client'
import {
  upsertCategoryWithItems,
  type SeedMeta,
} from './lib/mdm-upsert'

const prisma = new PrismaClient()

const SEED_META: SeedMeta = {
  version: '1.0',
  bundleId: 'seed_master_data_2026',
  allowOverwrite: process.env.SEED_OVERWRITE === 'true',
  skipIfVersionMatch: process.env.SEED_SKIP_VERSION === 'true',
}

type ItemInput = {
  code: string
  nameVi: string
  nameEn?: string
  shortName?: string
  parentCode?: string
  externalCode?: string
  sortOrder?: number
  metadata?: Record<string, unknown>
}

// ── CATEGORIES (68 danh mục / 11 nhóm) ──────────────────────────────────────

const CATEGORIES = [
  { code: 'MD_RANK', nameVi: 'Cấp bậc / Quân hàm', nameEn: 'Military Rank', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'BQP', sortOrder: 1 },
  { code: 'MD_POSITION_TYPE', nameVi: 'Loại chức vụ', nameEn: 'Position Type', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 2 },
  { code: 'MD_PERSONNEL_TYPE', nameVi: 'Loại quân nhân', nameEn: 'Personnel Type', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'BQP', sortOrder: 3 },
  { code: 'MD_OFFICER_CATEGORY', nameVi: 'Diện cán bộ', nameEn: 'Officer Category', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'BQP', sortOrder: 4 },
  { code: 'MD_SALARY_GRADE', nameVi: 'Ngạch lương', nameEn: 'Salary Grade', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'BQP', sortOrder: 5 },
  { code: 'MD_SALARY_ALLOWANCE', nameVi: 'Loại phụ cấp', nameEn: 'Allowance Type', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'BQP', sortOrder: 6 },
  { code: 'MD_UNIT_TYPE', nameVi: 'Loại đơn vị', nameEn: 'Unit Type', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 7 },
  { code: 'MD_UNIT_LEVEL', nameVi: 'Cấp đơn vị', nameEn: 'Unit Level', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 8 },
  { code: 'MD_MILITARY_REGION', nameVi: 'Quân khu', nameEn: 'Military Region', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'BQP', sortOrder: 9 },
  { code: 'MD_BRANCH', nameVi: 'Quân chủng / Binh chủng', nameEn: 'Military Branch', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'BQP', sortOrder: 10 },
  { code: 'MD_PROVINCE', nameVi: 'Tỉnh / Thành phố', nameEn: 'Province', groupTag: 'GEOGRAPHY', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 11 },
  { code: 'MD_DISTRICT', nameVi: 'Quận / Huyện', nameEn: 'District', groupTag: 'GEOGRAPHY', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 12 },
  { code: 'MD_WARD', nameVi: 'Phường / Xã', nameEn: 'Ward', groupTag: 'GEOGRAPHY', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 13 },
  { code: 'MD_COUNTRY', nameVi: 'Quốc gia', nameEn: 'Country', groupTag: 'GEOGRAPHY', cacheType: 'STATIC', sourceType: 'ISO', sortOrder: 14 },
  { code: 'MD_HOMETOWN_REGION', nameVi: 'Vùng miền', nameEn: 'Region', groupTag: 'GEOGRAPHY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 15 },
  { code: 'MD_ETHNICITY', nameVi: 'Dân tộc', nameEn: 'Ethnicity', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 16 },
  { code: 'MD_RELIGION', nameVi: 'Tôn giáo', nameEn: 'Religion', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 17 },
  { code: 'MD_POLITICAL_LEVEL', nameVi: 'Trình độ lý luận chính trị', nameEn: 'Political Theory Level', groupTag: 'PARTY', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 18 },
  { code: 'MD_EDUCATION_LEVEL', nameVi: 'Trình độ học vấn', nameEn: 'Education Level', groupTag: 'EDUCATION', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 19 },
  { code: 'MD_ACADEMIC_DEGREE', nameVi: 'Học vị', nameEn: 'Academic Degree', groupTag: 'EDUCATION', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 20 },
  { code: 'MD_ACADEMIC_TITLE', nameVi: 'Học hàm', nameEn: 'Academic Title', groupTag: 'EDUCATION', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 21 },
  { code: 'MD_PROFESSIONAL_TITLE', nameVi: 'Chức danh nghề nghiệp', nameEn: 'Professional Title', groupTag: 'EDUCATION', cacheType: 'SEMI', sourceType: 'NATIONAL', sortOrder: 22 },
  { code: 'MD_STUDY_MODE', nameVi: 'Hình thức đào tạo', nameEn: 'Study Mode', groupTag: 'EDUCATION', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 23 },
  { code: 'MD_MAJOR', nameVi: 'Chuyên ngành đào tạo', nameEn: 'Academic Major', groupTag: 'EDUCATION', cacheType: 'SEMI', sourceType: 'NATIONAL', sortOrder: 24 },
  { code: 'MD_INSTITUTION', nameVi: 'Cơ sở đào tạo', nameEn: 'Educational Institution', groupTag: 'EDUCATION', cacheType: 'DYNAMIC', sourceType: 'NATIONAL', sortOrder: 25 },
  { code: 'MD_LANGUAGE', nameVi: 'Ngoại ngữ', nameEn: 'Foreign Language', groupTag: 'EDUCATION', cacheType: 'STATIC', sourceType: 'ISO', sortOrder: 26 },
  { code: 'MD_LANGUAGE_LEVEL', nameVi: 'Trình độ ngoại ngữ', nameEn: 'Language Level', groupTag: 'EDUCATION', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 27 },
  { code: 'MD_IT_LEVEL', nameVi: 'Trình độ tin học', nameEn: 'IT Level', groupTag: 'EDUCATION', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 28 },
  { code: 'MD_PARTY_CATEGORY', nameVi: 'Phân loại đảng viên', nameEn: 'Party Member Category', groupTag: 'PARTY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 29 },
  { code: 'MD_PARTY_EVAL_TYPE', nameVi: 'Loại xếp loại đảng viên', nameEn: 'Party Eval Classification', groupTag: 'PARTY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 30 },
  { code: 'MD_PARTY_DISCIPLINE', nameVi: 'Hình thức kỷ luật Đảng', nameEn: 'Party Discipline Type', groupTag: 'PARTY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 31 },
  { code: 'MD_PARTY_ROLE', nameVi: 'Chức vụ Đảng', nameEn: 'Party Role', groupTag: 'PARTY', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 32 },
  { code: 'MD_YOUTH_ORG', nameVi: 'Tổ chức đoàn thể', nameEn: 'Youth Organization', groupTag: 'PARTY', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 33 },
  { code: 'MD_INSURANCE_TYPE', nameVi: 'Loại bảo hiểm', nameEn: 'Insurance Type', groupTag: 'SYSTEM', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 34 },
  { code: 'MD_MEDICAL_FACILITY', nameVi: 'Cơ sở KCB đăng ký', nameEn: 'Medical Facility', groupTag: 'SYSTEM', cacheType: 'DYNAMIC', sourceType: 'NATIONAL', sortOrder: 35 },
  { code: 'MD_DISEASE_GROUP', nameVi: 'Nhóm bệnh / ICD-10', nameEn: 'Disease Group', groupTag: 'SYSTEM', cacheType: 'STATIC', sourceType: 'ISO', sortOrder: 36 },
  { code: 'MD_LEAVE_TYPE', nameVi: 'Loại nghỉ phép', nameEn: 'Leave Type', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'BQP', sortOrder: 37 },
  { code: 'MD_BENEFIT_TYPE', nameVi: 'Loại chế độ ưu đãi', nameEn: 'Benefit Type', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'NATIONAL', sortOrder: 38 },
  { code: 'MD_RETIREMENT_REASON', nameVi: 'Lý do xuất ngũ / hưu', nameEn: 'Retirement Reason', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'BQP', sortOrder: 39 },
  { code: 'MD_AWARD_TYPE', nameVi: 'Loại khen thưởng', nameEn: 'Award Type', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'BQP', sortOrder: 40 },
  { code: 'MD_AWARD_LEVEL', nameVi: 'Cấp khen thưởng', nameEn: 'Award Level', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 41 },
  { code: 'MD_EMULATION_TITLE', nameVi: 'Danh hiệu thi đua', nameEn: 'Emulation Title', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'NATIONAL', sortOrder: 42 },
  { code: 'MD_DISCIPLINE_TYPE', nameVi: 'Hình thức kỷ luật', nameEn: 'Discipline Type', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'BQP', sortOrder: 43 },
  { code: 'MD_DISCIPLINE_REASON', nameVi: 'Lý do kỷ luật', nameEn: 'Discipline Reason', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'BQP', sortOrder: 44 },
  { code: 'MD_ACHIEVEMENT_FIELD', nameVi: 'Lĩnh vực thành tích', nameEn: 'Achievement Field', groupTag: 'MILITARY', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 45 },
  { code: 'MD_TRAINING_SYSTEM', nameVi: 'Hệ đào tạo', nameEn: 'Training System', groupTag: 'TRAINING', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 46 },
  { code: 'MD_SUBJECT_TYPE', nameVi: 'Loại môn học', nameEn: 'Subject Type', groupTag: 'TRAINING', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 47 },
  { code: 'MD_SUBJECT_GROUP', nameVi: 'Nhóm môn học', nameEn: 'Subject Group', groupTag: 'TRAINING', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 48 },
  { code: 'MD_GRADE_COMPONENT', nameVi: 'Thành phần điểm', nameEn: 'Grade Component', groupTag: 'TRAINING', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 49 },
  { code: 'MD_ACADEMIC_RESULT', nameVi: 'Xếp loại học lực', nameEn: 'Academic Result', groupTag: 'TRAINING', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 50 },
  { code: 'MD_CONDUCT_RESULT', nameVi: 'Xếp loại rèn luyện', nameEn: 'Conduct Classification', groupTag: 'TRAINING', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 51 },
  { code: 'MD_RESEARCH_TYPE', nameVi: 'Loại đề tài NCKH', nameEn: 'Research Type', groupTag: 'TRAINING', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 52 },
  { code: 'MD_RESEARCH_FIELD', nameVi: 'Lĩnh vực nghiên cứu', nameEn: 'Research Field', groupTag: 'TRAINING', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 53 },
  { code: 'MD_PUBLICATION_TYPE', nameVi: 'Loại công bố KH', nameEn: 'Publication Type', groupTag: 'TRAINING', cacheType: 'STATIC', sourceType: 'NATIONAL', sortOrder: 54 },
  { code: 'MD_JOURNAL', nameVi: 'Tạp chí KH', nameEn: 'Scientific Journal', groupTag: 'TRAINING', cacheType: 'DYNAMIC', sourceType: 'LOCAL', sortOrder: 55 },
  { code: 'MD_INNOVATION_LEVEL', nameVi: 'Cấp sáng kiến', nameEn: 'Innovation Level', groupTag: 'TRAINING', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 56 },
  { code: 'MD_EQUIPMENT_TYPE', nameVi: 'Loại trang bị', nameEn: 'Equipment Type', groupTag: 'EQUIPMENT', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 57 },
  { code: 'MD_EQUIPMENT_STATUS', nameVi: 'Trạng thái trang bị', nameEn: 'Equipment Status', groupTag: 'EQUIPMENT', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 58 },
  { code: 'MD_MAINTENANCE_TYPE', nameVi: 'Loại bảo dưỡng', nameEn: 'Maintenance Type', groupTag: 'EQUIPMENT', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 59 },
  { code: 'MD_MATERIAL_CATEGORY', nameVi: 'Nhóm vật tư', nameEn: 'Material Category', groupTag: 'EQUIPMENT', cacheType: 'SEMI', sourceType: 'LOCAL', sortOrder: 60 },
  { code: 'MD_FUEL_TYPE', nameVi: 'Loại nhiên liệu', nameEn: 'Fuel Type', groupTag: 'EQUIPMENT', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 61 },
  { code: 'MD_UNIT_OF_MEASURE', nameVi: 'Đơn vị đo lường', nameEn: 'Unit of Measure', groupTag: 'EQUIPMENT', cacheType: 'STATIC', sourceType: 'ISO', sortOrder: 62 },
  { code: 'MD_WORKFLOW_STATUS', nameVi: 'Trạng thái Workflow', nameEn: 'Workflow Status', groupTag: 'SYSTEM', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 63 },
  { code: 'MD_NOTIFICATION_TYPE', nameVi: 'Loại thông báo', nameEn: 'Notification Type', groupTag: 'SYSTEM', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 64 },
  { code: 'MD_FILE_FORMAT', nameVi: 'Định dạng file', nameEn: 'File Format', groupTag: 'SYSTEM', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 65 },
  { code: 'MD_SCOPE_LEVEL', nameVi: 'Cấp độ phạm vi RBAC', nameEn: 'RBAC Scope Level', groupTag: 'SYSTEM', cacheType: 'STATIC', sourceType: 'LOCAL', sortOrder: 66 },
  { code: 'MD_SYSTEM_CONFIG', nameVi: 'Cấu hình hệ thống', nameEn: 'System Configuration', groupTag: 'SYSTEM', cacheType: 'DYNAMIC', sourceType: 'LOCAL', sortOrder: 67 },
  { code: 'MD_ACADEMIC_YEAR', nameVi: 'Năm học / Học kỳ', nameEn: 'Academic Year', groupTag: 'TRAINING', cacheType: 'DYNAMIC', sourceType: 'LOCAL', sortOrder: 68 },
  { code: 'MD_BLOOD_TYPE', nameVi: 'Nhóm máu', nameEn: 'Blood Type', groupTag: 'MILITARY', cacheType: 'STATIC', sourceType: 'ISO', sortOrder: 69 },
]

// ── ITEMS (dữ liệu đầy đủ cho các danh mục cốt lõi) ─────────────────────────

const ITEMS: Record<string, ItemInput[]> = {
  MD_RANK: [
    { code: 'BINH_NHI', nameVi: 'Binh nhì', nameEn: 'Private', shortName: 'B2', sortOrder: 1, metadata: { type: 'ARMY' } },
    { code: 'BINH_NHAT', nameVi: 'Binh nhất', nameEn: 'Private First Class', shortName: 'B1', sortOrder: 2, metadata: { type: 'ARMY' } },
    { code: 'HA_SI', nameVi: 'Hạ sĩ', nameEn: 'Corporal', shortName: 'H.Sĩ', sortOrder: 3, metadata: { type: 'ARMY' } },
    { code: 'TRUNG_SI', nameVi: 'Trung sĩ', nameEn: 'Sergeant', shortName: 'T.Sĩ', sortOrder: 4, metadata: { type: 'ARMY' } },
    { code: 'THUONG_SI', nameVi: 'Thượng sĩ', nameEn: 'Staff Sergeant', shortName: 'Th.Sĩ', sortOrder: 5, metadata: { type: 'ARMY' } },
    { code: 'CHUAN_UY', nameVi: 'Chuẩn úy', nameEn: 'Warrant Officer', shortName: 'C.Úy', sortOrder: 6, metadata: { type: 'OFFICER' } },
    { code: 'THIEU_UY', nameVi: 'Thiếu úy', nameEn: 'Second Lieutenant', shortName: 'Th.Úy', sortOrder: 7, metadata: { type: 'OFFICER' } },
    { code: 'TRUNG_UY', nameVi: 'Trung úy', nameEn: 'First Lieutenant', shortName: 'T.Úy', sortOrder: 8, metadata: { type: 'OFFICER' } },
    { code: 'THUONG_UY', nameVi: 'Thượng úy', nameEn: 'Captain', shortName: 'Th.Úy', sortOrder: 9, metadata: { type: 'OFFICER' } },
    { code: 'DAI_UY', nameVi: 'Đại úy', nameEn: 'Senior Captain', shortName: 'Đ.Úy', sortOrder: 10, metadata: { type: 'OFFICER' } },
    { code: 'THIEU_TA', nameVi: 'Thiếu tá', nameEn: 'Major', shortName: 'T.Tá', sortOrder: 11, metadata: { type: 'OFFICER' } },
    { code: 'TRUNG_TA', nameVi: 'Trung tá', nameEn: 'Lieutenant Colonel', shortName: 'Tr.Tá', sortOrder: 12, metadata: { type: 'OFFICER' } },
    { code: 'THUONG_TA', nameVi: 'Thượng tá', nameEn: 'Colonel', shortName: 'Th.Tá', sortOrder: 13, metadata: { type: 'OFFICER' } },
    { code: 'DAI_TA', nameVi: 'Đại tá', nameEn: 'Senior Colonel', shortName: 'Đ.Tá', sortOrder: 14, metadata: { type: 'OFFICER' } },
    { code: 'THIEU_TUONG', nameVi: 'Thiếu tướng', nameEn: 'Major General', shortName: 'Th.Tướng', sortOrder: 15, metadata: { type: 'GENERAL' } },
    { code: 'TRUNG_TUONG', nameVi: 'Trung tướng', nameEn: 'Lieutenant General', shortName: 'T.Tướng', sortOrder: 16, metadata: { type: 'GENERAL' } },
    { code: 'THUONG_TUONG', nameVi: 'Thượng tướng', nameEn: 'General', shortName: 'Th.Tướng', sortOrder: 17, metadata: { type: 'GENERAL' } },
    { code: 'DAI_TUONG', nameVi: 'Đại tướng', nameEn: 'General of the Army', shortName: 'Đ.Tướng', sortOrder: 18, metadata: { type: 'GENERAL' } },
    { code: 'QNCN_1', nameVi: 'QNCN bậc 1', nameEn: 'Professional Soldier Grade 1', shortName: 'QNCN1', sortOrder: 19, metadata: { type: 'QNCN' } },
    { code: 'QNCN_2', nameVi: 'QNCN bậc 2', nameEn: 'Professional Soldier Grade 2', shortName: 'QNCN2', sortOrder: 20, metadata: { type: 'QNCN' } },
    { code: 'QNCN_3', nameVi: 'QNCN bậc 3', nameEn: 'Professional Soldier Grade 3', shortName: 'QNCN3', sortOrder: 21, metadata: { type: 'QNCN' } },
    { code: 'QNCN_4', nameVi: 'QNCN bậc 4', nameEn: 'Professional Soldier Grade 4', shortName: 'QNCN4', sortOrder: 22, metadata: { type: 'QNCN' } },
    { code: 'QNCN_5', nameVi: 'QNCN bậc 5', nameEn: 'Professional Soldier Grade 5', shortName: 'QNCN5', sortOrder: 23, metadata: { type: 'QNCN' } },
    { code: 'QNCN_6', nameVi: 'QNCN bậc 6', nameEn: 'Professional Soldier Grade 6', shortName: 'QNCN6', sortOrder: 24, metadata: { type: 'QNCN' } },
  ],
  MD_EDUCATION_LEVEL: [
    { code: 'TIEU_HOC', nameVi: 'Tiểu học', nameEn: 'Primary School', shortName: 'TH', sortOrder: 1 },
    { code: 'THCS', nameVi: 'Trung học cơ sở', nameEn: 'Middle School', shortName: 'THCS', sortOrder: 2 },
    { code: 'THPT', nameVi: 'Trung học phổ thông', nameEn: 'High School', shortName: 'THPT', sortOrder: 3 },
    { code: 'TRUNG_CAP', nameVi: 'Trung cấp', nameEn: 'Vocational Secondary', shortName: 'TC', sortOrder: 4 },
    { code: 'CAO_DANG', nameVi: 'Cao đẳng', nameEn: 'College', shortName: 'CĐ', sortOrder: 5 },
    { code: 'DAI_HOC', nameVi: 'Đại học', nameEn: 'University', shortName: 'ĐH', sortOrder: 6 },
    { code: 'CU_NHAN_VB2', nameVi: 'Cử nhân (văn bằng 2)', nameEn: 'Bachelor (2nd degree)', shortName: 'CN', sortOrder: 7 },
    { code: 'THAC_SI', nameVi: 'Thạc sĩ', nameEn: 'Master', shortName: 'ThS', sortOrder: 8 },
    { code: 'TIEN_SI', nameVi: 'Tiến sĩ', nameEn: 'Doctor', shortName: 'TS', sortOrder: 9 },
    { code: 'TIEN_SI_KHOA_HOC', nameVi: 'Tiến sĩ Khoa học', nameEn: 'Doctor of Science', shortName: 'TSKH', sortOrder: 10 },
    { code: 'PHO_GIAO_SU', nameVi: 'Phó Giáo sư', nameEn: 'Associate Professor', shortName: 'PGS', sortOrder: 11 },
    { code: 'GIAO_SU', nameVi: 'Giáo sư', nameEn: 'Professor', shortName: 'GS', sortOrder: 12 },
  ],
  MD_ETHNICITY: [
    { code: 'KINH', nameVi: 'Kinh', nameEn: 'Kinh', shortName: 'Kinh', sortOrder: 1 },
    { code: 'TAY', nameVi: 'Tày', nameEn: 'Tay', shortName: 'Tày', sortOrder: 2 },
    { code: 'THAI', nameVi: 'Thái', nameEn: 'Thai', shortName: 'Thái', sortOrder: 3 },
    { code: 'MUONG', nameVi: 'Mường', nameEn: 'Muong', shortName: 'Mường', sortOrder: 4 },
    { code: 'KHMER', nameVi: 'Khmer', nameEn: 'Khmer', shortName: 'Khmer', sortOrder: 5 },
    { code: 'HOA', nameVi: 'Hoa', nameEn: 'Chinese', shortName: 'Hoa', sortOrder: 6 },
    { code: 'NUNG', nameVi: 'Nùng', nameEn: 'Nung', shortName: 'Nùng', sortOrder: 7 },
    { code: 'HMONG', nameVi: 'Hmông', nameEn: 'Hmong', shortName: 'Hmông', sortOrder: 8 },
    { code: 'DAO', nameVi: 'Dao', nameEn: 'Dao', shortName: 'Dao', sortOrder: 9 },
    { code: 'GIA_RAI', nameVi: 'Gia Rai', nameEn: 'Gia Rai', shortName: 'GRai', sortOrder: 10 },
    { code: 'E_DE', nameVi: 'Ê Đê', nameEn: 'Ede', shortName: 'ĐĐ', sortOrder: 11 },
    { code: 'BA_NA', nameVi: 'Ba Na', nameEn: 'Ba Na', shortName: 'BNa', sortOrder: 12 },
    { code: 'XTIENG', nameVi: 'Xtiêng', nameEn: 'Xtieng', shortName: 'XTng', sortOrder: 13 },
    { code: 'CHAM', nameVi: 'Chăm', nameEn: 'Cham', shortName: 'Chăm', sortOrder: 14 },
    { code: 'CO_HO', nameVi: 'Cơ Ho', nameEn: 'Co Ho', shortName: 'CHo', sortOrder: 15 },
    { code: 'XODANG', nameVi: 'Xơ Đăng', nameEn: 'Xo Dang', shortName: 'XĐăng', sortOrder: 16 },
    { code: 'SAN_CHAY', nameVi: 'Sán Chay', nameEn: 'San Chay', shortName: 'SChay', sortOrder: 17 },
    { code: 'CO_TU', nameVi: 'Cơ Tu', nameEn: 'Co Tu', shortName: 'CTu', sortOrder: 18 },
    { code: 'GIAY', nameVi: 'Giáy', nameEn: 'Giay', shortName: 'Giáy', sortOrder: 19 },
    { code: 'TA_OI', nameVi: 'Tà Ôi', nameEn: 'Ta Oi', shortName: 'TOI', sortOrder: 20 },
    { code: 'MA', nameVi: 'Mạ', nameEn: 'Ma', shortName: 'Mạ', sortOrder: 21 },
    { code: 'CHO_RO', nameVi: 'Chơ Ro', nameEn: 'Cho Ro', shortName: 'CRo', sortOrder: 22 },
    { code: 'HA_NHI', nameVi: 'Hà Nhì', nameEn: 'Ha Nhi', shortName: 'HNhì', sortOrder: 23 },
    { code: 'CHU_RU', nameVi: 'Chu Ru', nameEn: 'Chu Ru', shortName: 'CRu', sortOrder: 24 },
    { code: 'LAO', nameVi: 'Lào', nameEn: 'Lao', shortName: 'Lào', sortOrder: 25 },
    { code: 'LA_CHI', nameVi: 'La Chí', nameEn: 'La Chi', shortName: 'LChí', sortOrder: 26 },
    { code: 'KHOMU', nameVi: 'Khơ Mú', nameEn: 'Kho Mu', shortName: 'KMú', sortOrder: 27 },
    { code: 'PHU_LA', nameVi: 'Phù Lá', nameEn: 'Phu La', shortName: 'PLá', sortOrder: 28 },
    { code: 'LA_HU', nameVi: 'La Hủ', nameEn: 'La Hu', shortName: 'LHủ', sortOrder: 29 },
    { code: 'MONG', nameVi: 'Mông', nameEn: 'Mong', shortName: 'Mông', sortOrder: 30 },
    { code: 'SAN_DIU', nameVi: 'Sán Dìu', nameEn: 'San Diu', shortName: 'SDìu', sortOrder: 31 },
    { code: 'RAGLAY', nameVi: 'Raglai', nameEn: 'Raglai', shortName: 'Rglai', sortOrder: 32 },
    { code: 'LO_LO', nameVi: 'Lô Lô', nameEn: 'Lo Lo', shortName: 'LLô', sortOrder: 33 },
    { code: 'CHUT', nameVi: 'Chứt', nameEn: 'Chut', shortName: 'Chứt', sortOrder: 34 },
    { code: 'ROMAM', nameVi: 'Rơ Măm', nameEn: 'Ro Mam', shortName: 'RMăm', sortOrder: 35 },
    { code: 'BRAU', nameVi: 'Brâu', nameEn: 'Brau', shortName: 'Brâu', sortOrder: 36 },
    { code: 'ODU', nameVi: 'Ơ Đu', nameEn: 'O Du', shortName: 'ĐDu', sortOrder: 37 },
    { code: 'CO_LAO', nameVi: 'Cờ Lao', nameEn: 'Co Lao', shortName: 'CLao', sortOrder: 38 },
    { code: 'MANG', nameVi: 'Mảng', nameEn: 'Mang', shortName: 'Mảng', sortOrder: 39 },
    { code: 'BOY', nameVi: 'Bố Y', nameEn: 'Bo Y', shortName: 'BY', sortOrder: 40 },
    { code: 'CONG', nameVi: 'Công', nameEn: 'Cong', shortName: 'Công', sortOrder: 41 },
    { code: 'SI_LA', nameVi: 'Si La', nameEn: 'Si La', shortName: 'SLa', sortOrder: 42 },
    { code: 'PHU_PEO', nameVi: 'Phú Pẻo', nameEn: 'Phu Peo', shortName: 'PPẻo', sortOrder: 43 },
    { code: 'KANG', nameVi: 'Kháng', nameEn: 'Khang', shortName: 'Kháng', sortOrder: 44 },
    { code: 'PA_THEN', nameVi: 'Pà Thẻn', nameEn: 'Pa Then', shortName: 'PThẻn', sortOrder: 45 },
    { code: 'LA_HA', nameVi: 'La Ha', nameEn: 'La Ha', shortName: 'LHa', sortOrder: 46 },
    { code: 'PUTEO', nameVi: 'Pu Péo', nameEn: 'Pu Peo', shortName: 'PPéo', sortOrder: 47 },
    { code: 'XINH_MUN', nameVi: 'Xinh Mun', nameEn: 'Xinh Mun', shortName: 'XMun', sortOrder: 48 },
    { code: 'CO', nameVi: 'Co', nameEn: 'Co', shortName: 'Co', sortOrder: 49 },
    { code: 'TA_OI2', nameVi: 'Tà Ôi (nhóm 2)', nameEn: 'Ta Oi (group 2)', shortName: 'TOI2', sortOrder: 50 },
    { code: 'PAKO', nameVi: 'Pa Kô', nameEn: 'Pa Ko', shortName: 'PKô', sortOrder: 51 },
    { code: 'COONG', nameVi: 'Coong', nameEn: 'Coong', shortName: 'Coong', sortOrder: 52 },
    { code: 'LAHA', nameVi: 'Laha', nameEn: 'Laha', shortName: 'Laha', sortOrder: 53 },
    { code: 'XANH', nameVi: 'Xánh', nameEn: 'Xanh', shortName: 'Xánh', sortOrder: 54 },
  ],
  MD_RESEARCH_TYPE: [
    { code: 'NCKH_NHA_NUOC', nameVi: 'Đề tài cấp Nhà nước', nameEn: 'National Level Research', shortName: 'NN', sortOrder: 1, metadata: { source: 'Nafosted' } },
    { code: 'NCKH_BO', nameVi: 'Đề tài cấp Bộ (BQP)', nameEn: 'Ministry Level Research', shortName: 'Bộ', sortOrder: 2, metadata: { source: 'Cục KHQS' } },
    { code: 'NCKH_HOC_VIEN', nameVi: 'Đề tài cấp Học viện', nameEn: 'Academy Level Research', shortName: 'HV', sortOrder: 3, metadata: { source: 'HVHC' } },
    { code: 'NCKH_KHOA', nameVi: 'Đề tài cấp Khoa', nameEn: 'Department Level Research', shortName: 'Khoa', sortOrder: 4 },
    { code: 'SANG_KIEN', nameVi: 'Sáng kiến cải tiến', nameEn: 'Innovation', shortName: 'SK', sortOrder: 5 },
    { code: 'SANG_KIEN_CAP_HV', nameVi: 'Sáng kiến cấp Học viện', nameEn: 'Academy Innovation', shortName: 'SKHV', sortOrder: 6 },
    { code: 'CHUONG_TRINH', nameVi: 'Chương trình NCKH', nameEn: 'Research Program', shortName: 'CT', sortOrder: 7 },
    { code: 'DE_AN', nameVi: 'Đề án khoa học', nameEn: 'Scientific Project', shortName: 'ĐA', sortOrder: 8 },
    { code: 'LUAN_VAN_THS', nameVi: 'Luận văn Thạc sĩ', nameEn: 'Master Thesis', shortName: 'LV-ThS', sortOrder: 9 },
    { code: 'LUAN_AN_TS', nameVi: 'Luận án Tiến sĩ', nameEn: 'Doctoral Dissertation', shortName: 'LA-TS', sortOrder: 10 },
    { code: 'BAO_CAO_KHOA_HOC', nameVi: 'Báo cáo khoa học', nameEn: 'Scientific Report', shortName: 'BCKH', sortOrder: 11 },
    { code: 'GIAO_TRINH', nameVi: 'Giáo trình', nameEn: 'Textbook', shortName: 'GT', sortOrder: 12 },
  ],
  MD_AWARD_TYPE: [
    { code: 'HC_QS_HANG_NHAT', nameVi: 'Huân chương QS hạng nhất', nameEn: 'Military Medal 1st Class', shortName: 'HC-QS1', sortOrder: 1, metadata: { level: 'Nhà nước' } },
    { code: 'HC_QS_HANG_NHI', nameVi: 'Huân chương QS hạng nhì', nameEn: 'Military Medal 2nd Class', shortName: 'HC-QS2', sortOrder: 2, metadata: { level: 'Nhà nước' } },
    { code: 'HC_QS_HANG_BA', nameVi: 'Huân chương QS hạng ba', nameEn: 'Military Medal 3rd Class', shortName: 'HC-QS3', sortOrder: 3, metadata: { level: 'Nhà nước' } },
    { code: 'HC_CHIEN_CONG_1', nameVi: 'Huân chương Chiến công hạng nhất', nameEn: 'Combat Medal 1st', shortName: 'HC-CC1', sortOrder: 4, metadata: { level: 'Nhà nước' } },
    { code: 'HC_CHIEN_CONG_2', nameVi: 'Huân chương Chiến công hạng nhì', nameEn: 'Combat Medal 2nd', shortName: 'HC-CC2', sortOrder: 5, metadata: { level: 'Nhà nước' } },
    { code: 'HC_CHIEN_CONG_3', nameVi: 'Huân chương Chiến công hạng ba', nameEn: 'Combat Medal 3rd', shortName: 'HC-CC3', sortOrder: 6, metadata: { level: 'Nhà nước' } },
    { code: 'HUY_CHUONG_QUAN_KY', nameVi: 'Huy chương Quân kỳ Quyết thắng', nameEn: 'Military Service Medal', shortName: 'HCQ', sortOrder: 7, metadata: { level: 'Nhà nước' } },
    { code: 'BANG_KHEN_BQP', nameVi: 'Bằng khen Bộ trưởng BQP', nameEn: 'Minister of Defence Award', shortName: 'BK-BQP', sortOrder: 8, metadata: { level: 'BQP' } },
    { code: 'BANG_KHEN_TGTC', nameVi: 'Bằng khen Tổng Giám đốc', nameEn: 'Director Award', shortName: 'BK-TGĐ', sortOrder: 9, metadata: { level: 'BQP' } },
    { code: 'BANG_KHEN_HV', nameVi: 'Bằng khen Học viện', nameEn: 'Academy Commendation', shortName: 'BK-HV', sortOrder: 10, metadata: { level: 'HVHC' } },
    { code: 'GIAY_KHEN', nameVi: 'Giấy khen', nameEn: 'Certificate of Merit', shortName: 'GK', sortOrder: 11, metadata: { level: 'Đơn vị' } },
    { code: 'CSTT', nameVi: 'Chiến sĩ tiên tiến', nameEn: 'Outstanding Soldier', shortName: 'CSTT', sortOrder: 12, metadata: { level: 'Đơn vị' } },
    { code: 'CSTT_TOAN_QUAN', nameVi: 'Chiến sĩ tiên tiến toàn quân', nameEn: 'Outstanding Soldier Army', shortName: 'CSTT-TQ', sortOrder: 13, metadata: { level: 'BQP' } },
    { code: 'DANHIEUTC', nameVi: 'Danh hiệu Đơn vị tiên tiến', nameEn: 'Merit Unit', shortName: 'ĐVTT', sortOrder: 14, metadata: { level: 'HV' } },
    { code: 'HC_LAO_DONG_1', nameVi: 'Huân chương Lao động hạng nhất', nameEn: 'Labour Medal 1st', shortName: 'HC-LĐ1', sortOrder: 15, metadata: { level: 'Nhà nước' } },
    { code: 'HC_LAO_DONG_2', nameVi: 'Huân chương Lao động hạng nhì', nameEn: 'Labour Medal 2nd', shortName: 'HC-LĐ2', sortOrder: 16, metadata: { level: 'Nhà nước' } },
    { code: 'HC_LAO_DONG_3', nameVi: 'Huân chương Lao động hạng ba', nameEn: 'Labour Medal 3rd', shortName: 'HC-LĐ3', sortOrder: 17, metadata: { level: 'Nhà nước' } },
    { code: 'HC_DOC_LAP_1', nameVi: 'Huân chương Độc Lập hạng nhất', nameEn: 'Independence Medal 1st', shortName: 'HC-ĐL1', sortOrder: 18, metadata: { level: 'Nhà nước' } },
    { code: 'HC_DOC_LAP_2', nameVi: 'Huân chương Độc Lập hạng nhì', nameEn: 'Independence Medal 2nd', shortName: 'HC-ĐL2', sortOrder: 19, metadata: { level: 'Nhà nước' } },
    { code: 'HC_DOC_LAP_3', nameVi: 'Huân chương Độc Lập hạng ba', nameEn: 'Independence Medal 3rd', shortName: 'HC-ĐL3', sortOrder: 20, metadata: { level: 'Nhà nước' } },
  ],
  MD_WORKFLOW_STATUS: [
    { code: 'DRAFT', nameVi: 'Bản nháp', nameEn: 'Draft', shortName: 'Nháp', sortOrder: 1, metadata: { color: 'gray' } },
    { code: 'SUBMITTED', nameVi: 'Đã nộp', nameEn: 'Submitted', shortName: 'Đã nộp', sortOrder: 2, metadata: { color: 'blue' } },
    { code: 'IN_REVIEW', nameVi: 'Đang xem xét', nameEn: 'Under Review', shortName: 'Xem xét', sortOrder: 3, metadata: { color: 'orange' } },
    { code: 'PENDING_APPROVAL', nameVi: 'Chờ phê duyệt', nameEn: 'Pending Approval', shortName: 'Chờ duyệt', sortOrder: 4, metadata: { color: 'yellow' } },
    { code: 'APPROVED', nameVi: 'Đã phê duyệt', nameEn: 'Approved', shortName: 'Đã duyệt', sortOrder: 5, metadata: { color: 'green' } },
    { code: 'REJECTED', nameVi: 'Từ chối', nameEn: 'Rejected', shortName: 'Từ chối', sortOrder: 6, metadata: { color: 'red' } },
    { code: 'RETURNED', nameVi: 'Trả lại chỉnh sửa', nameEn: 'Returned for Revision', shortName: 'Trả lại', sortOrder: 7, metadata: { color: 'purple' } },
    { code: 'CANCELLED', nameVi: 'Hủy bỏ', nameEn: 'Cancelled', shortName: 'Hủy', sortOrder: 8, metadata: { color: 'gray' } },
    { code: 'COMPLETED', nameVi: 'Hoàn thành', nameEn: 'Completed', shortName: 'Hoàn thành', sortOrder: 9, metadata: { color: 'green' } },
    { code: 'EXPIRED', nameVi: 'Hết hạn', nameEn: 'Expired', shortName: 'Hết hạn', sortOrder: 10, metadata: { color: 'red' } },
  ],
  MD_RELIGION: [
    { code: 'KHONG', nameVi: 'Không', nameEn: 'None', shortName: 'KT', sortOrder: 1 },
    { code: 'PHAT_GIAO', nameVi: 'Phật giáo', nameEn: 'Buddhism', shortName: 'PG', sortOrder: 2 },
    { code: 'CONG_GIAO', nameVi: 'Công giáo', nameEn: 'Catholicism', shortName: 'CG', sortOrder: 3 },
    { code: 'CAO_DAI', nameVi: 'Cao Đài', nameEn: 'Cao Dai', shortName: 'CD', sortOrder: 4 },
    { code: 'HOA_HAO', nameVi: 'Hòa Hảo', nameEn: 'Hoa Hao', shortName: 'HH', sortOrder: 5 },
    { code: 'TIN_LANH', nameVi: 'Tin Lành', nameEn: 'Protestantism', shortName: 'TL', sortOrder: 6 },
    { code: 'HOI_GIAO', nameVi: 'Hồi giáo', nameEn: 'Islam', shortName: 'HG', sortOrder: 7 },
  ],
  MD_PROVINCE: [
    { code: 'HN', nameVi: 'Hà Nội', nameEn: 'Hanoi', shortName: 'HN', externalCode: '01', sortOrder: 1 },
    { code: 'HCM', nameVi: 'Hồ Chí Minh', nameEn: 'Ho Chi Minh City', shortName: 'HCM', externalCode: '79', sortOrder: 2 },
    { code: 'DN', nameVi: 'Đà Nẵng', nameEn: 'Da Nang', shortName: 'ĐN', externalCode: '48', sortOrder: 3 },
    { code: 'HP', nameVi: 'Hải Phòng', nameEn: 'Hai Phong', shortName: 'HP', externalCode: '31', sortOrder: 4 },
    { code: 'CT', nameVi: 'Cần Thơ', nameEn: 'Can Tho', shortName: 'CT', externalCode: '92', sortOrder: 5 },
    { code: 'BD', nameVi: 'Bình Dương', nameEn: 'Binh Duong', shortName: 'BĐ', externalCode: '74', sortOrder: 6 },
    { code: 'NA', nameVi: 'Nghệ An', nameEn: 'Nghe An', shortName: 'NA', externalCode: '40', sortOrder: 7 },
    { code: 'TH', nameVi: 'Thanh Hóa', nameEn: 'Thanh Hoa', shortName: 'TH', externalCode: '38', sortOrder: 8 },
    { code: 'TN', nameVi: 'Thái Nguyên', nameEn: 'Thai Nguyen', shortName: 'TN', externalCode: '19', sortOrder: 9 },
    { code: 'BP', nameVi: 'Bình Phước', nameEn: 'Binh Phuoc', shortName: 'BP', externalCode: '70', sortOrder: 10 },
    { code: 'HB', nameVi: 'Hòa Bình', nameEn: 'Hoa Binh', shortName: 'HB', externalCode: '17', sortOrder: 11 },
    { code: 'PY', nameVi: 'Phú Yên', nameEn: 'Phu Yen', shortName: 'PY', externalCode: '54', sortOrder: 12 },
    { code: 'GL', nameVi: 'Gia Lai', nameEn: 'Gia Lai', shortName: 'GL', externalCode: '64', sortOrder: 13 },
    { code: 'KH', nameVi: 'Khánh Hòa', nameEn: 'Khanh Hoa', shortName: 'KH', externalCode: '56', sortOrder: 14 },
    { code: 'LD', nameVi: 'Lâm Đồng', nameEn: 'Lam Dong', shortName: 'LĐ', externalCode: '68', sortOrder: 15 },
  ],
  MD_POLITICAL_LEVEL: [
    { code: 'SO_CAP', nameVi: 'Sơ cấp', nameEn: 'Elementary', shortName: 'SC', sortOrder: 1 },
    { code: 'TRUNG_CAP', nameVi: 'Trung cấp', nameEn: 'Intermediate', shortName: 'TC', sortOrder: 2 },
    { code: 'CAO_CAP', nameVi: 'Cao cấp', nameEn: 'Advanced', shortName: 'CC', sortOrder: 3 },
    { code: 'CU_NHAN_CTCT', nameVi: 'Cử nhân CTCT', nameEn: 'Bachelor of Political Theory', shortName: 'CN-CTCT', sortOrder: 4 },
    { code: 'THAC_SI_CTCT', nameVi: 'Thạc sĩ CTCT', nameEn: 'Master of Political Theory', shortName: 'ThS-CTCT', sortOrder: 5 },
    { code: 'TIEN_SI_CTCT', nameVi: 'Tiến sĩ CTCT', nameEn: 'Doctor of Political Theory', shortName: 'TS-CTCT', sortOrder: 6 },
  ],
  MD_PARTY_CATEGORY: [
    { code: 'CHINH_THUC', nameVi: 'Đảng viên chính thức', nameEn: 'Full Party Member', shortName: 'ĐV-CT', sortOrder: 1 },
    { code: 'DU_BI', nameVi: 'Đảng viên dự bị', nameEn: 'Probationary Member', shortName: 'ĐV-DB', sortOrder: 2 },
    { code: 'CAM_TINH', nameVi: 'Đảng cảm tình', nameEn: 'Party Sympathizer', shortName: 'ĐCT', sortOrder: 3 },
    { code: 'DOI_TUONG', nameVi: 'Đang là đối tượng', nameEn: 'Under Consideration', shortName: 'ĐT', sortOrder: 4 },
    { code: 'HET_HAN', nameVi: 'Hết hạn', nameEn: 'Lapsed', shortName: 'HH', sortOrder: 5 },
  ],
  MD_PARTY_EVAL_TYPE: [
    { code: 'HTXSNV', nameVi: 'Hoàn thành xuất sắc nhiệm vụ', nameEn: 'Excellent Task Completion', shortName: 'HTXSNV', sortOrder: 1 },
    { code: 'HTTNV', nameVi: 'Hoàn thành tốt nhiệm vụ', nameEn: 'Good Task Completion', shortName: 'HTTNV', sortOrder: 2 },
    { code: 'HTNV', nameVi: 'Hoàn thành nhiệm vụ', nameEn: 'Task Completion', shortName: 'HTNV', sortOrder: 3 },
    { code: 'KHONG_HTNV', nameVi: 'Không hoàn thành nhiệm vụ', nameEn: 'Incomplete Tasks', shortName: 'KHTNV', sortOrder: 4 },
  ],
  MD_ACADEMIC_DEGREE: [
    { code: 'CU_NHAN', nameVi: 'Cử nhân', nameEn: 'Bachelor', shortName: 'CN', sortOrder: 1 },
    { code: 'KY_SU', nameVi: 'Kỹ sư', nameEn: 'Engineer', shortName: 'KS', sortOrder: 2 },
    { code: 'THAC_SI', nameVi: 'Thạc sĩ', nameEn: 'Master', shortName: 'ThS', sortOrder: 3 },
    { code: 'TIEN_SI', nameVi: 'Tiến sĩ', nameEn: 'Doctor', shortName: 'TS', sortOrder: 4 },
    { code: 'TIEN_SI_KHOA_HOC', nameVi: 'Tiến sĩ Khoa học', nameEn: 'Doctor of Science', shortName: 'TSKH', sortOrder: 5 },
    { code: 'BAC_SI', nameVi: 'Bác sĩ', nameEn: 'Medical Doctor', shortName: 'BS', sortOrder: 6 },
    { code: 'DUOC_SI', nameVi: 'Dược sĩ', nameEn: 'Pharmacist', shortName: 'DS', sortOrder: 7 },
    { code: 'LUAT_SU', nameVi: 'Luật sư', nameEn: 'Lawyer', shortName: 'LS', sortOrder: 8 },
  ],
  MD_ACADEMIC_TITLE: [
    { code: 'GIANG_VIEN', nameVi: 'Giảng viên', nameEn: 'Lecturer', shortName: 'GV', sortOrder: 1 },
    { code: 'GIANG_VIEN_CHINH', nameVi: 'Giảng viên chính', nameEn: 'Senior Lecturer', shortName: 'GVC', sortOrder: 2 },
    { code: 'GIANG_VIEN_CAO_CAP', nameVi: 'Giảng viên cao cấp', nameEn: 'Principal Lecturer', shortName: 'GVCC', sortOrder: 3 },
    { code: 'PHO_GIAO_SU', nameVi: 'Phó Giáo sư', nameEn: 'Associate Professor', shortName: 'PGS', sortOrder: 4 },
    { code: 'GIAO_SU', nameVi: 'Giáo sư', nameEn: 'Professor', shortName: 'GS', sortOrder: 5 },
  ],
  MD_STUDY_MODE: [
    { code: 'CHINH_QUY', nameVi: 'Chính quy', nameEn: 'Regular', shortName: 'CQ', sortOrder: 1 },
    { code: 'TAI_CHUC', nameVi: 'Tại chức', nameEn: 'Part-time', shortName: 'TC', sortOrder: 2 },
    { code: 'TU_XA', nameVi: 'Từ xa', nameEn: 'Distance Learning', shortName: 'TX', sortOrder: 3 },
    { code: 'VAN_BANG_2', nameVi: 'Văn bằng 2', nameEn: 'Second Degree', shortName: 'VB2', sortOrder: 4 },
    { code: 'LIEN_THONG', nameVi: 'Liên thông', nameEn: 'Transfer', shortName: 'LT', sortOrder: 5 },
    { code: 'NGHIEN_CUU_SINH', nameVi: 'Nghiên cứu sinh', nameEn: 'PhD Student', shortName: 'NCS', sortOrder: 6 },
    { code: 'THUC_TAP_SINH', nameVi: 'Thực tập sinh', nameEn: 'Intern', shortName: 'TTS', sortOrder: 7 },
    { code: 'BOI_DUONG', nameVi: 'Bồi dưỡng', nameEn: 'Short Course', shortName: 'BD', sortOrder: 8 },
  ],
  MD_LANGUAGE: [
    { code: 'EN', nameVi: 'Tiếng Anh', nameEn: 'English', shortName: 'Anh', externalCode: 'en', sortOrder: 1 },
    { code: 'RU', nameVi: 'Tiếng Nga', nameEn: 'Russian', shortName: 'Nga', externalCode: 'ru', sortOrder: 2 },
    { code: 'ZH', nameVi: 'Tiếng Trung', nameEn: 'Chinese', shortName: 'Trung', externalCode: 'zh', sortOrder: 3 },
    { code: 'FR', nameVi: 'Tiếng Pháp', nameEn: 'French', shortName: 'Pháp', externalCode: 'fr', sortOrder: 4 },
    { code: 'DE', nameVi: 'Tiếng Đức', nameEn: 'German', shortName: 'Đức', externalCode: 'de', sortOrder: 5 },
    { code: 'JA', nameVi: 'Tiếng Nhật', nameEn: 'Japanese', shortName: 'Nhật', externalCode: 'ja', sortOrder: 6 },
    { code: 'KO', nameVi: 'Tiếng Hàn', nameEn: 'Korean', shortName: 'Hàn', externalCode: 'ko', sortOrder: 7 },
  ],
  MD_LANGUAGE_LEVEL: [
    { code: 'A1', nameVi: 'A1 – Sơ cấp', nameEn: 'A1 – Beginner', shortName: 'A1', sortOrder: 1 },
    { code: 'A2', nameVi: 'A2 – Cơ bản', nameEn: 'A2 – Elementary', shortName: 'A2', sortOrder: 2 },
    { code: 'B1', nameVi: 'B1 – Trung cấp', nameEn: 'B1 – Intermediate', shortName: 'B1', sortOrder: 3 },
    { code: 'B2', nameVi: 'B2 – Khá', nameEn: 'B2 – Upper Intermediate', shortName: 'B2', sortOrder: 4 },
    { code: 'C1', nameVi: 'C1 – Nâng cao', nameEn: 'C1 – Advanced', shortName: 'C1', sortOrder: 5 },
    { code: 'C2', nameVi: 'C2 – Thành thạo', nameEn: 'C2 – Proficient', shortName: 'C2', sortOrder: 6 },
    { code: 'CU_NHAN_NN', nameVi: 'Cử nhân ngoại ngữ', nameEn: 'Language Bachelor', shortName: 'CN-NN', sortOrder: 7 },
    { code: 'CHUYEN_NGANH', nameVi: 'Chứng chỉ chuyên ngành', nameEn: 'Specialized Certificate', shortName: 'CC', sortOrder: 8 },
  ],
  MD_IT_LEVEL: [
    { code: 'CAN_BAN', nameVi: 'Căn bản', nameEn: 'Basic', shortName: 'CB', sortOrder: 1 },
    { code: 'NANG_CAO', nameVi: 'Nâng cao', nameEn: 'Advanced', shortName: 'NC', sortOrder: 2 },
    { code: 'CHUNG_CHI_NGHE', nameVi: 'Chứng chỉ nghề', nameEn: 'Vocational Certificate', shortName: 'CCN', sortOrder: 3 },
    { code: 'DAI_HOC_CNTT', nameVi: 'Đại học CNTT', nameEn: 'IT University', shortName: 'ĐH-CNTT', sortOrder: 4 },
    { code: 'THAC_SI_CNTT', nameVi: 'Thạc sĩ CNTT', nameEn: 'IT Master', shortName: 'ThS-CNTT', sortOrder: 5 },
    { code: 'TIEN_SI_CNTT', nameVi: 'Tiến sĩ CNTT', nameEn: 'IT Doctor', shortName: 'TS-CNTT', sortOrder: 6 },
  ],
  MD_AWARD_LEVEL: [
    { code: 'NHA_NUOC', nameVi: 'Nhà nước', nameEn: 'State Level', shortName: 'NN', sortOrder: 1 },
    { code: 'CHINH_PHU', nameVi: 'Chính phủ', nameEn: 'Government Level', shortName: 'CP', sortOrder: 2 },
    { code: 'BO_NGANH', nameVi: 'Bộ/Ban ngành', nameEn: 'Ministry/Department Level', shortName: 'Bộ', sortOrder: 3 },
    { code: 'QUAN_KHU', nameVi: 'Quân khu', nameEn: 'Military Region Level', shortName: 'QK', sortOrder: 4 },
    { code: 'HOC_VIEN', nameVi: 'Học viện', nameEn: 'Academy Level', shortName: 'HV', sortOrder: 5 },
    { code: 'KHOA_PHONG', nameVi: 'Khoa/Phòng', nameEn: 'Department Level', shortName: 'KP', sortOrder: 6 },
    { code: 'DON_VI', nameVi: 'Đơn vị', nameEn: 'Unit Level', shortName: 'ĐV', sortOrder: 7 },
    { code: 'CA_NHAN', nameVi: 'Cá nhân', nameEn: 'Individual', shortName: 'CN', sortOrder: 8 },
  ],
  MD_DISCIPLINE_TYPE: [
    { code: 'KHIEN_TRACH', nameVi: 'Khiển trách', nameEn: 'Warning', shortName: 'KT', sortOrder: 1 },
    { code: 'CANH_CAO', nameVi: 'Cảnh cáo', nameEn: 'Reprimand', shortName: 'CC', sortOrder: 2 },
    { code: 'HA_BAC_LUONG', nameVi: 'Hạ bậc lương', nameEn: 'Salary Reduction', shortName: 'HBL', sortOrder: 3 },
    { code: 'HA_CAP_BAC_QH', nameVi: 'Hạ cấp bậc quân hàm', nameEn: 'Rank Demotion', shortName: 'HCBQH', sortOrder: 4 },
    { code: 'TUOC_DANH_HIEU', nameVi: 'Tước danh hiệu quân nhân', nameEn: 'Revoke Military Title', shortName: 'TDHQN', sortOrder: 5 },
    { code: 'GIANG_CHUC', nameVi: 'Giáng chức', nameEn: 'Demotion', shortName: 'GC', sortOrder: 6 },
    { code: 'CACH_CHUC', nameVi: 'Cách chức', nameEn: 'Dismissal from Position', shortName: 'CChức', sortOrder: 7 },
    { code: 'KHAI_TRU', nameVi: 'Khai trừ', nameEn: 'Expulsion', shortName: 'KTrừ', sortOrder: 8 },
  ],
  MD_TRAINING_SYSTEM: [
    { code: 'DH_CHINH_QUY', nameVi: 'Đại học chính quy', nameEn: 'Regular University', shortName: 'ĐH-CQ', sortOrder: 1 },
    { code: 'SDH_THAC_SI', nameVi: 'Sau ĐH Thạc sĩ', nameEn: 'Master Program', shortName: 'SĐH-ThS', sortOrder: 2 },
    { code: 'SDH_TIEN_SI', nameVi: 'Sau ĐH Tiến sĩ', nameEn: 'Doctoral Program', shortName: 'SĐH-TS', sortOrder: 3 },
    { code: 'BOI_DUONG_NGAN_HAN', nameVi: 'Bồi dưỡng ngắn hạn', nameEn: 'Short-term Training', shortName: 'BDNH', sortOrder: 4 },
    { code: 'LIEN_KET_DT', nameVi: 'Liên kết đào tạo', nameEn: 'Collaborative Training', shortName: 'LKĐT', sortOrder: 5 },
    { code: 'CHUYEN_NGANH_QS', nameVi: 'Chuyên ngành quân sự', nameEn: 'Military Specialization', shortName: 'CNQS', sortOrder: 6 },
    { code: 'BOI_DUONG_CT', nameVi: 'Bồi dưỡng chính trị', nameEn: 'Political Training', shortName: 'BDCT', sortOrder: 7 },
    { code: 'DH_TAI_CHUC', nameVi: 'Đại học tại chức', nameEn: 'Part-time University', shortName: 'ĐH-TC', sortOrder: 8 },
    { code: 'CAO_DANG', nameVi: 'Cao đẳng', nameEn: 'College', shortName: 'CĐ', sortOrder: 9 },
    { code: 'TRUNG_CAP', nameVi: 'Trung cấp', nameEn: 'Secondary Vocational', shortName: 'TC', sortOrder: 10 },
  ],
  MD_ACADEMIC_RESULT: [
    { code: 'XUAT_SAC', nameVi: 'Xuất sắc', nameEn: 'Excellent', shortName: 'XS', sortOrder: 1, metadata: { minScore: 9.0 } },
    { code: 'GIOI', nameVi: 'Giỏi', nameEn: 'Good', shortName: 'G', sortOrder: 2, metadata: { minScore: 8.0 } },
    { code: 'KHA', nameVi: 'Khá', nameEn: 'Fair', shortName: 'K', sortOrder: 3, metadata: { minScore: 7.0 } },
    { code: 'TRUNG_BINH_KHA', nameVi: 'Trung bình khá', nameEn: 'Average-Good', shortName: 'TBK', sortOrder: 4, metadata: { minScore: 6.0 } },
    { code: 'TRUNG_BINH', nameVi: 'Trung bình', nameEn: 'Average', shortName: 'TB', sortOrder: 5, metadata: { minScore: 5.0 } },
    { code: 'YEU', nameVi: 'Yếu', nameEn: 'Poor', shortName: 'Y', sortOrder: 6, metadata: { minScore: 0 } },
  ],
  MD_CONDUCT_RESULT: [
    { code: 'XUAT_SAC', nameVi: 'Xuất sắc', nameEn: 'Excellent', shortName: 'XS', sortOrder: 1 },
    { code: 'TOT', nameVi: 'Tốt', nameEn: 'Good', shortName: 'T', sortOrder: 2 },
    { code: 'KHA', nameVi: 'Khá', nameEn: 'Fair', shortName: 'K', sortOrder: 3 },
    { code: 'TRUNG_BINH', nameVi: 'Trung bình', nameEn: 'Average', shortName: 'TB', sortOrder: 4 },
    { code: 'YEU', nameVi: 'Yếu', nameEn: 'Poor', shortName: 'Y', sortOrder: 5 },
  ],
  MD_INSURANCE_TYPE: [
    { code: 'BHXH_BB', nameVi: 'BHXH bắt buộc', nameEn: 'Mandatory Social Insurance', shortName: 'BHXH', sortOrder: 1 },
    { code: 'BHYT', nameVi: 'Bảo hiểm y tế', nameEn: 'Health Insurance', shortName: 'BHYT', sortOrder: 2 },
    { code: 'BHTN', nameVi: 'Bảo hiểm thất nghiệp', nameEn: 'Unemployment Insurance', shortName: 'BHTN', sortOrder: 3 },
    { code: 'BH_TNQS', nameVi: 'BH tai nạn quân sự', nameEn: 'Military Accident Insurance', shortName: 'BH-TN', sortOrder: 4 },
    { code: 'BH_THUONG_BINH', nameVi: 'BH thương binh', nameEn: 'War Veteran Insurance', shortName: 'BH-TB', sortOrder: 5 },
    { code: 'BH_TU_TUAT', nameVi: 'BH tử tuất', nameEn: 'Death Insurance', shortName: 'BH-TT', sortOrder: 6 },
  ],
  MD_LEAVE_TYPE: [
    { code: 'NGHI_PHEP_NAM', nameVi: 'Nghỉ phép năm', nameEn: 'Annual Leave', shortName: 'NPN', sortOrder: 1 },
    { code: 'NGHI_OM', nameVi: 'Nghỉ ốm', nameEn: 'Sick Leave', shortName: 'NÔm', sortOrder: 2 },
    { code: 'NGHI_THAI_SAN', nameVi: 'Nghỉ thai sản', nameEn: 'Maternity Leave', shortName: 'NTS', sortOrder: 3 },
    { code: 'NGHI_KHONG_LUONG', nameVi: 'Nghỉ không lương', nameEn: 'Unpaid Leave', shortName: 'NKL', sortOrder: 4 },
    { code: 'NGHI_HUU', nameVi: 'Nghỉ hưu', nameEn: 'Retirement', shortName: 'NH', sortOrder: 5 },
    { code: 'NGHI_DUONG_SUC', nameVi: 'Nghỉ dưỡng sức', nameEn: 'Recovery Leave', shortName: 'NDS', sortOrder: 6 },
    { code: 'NGHI_CONG_TAC', nameVi: 'Nghỉ công tác', nameEn: 'Business Leave', shortName: 'NCT', sortOrder: 7 },
    { code: 'NGHI_HIEU', nameVi: 'Nghỉ hiếu', nameEn: 'Bereavement Leave', shortName: 'NHiếu', sortOrder: 8 },
    { code: 'NGHI_LE_TET', nameVi: 'Nghỉ lễ/Tết', nameEn: 'Holiday Leave', shortName: 'NLT', sortOrder: 9 },
    { code: 'NGHI_DI_HOC', nameVi: 'Nghỉ đi học', nameEn: 'Study Leave', shortName: 'NDH', sortOrder: 10 },
  ],
  MD_PUBLICATION_TYPE: [
    { code: 'TAPCHI_QT_Q1', nameVi: 'Tạp chí quốc tế Q1', nameEn: 'International Journal Q1', shortName: 'Q1', sortOrder: 1 },
    { code: 'TAPCHI_QT_Q2', nameVi: 'Tạp chí quốc tế Q2', nameEn: 'International Journal Q2', shortName: 'Q2', sortOrder: 2 },
    { code: 'TAPCHI_QT_Q3', nameVi: 'Tạp chí quốc tế Q3', nameEn: 'International Journal Q3', shortName: 'Q3', sortOrder: 3 },
    { code: 'TAPCHI_QT_Q4', nameVi: 'Tạp chí quốc tế Q4', nameEn: 'International Journal Q4', shortName: 'Q4', sortOrder: 4 },
    { code: 'TAPCHI_TRONG_NUOC', nameVi: 'Tạp chí trong nước', nameEn: 'Domestic Journal', shortName: 'TN', sortOrder: 5 },
    { code: 'HOI_THAO_QT', nameVi: 'Hội thảo quốc tế', nameEn: 'International Conference', shortName: 'HTQT', sortOrder: 6 },
    { code: 'KY_YEU', nameVi: 'Kỷ yếu', nameEn: 'Proceedings', shortName: 'KY', sortOrder: 7 },
    { code: 'SACH', nameVi: 'Sách', nameEn: 'Book', shortName: 'Sách', sortOrder: 8 },
    { code: 'GIAO_TRINH', nameVi: 'Giáo trình', nameEn: 'Textbook', shortName: 'GT', sortOrder: 9 },
    { code: 'BAO_CAO_KH', nameVi: 'Báo cáo khoa học', nameEn: 'Scientific Report', shortName: 'BCKH', sortOrder: 10 },
  ],
  MD_INNOVATION_LEVEL: [
    { code: 'CAP_KHOA', nameVi: 'Cấp Khoa', nameEn: 'Department Level', shortName: 'Khoa', sortOrder: 1 },
    { code: 'CAP_HOC_VIEN', nameVi: 'Cấp Học viện', nameEn: 'Academy Level', shortName: 'HV', sortOrder: 2 },
    { code: 'CAP_BO', nameVi: 'Cấp Bộ', nameEn: 'Ministry Level', shortName: 'Bộ', sortOrder: 3 },
    { code: 'CAP_NHA_NUOC', nameVi: 'Cấp Nhà nước', nameEn: 'National Level', shortName: 'NN', sortOrder: 4 },
    { code: 'BANG_SANG_CHE_QT', nameVi: 'Bằng sáng chế quốc tế', nameEn: 'International Patent', shortName: 'BSC-QT', sortOrder: 5 },
  ],
  MD_EQUIPMENT_STATUS: [
    { code: 'TOT', nameVi: 'Tốt', nameEn: 'Good', shortName: 'T', sortOrder: 1 },
    { code: 'TRUNG_BINH', nameVi: 'Trung bình', nameEn: 'Average', shortName: 'TB', sortOrder: 2 },
    { code: 'KEM', nameVi: 'Kém', nameEn: 'Poor', shortName: 'K', sortOrder: 3 },
    { code: 'CAN_SUA_CHUA', nameVi: 'Cần sửa chữa', nameEn: 'Needs Repair', shortName: 'CSC', sortOrder: 4 },
    { code: 'DANG_SUA', nameVi: 'Đang sửa', nameEn: 'Under Repair', shortName: 'DS', sortOrder: 5 },
    { code: 'CHO_THANH_LY', nameVi: 'Chờ thanh lý', nameEn: 'Pending Disposal', shortName: 'CTL', sortOrder: 6 },
    { code: 'DA_THANH_LY', nameVi: 'Đã thanh lý', nameEn: 'Disposed', shortName: 'ĐTL', sortOrder: 7 },
    { code: 'MAT', nameVi: 'Mất', nameEn: 'Lost', shortName: 'Mất', sortOrder: 8 },
  ],
  MD_PERSONNEL_TYPE: [
    { code: 'SI_QUAN', nameVi: 'Sĩ quan', nameEn: 'Officer', shortName: 'SQ', sortOrder: 1 },
    { code: 'QNCN', nameVi: 'Quân nhân chuyên nghiệp', nameEn: 'Professional Soldier', shortName: 'QNCN', sortOrder: 2 },
    { code: 'HA_SI_QUAN', nameVi: 'Hạ sĩ quan', nameEn: 'Non-commissioned Officer', shortName: 'HSQ', sortOrder: 3 },
    { code: 'BINH_SI', nameVi: 'Binh sĩ', nameEn: 'Soldier', shortName: 'BS', sortOrder: 4 },
    { code: 'CONG_CHUC_QP', nameVi: 'Công chức quốc phòng', nameEn: 'Defence Civil Servant', shortName: 'CC-QP', sortOrder: 5 },
    { code: 'VIEN_CHUC_QP', nameVi: 'Viên chức quốc phòng', nameEn: 'Defence Official', shortName: 'VC-QP', sortOrder: 6 },
    { code: 'LAO_DONG_HD', nameVi: 'Lao động hợp đồng', nameEn: 'Contract Worker', shortName: 'LĐHĐ', sortOrder: 7 },
    { code: 'HOC_VIEN', nameVi: 'Học viên', nameEn: 'Student', shortName: 'HV', sortOrder: 8 },
  ],
  MD_UNIT_TYPE: [
    { code: 'HOC_VIEN', nameVi: 'Học viện', nameEn: 'Academy', shortName: 'HV', sortOrder: 1 },
    { code: 'KHOA', nameVi: 'Khoa', nameEn: 'Faculty', shortName: 'Khoa', sortOrder: 2 },
    { code: 'PHONG', nameVi: 'Phòng', nameEn: 'Department', shortName: 'Phòng', sortOrder: 3 },
    { code: 'BAN', nameVi: 'Ban', nameEn: 'Division', shortName: 'Ban', sortOrder: 4 },
    { code: 'BO_MON', nameVi: 'Bộ môn', nameEn: 'Subject Department', shortName: 'BM', sortOrder: 5 },
    { code: 'TRUNG_TAM', nameVi: 'Trung tâm', nameEn: 'Center', shortName: 'TT', sortOrder: 6 },
    { code: 'TIEU_DOAN', nameVi: 'Tiểu đoàn', nameEn: 'Battalion', shortName: 'TĐ', sortOrder: 7 },
    { code: 'DAI_DOI', nameVi: 'Đại đội', nameEn: 'Company', shortName: 'ĐĐ', sortOrder: 8 },
    { code: 'TRUNG_DOI', nameVi: 'Trung đội', nameEn: 'Platoon', shortName: 'TrĐ', sortOrder: 9 },
    { code: 'TIEU_DOI', nameVi: 'Tiểu đội', nameEn: 'Squad', shortName: 'TiĐ', sortOrder: 10 },
    { code: 'LOP', nameVi: 'Lớp', nameEn: 'Class', shortName: 'Lớp', sortOrder: 11 },
    { code: 'TO', nameVi: 'Tổ', nameEn: 'Group', shortName: 'Tổ', sortOrder: 12 },
  ],
  MD_SCOPE_LEVEL: [
    { code: 'SELF', nameVi: 'Bản thân', nameEn: 'Self', shortName: 'Self', sortOrder: 1 },
    { code: 'UNIT', nameVi: 'Đơn vị', nameEn: 'Unit', shortName: 'Unit', sortOrder: 2 },
    { code: 'DEPARTMENT', nameVi: 'Khoa/Phòng', nameEn: 'Department', shortName: 'Dept', sortOrder: 3 },
    { code: 'ACADEMY', nameVi: 'Toàn Học viện', nameEn: 'Academy', shortName: 'Acad', sortOrder: 4 },
  ],
  MD_NOTIFICATION_TYPE: [
    { code: 'CANH_BAO_HT', nameVi: 'Cảnh báo hệ thống', nameEn: 'System Alert', shortName: 'CB-HT', sortOrder: 1 },
    { code: 'NHAC_VIEC', nameVi: 'Nhắc việc', nameEn: 'Reminder', shortName: 'NV', sortOrder: 2 },
    { code: 'PHE_DUYET', nameVi: 'Phê duyệt', nameEn: 'Approval', shortName: 'PD', sortOrder: 3 },
    { code: 'HET_HAN', nameVi: 'Hết hạn', nameEn: 'Expired', shortName: 'HH', sortOrder: 4 },
    { code: 'THONG_TIN', nameVi: 'Thông tin', nameEn: 'Information', shortName: 'TT', sortOrder: 5 },
    { code: 'CAP_NHAT_CS', nameVi: 'Cập nhật chính sách', nameEn: 'Policy Update', shortName: 'CNCS', sortOrder: 6 },
    { code: 'DAO_TAO', nameVi: 'Đào tạo', nameEn: 'Training', shortName: 'ĐT', sortOrder: 7 },
    { code: 'AN_NINH', nameVi: 'An ninh bảo mật', nameEn: 'Security', shortName: 'AN', sortOrder: 8 },
    { code: 'NCKH', nameVi: 'Nghiên cứu khoa học', nameEn: 'Research', shortName: 'NCKH', sortOrder: 9 },
    { code: 'CAP_BAC', nameVi: 'Thăng cấp bậc', nameEn: 'Promotion', shortName: 'CB', sortOrder: 10 },
    { code: 'BAO_CAO', nameVi: 'Báo cáo', nameEn: 'Report', shortName: 'BC', sortOrder: 11 },
    { code: 'KET_QUA', nameVi: 'Kết quả', nameEn: 'Result', shortName: 'KQ', sortOrder: 12 },
    { code: 'XEP_LOAI', nameVi: 'Xếp loại', nameEn: 'Classification', shortName: 'XL', sortOrder: 13 },
    { code: 'LICH_HOP', nameVi: 'Lịch họp', nameEn: 'Meeting', shortName: 'LH', sortOrder: 14 },
    { code: 'BIEU_MAU', nameVi: 'Biểu mẫu mới', nameEn: 'New Form', shortName: 'BM', sortOrder: 15 },
  ],
  MD_FILE_FORMAT: [
    { code: 'DOCX', nameVi: 'Word Document', nameEn: 'Word Document', shortName: 'DOCX', sortOrder: 1 },
    { code: 'PDF', nameVi: 'PDF Document', nameEn: 'PDF Document', shortName: 'PDF', sortOrder: 2 },
    { code: 'XLSX', nameVi: 'Excel Spreadsheet', nameEn: 'Excel Spreadsheet', shortName: 'XLSX', sortOrder: 3 },
    { code: 'CSV', nameVi: 'CSV Data', nameEn: 'CSV Data', shortName: 'CSV', sortOrder: 4 },
    { code: 'JSON', nameVi: 'JSON Data', nameEn: 'JSON Data', shortName: 'JSON', sortOrder: 5 },
    { code: 'XML', nameVi: 'XML Data', nameEn: 'XML Data', shortName: 'XML', sortOrder: 6 },
    { code: 'PNG', nameVi: 'PNG Image', nameEn: 'PNG Image', shortName: 'PNG', sortOrder: 7 },
    { code: 'JPG', nameVi: 'JPEG Image', nameEn: 'JPEG Image', shortName: 'JPG', sortOrder: 8 },
    { code: 'MP4', nameVi: 'MP4 Video', nameEn: 'MP4 Video', shortName: 'MP4', sortOrder: 9 },
    { code: 'ZIP', nameVi: 'ZIP Archive', nameEn: 'ZIP Archive', shortName: 'ZIP', sortOrder: 10 },
  ],
  MD_RETIREMENT_REASON: [
    { code: 'DU_TUOI_CT', nameVi: 'Đủ tuổi/năm công tác', nameEn: 'Age/Service Completion', shortName: 'ĐT/CT', sortOrder: 1 },
    { code: 'SUC_KHOE', nameVi: 'Sức khỏe', nameEn: 'Health Reasons', shortName: 'SK', sortOrder: 2 },
    { code: 'VI_PHAM_KY_LUAT', nameVi: 'Vi phạm kỷ luật', nameEn: 'Disciplinary', shortName: 'VPKL', sortOrder: 3 },
    { code: 'TINH_GIAN_BC', nameVi: 'Tinh giản biên chế', nameEn: 'Workforce Reduction', shortName: 'TGBC', sortOrder: 4 },
    { code: 'PHUC_VIEN', nameVi: 'Phục viên', nameEn: 'Demobilized', shortName: 'PV', sortOrder: 5 },
    { code: 'CHUYEN_NGU', nameVi: 'Chuyển ngũ', nameEn: 'Transfer', shortName: 'CNG', sortOrder: 6 },
    { code: 'MAT', nameVi: 'Mất', nameEn: 'Deceased', shortName: 'Mất', sortOrder: 7 },
    { code: 'TU_NGUYEN', nameVi: 'Tự nguyện xin nghỉ', nameEn: 'Voluntary Resignation', shortName: 'TN', sortOrder: 8 },
    { code: 'KET_THUC_HD', nameVi: 'Kết thúc hợp đồng', nameEn: 'Contract Completion', shortName: 'KTHĐ', sortOrder: 9 },
    { code: 'CHUYEN_CONG_TAC', nameVi: 'Chuyển công tác', nameEn: 'Transfer to Other Unit', shortName: 'CCT', sortOrder: 10 },
    { code: 'HA_NGACH', nameVi: 'Hạ ngạch', nameEn: 'Grade Reduction', shortName: 'HN', sortOrder: 11 },
    { code: 'LY_DO_KHAC', nameVi: 'Lý do khác', nameEn: 'Other Reasons', shortName: 'LDK', sortOrder: 12 },
  ],
  MD_SUBJECT_TYPE: [
    { code: 'DAI_CUONG', nameVi: 'Đại cương', nameEn: 'General', shortName: 'ĐC', sortOrder: 1 },
    { code: 'CO_SO_NGANH', nameVi: 'Cơ sở ngành', nameEn: 'Core Discipline', shortName: 'CSN', sortOrder: 2 },
    { code: 'CHUYEN_NGANH', nameVi: 'Chuyên ngành', nameEn: 'Specialization', shortName: 'CN', sortOrder: 3 },
    { code: 'THUC_TAP', nameVi: 'Thực tập', nameEn: 'Internship', shortName: 'TT', sortOrder: 4 },
    { code: 'NGHIEN_CUU', nameVi: 'Nghiên cứu', nameEn: 'Research', shortName: 'NC', sortOrder: 5 },
    { code: 'LUAN_VAN', nameVi: 'Luận văn', nameEn: 'Thesis', shortName: 'LV', sortOrder: 6 },
    { code: 'THE_DUC_QS', nameVi: 'Thể dục QS', nameEn: 'Military PE', shortName: 'TDQS', sortOrder: 7 },
    { code: 'GIAO_DUC_CT', nameVi: 'Giáo dục chính trị', nameEn: 'Political Education', shortName: 'GDCT', sortOrder: 8 },
  ],
  MD_UNIT_LEVEL: [
    { code: 'CAP_1', nameVi: 'Cấp 1 (Học viện)', nameEn: 'Level 1 (Academy)', shortName: 'C1', sortOrder: 1 },
    { code: 'CAP_2', nameVi: 'Cấp 2 (Khoa/Phòng)', nameEn: 'Level 2 (Faculty/Dept)', shortName: 'C2', sortOrder: 2 },
    { code: 'CAP_3', nameVi: 'Cấp 3 (Bộ môn/Ban)', nameEn: 'Level 3 (Division)', shortName: 'C3', sortOrder: 3 },
    { code: 'CAP_4', nameVi: 'Cấp 4 (Lớp/Tổ)', nameEn: 'Level 4 (Class/Group)', shortName: 'C4', sortOrder: 4 },
    { code: 'CAP_DAI_DOI', nameVi: 'Cấp Đại đội', nameEn: 'Company Level', shortName: 'ĐĐ', sortOrder: 5 },
    { code: 'CAP_TRUNG_DOI', nameVi: 'Cấp Trung đội', nameEn: 'Platoon Level', shortName: 'TrĐ', sortOrder: 6 },
  ],
  MD_BLOOD_TYPE: [
    { code: 'A_POSITIVE',  nameVi: 'A+',  nameEn: 'A Positive',  shortName: 'A+',  externalCode: 'A+',  sortOrder: 1 },
    { code: 'A_NEGATIVE',  nameVi: 'A-',  nameEn: 'A Negative',  shortName: 'A-',  externalCode: 'A-',  sortOrder: 2 },
    { code: 'B_POSITIVE',  nameVi: 'B+',  nameEn: 'B Positive',  shortName: 'B+',  externalCode: 'B+',  sortOrder: 3 },
    { code: 'B_NEGATIVE',  nameVi: 'B-',  nameEn: 'B Negative',  shortName: 'B-',  externalCode: 'B-',  sortOrder: 4 },
    { code: 'AB_POSITIVE', nameVi: 'AB+', nameEn: 'AB Positive', shortName: 'AB+', externalCode: 'AB+', sortOrder: 5 },
    { code: 'AB_NEGATIVE', nameVi: 'AB-', nameEn: 'AB Negative', shortName: 'AB-', externalCode: 'AB-', sortOrder: 6 },
    { code: 'O_POSITIVE',  nameVi: 'O+',  nameEn: 'O Positive',  shortName: 'O+',  externalCode: 'O+',  sortOrder: 7 },
    { code: 'O_NEGATIVE',  nameVi: 'O-',  nameEn: 'O Negative',  shortName: 'O-',  externalCode: 'O-',  sortOrder: 8 },
  ],

  // ── MILITARY / HR ──────────────────────────────────────────────────────────
  MD_EMULATION_TITLE: [
    { code: 'CHIEN_SI_XUAT_SAC', nameVi: 'Chiến sĩ xuất sắc', nameEn: 'Outstanding Soldier', shortName: 'CSXS', sortOrder: 1 },
    { code: 'CHIEN_SI_THI_DUA_CO_SO', nameVi: 'Chiến sĩ thi đua cơ sở', nameEn: 'Grassroots Emulation Soldier', shortName: 'CSTĐ-CS', sortOrder: 2 },
    { code: 'CHIEN_SI_THI_DUA_CAP_BO', nameVi: 'Chiến sĩ thi đua cấp Bộ', nameEn: 'Ministry-level Emulation Soldier', shortName: 'CSTĐ-B', sortOrder: 3 },
    { code: 'CHIEN_SI_THI_DUA_TOAN_QUAN', nameVi: 'Chiến sĩ thi đua toàn quân', nameEn: 'Army-wide Emulation Soldier', shortName: 'CSTĐ-TQ', sortOrder: 4 },
    { code: 'TAP_THE_LAO_DONG_TIEN_TIEN', nameVi: 'Tập thể Lao động tiên tiến', nameEn: 'Advanced Collective', shortName: 'TTLĐTT', sortOrder: 5 },
    { code: 'TAP_THE_LAO_DONG_XUAT_SAC', nameVi: 'Tập thể Lao động xuất sắc', nameEn: 'Outstanding Collective', shortName: 'TTLĐXS', sortOrder: 6 },
    { code: 'CO_THI_DUA', nameVi: 'Cờ thi đua', nameEn: 'Emulation Flag', shortName: 'CTĐ', sortOrder: 7 },
    { code: 'CO_THI_DUA_CAP_BO', nameVi: 'Cờ thi đua cấp Bộ', nameEn: 'Ministry Emulation Flag', shortName: 'CTĐ-B', sortOrder: 8 },
    { code: 'CO_THI_DUA_CHINH_PHU', nameVi: 'Cờ thi đua Chính phủ', nameEn: 'Government Emulation Flag', shortName: 'CTĐ-CP', sortOrder: 9 },
    { code: 'HUAN_CHUONG_QUAN_CONG', nameVi: 'Huân chương Quân công', nameEn: 'Military Merit Medal', shortName: 'HCQC', sortOrder: 10 },
    { code: 'HUAN_CHUONG_CHIEN_CONG', nameVi: 'Huân chương Chiến công', nameEn: 'Combat Achievement Medal', shortName: 'HCCC', sortOrder: 11 },
    { code: 'HUAN_CHUONG_BAO_VE_TO_QUOC', nameVi: 'Huân chương Bảo vệ Tổ quốc', nameEn: 'Homeland Defence Medal', shortName: 'HCBVTQ', sortOrder: 12 },
    { code: 'HUAN_CHUONG_LAO_DONG', nameVi: 'Huân chương Lao động', nameEn: 'Labour Medal', shortName: 'HCLĐ', sortOrder: 13 },
    { code: 'HUAN_CHUONG_DOC_LAP', nameVi: 'Huân chương Độc lập', nameEn: 'Independence Medal', shortName: 'HCĐL', sortOrder: 14 },
    { code: 'HUAN_CHUONG_HO_CHI_MINH', nameVi: 'Huân chương Hồ Chí Minh', nameEn: 'Ho Chi Minh Medal', shortName: 'HCHCM', sortOrder: 15 },
    { code: 'ANH_HUNG_LLVTND', nameVi: 'Anh hùng LLVT nhân dân', nameEn: 'People\'s Armed Forces Hero', shortName: 'AHLLVT', sortOrder: 16 },
    { code: 'ANH_HUNG_LAO_DONG', nameVi: 'Anh hùng Lao động', nameEn: 'Labour Hero', shortName: 'AHLĐ', sortOrder: 17 },
    { code: 'BANG_KHEN_BQP', nameVi: 'Bằng khen Bộ Quốc phòng', nameEn: 'MoD Certificate of Merit', shortName: 'BK-BQP', sortOrder: 18 },
    { code: 'BANG_KHEN_THU_TUONG', nameVi: 'Bằng khen Thủ tướng', nameEn: 'Prime Minister Certificate', shortName: 'BK-TT', sortOrder: 19 },
    { code: 'GIAY_KHEN', nameVi: 'Giấy khen', nameEn: 'Certificate of Commendation', shortName: 'GK', sortOrder: 20 },
  ],

  MD_POSITION_TYPE: [
    { code: 'CHI_HUY', nameVi: 'Chỉ huy', nameEn: 'Command', shortName: 'CH', sortOrder: 1 },
    { code: 'CHINH_UY', nameVi: 'Chính ủy / Chính trị viên', nameEn: 'Political Commissar', shortName: 'CU', sortOrder: 2 },
    { code: 'THAM_MUU', nameVi: 'Tham mưu', nameEn: 'Staff', shortName: 'TM', sortOrder: 3 },
    { code: 'GIANG_VIEN', nameVi: 'Giảng viên', nameEn: 'Lecturer', shortName: 'GV', sortOrder: 4 },
    { code: 'NGHIEN_CUU', nameVi: 'Nghiên cứu viên', nameEn: 'Researcher', shortName: 'NCV', sortOrder: 5 },
    { code: 'QUAN_LY', nameVi: 'Quản lý', nameEn: 'Management', shortName: 'QL', sortOrder: 6 },
    { code: 'KY_THUAT', nameVi: 'Kỹ thuật', nameEn: 'Technical', shortName: 'KT', sortOrder: 7 },
    { code: 'HANH_CHINH', nameVi: 'Hành chính', nameEn: 'Administrative', shortName: 'HC', sortOrder: 8 },
    { code: 'HO_TRO', nameVi: 'Hỗ trợ', nameEn: 'Support', shortName: 'HT', sortOrder: 9 },
  ],

  MD_OFFICER_CATEGORY: [
    { code: 'DIEN_TW', nameVi: 'Diện Trung ương quản lý', nameEn: 'Central Level', shortName: 'TW', sortOrder: 1 },
    { code: 'DIEN_BQP', nameVi: 'Diện Bộ Quốc phòng quản lý', nameEn: 'MoD Level', shortName: 'BQP', sortOrder: 2 },
    { code: 'DIEN_QUAN_KHU', nameVi: 'Diện Quân khu / Quân chủng', nameEn: 'Military Region Level', shortName: 'QK', sortOrder: 3 },
    { code: 'DIEN_HOC_VIEN', nameVi: 'Diện Học viện / Nhà trường', nameEn: 'Academy Level', shortName: 'HV', sortOrder: 4 },
    { code: 'DIEN_DON_VI', nameVi: 'Diện Đơn vị trực tiếp', nameEn: 'Direct Unit Level', shortName: 'ĐV', sortOrder: 5 },
  ],

  MD_ACHIEVEMENT_FIELD: [
    { code: 'QUAN_SU', nameVi: 'Quân sự', nameEn: 'Military', shortName: 'QS', sortOrder: 1 },
    { code: 'CHINH_TRI', nameVi: 'Chính trị', nameEn: 'Political', shortName: 'CT', sortOrder: 2 },
    { code: 'HAU_CAN', nameVi: 'Hậu cần', nameEn: 'Logistics', shortName: 'HC', sortOrder: 3 },
    { code: 'KY_THUAT', nameVi: 'Kỹ thuật', nameEn: 'Technical', shortName: 'KT', sortOrder: 4 },
    { code: 'GIAO_DUC_DAO_TAO', nameVi: 'Giáo dục – Đào tạo', nameEn: 'Education & Training', shortName: 'GD', sortOrder: 5 },
    { code: 'KHOA_HOC_CONG_NGHE', nameVi: 'Khoa học – Công nghệ', nameEn: 'Science & Technology', shortName: 'KHCN', sortOrder: 6 },
    { code: 'THE_DUC_THE_THAO', nameVi: 'Thể dục – Thể thao', nameEn: 'Sports', shortName: 'TDTT', sortOrder: 7 },
    { code: 'VAN_HOA_NGHE_THUAT', nameVi: 'Văn hóa – Nghệ thuật', nameEn: 'Culture & Arts', shortName: 'VH', sortOrder: 8 },
    { code: 'AN_NINH_TRAT_TU', nameVi: 'An ninh – Trật tự', nameEn: 'Security & Order', shortName: 'AN', sortOrder: 9 },
    { code: 'XAY_DUNG_DON_VI', nameVi: 'Xây dựng đơn vị', nameEn: 'Unit Development', shortName: 'XDĐV', sortOrder: 10 },
    { code: 'SANG_KIEN_CACH_TAN', nameVi: 'Sáng kiến – Cải tiến', nameEn: 'Innovation', shortName: 'SK', sortOrder: 11 },
    { code: 'PHONG_CHONG_DICH', nameVi: 'Phòng chống dịch bệnh', nameEn: 'Epidemic Prevention', shortName: 'PCDB', sortOrder: 12 },
  ],

  MD_GRADE_COMPONENT: [
    { code: 'CHUYEN_CAN', nameVi: 'Chuyên cần', nameEn: 'Attendance', shortName: 'CC', sortOrder: 1 },
    { code: 'KIEM_TRA_THUONG_XUYEN', nameVi: 'Kiểm tra thường xuyên', nameEn: 'Regular Test', shortName: 'KTTX', sortOrder: 2 },
    { code: 'KIEM_TRA_GIUA_KY', nameVi: 'Kiểm tra giữa kỳ', nameEn: 'Midterm', shortName: 'KTGK', sortOrder: 3 },
    { code: 'THI_CUOI_KY', nameVi: 'Thi cuối kỳ', nameEn: 'Final Exam', shortName: 'TCK', sortOrder: 4 },
    { code: 'THUC_HANH', nameVi: 'Thực hành / Thí nghiệm', nameEn: 'Practical', shortName: 'TH', sortOrder: 5 },
    { code: 'TIEU_LUAN', nameVi: 'Tiểu luận / Bài tập lớn', nameEn: 'Essay/Project', shortName: 'TL', sortOrder: 6 },
    { code: 'BAO_CAO', nameVi: 'Báo cáo thực tập', nameEn: 'Internship Report', shortName: 'BC', sortOrder: 7 },
    { code: 'LUAN_VAN', nameVi: 'Luận văn / Đồ án', nameEn: 'Thesis/Capstone', shortName: 'LV', sortOrder: 8 },
  ],

  MD_DISCIPLINE_REASON: [
    { code: 'VI_PHAM_NOI_QUY', nameVi: 'Vi phạm nội quy, quy định', nameEn: 'Rule Violation', shortName: 'VPNQ', sortOrder: 1 },
    { code: 'GIAN_LAN_THI', nameVi: 'Gian lận trong thi cử', nameEn: 'Exam Cheating', shortName: 'GLT', sortOrder: 2 },
    { code: 'BO_NHIEM_VU', nameVi: 'Bỏ nhiệm vụ, trốn tránh', nameEn: 'Duty Desertion', shortName: 'BNV', sortOrder: 3 },
    { code: 'VI_PHAM_PHAP_LUAT', nameVi: 'Vi phạm pháp luật', nameEn: 'Legal Violation', shortName: 'VPPL', sortOrder: 4 },
    { code: 'HANH_VI_PHI_QUAN_PHONG', nameVi: 'Hành vi phi quân phong', nameEn: 'Unsoldierly Conduct', shortName: 'HVPQP', sortOrder: 5 },
    { code: 'XU_DUNG_CHAT_KICH_THICH', nameVi: 'Sử dụng chất kích thích', nameEn: 'Substance Use', shortName: 'XDCKT', sortOrder: 6 },
    { code: 'THAM_NHUNG', nameVi: 'Tham nhũng, lãng phí', nameEn: 'Corruption/Waste', shortName: 'TN', sortOrder: 7 },
    { code: 'LO_BI_MAT', nameVi: 'Lộ bí mật nhà nước', nameEn: 'State Secret Leak', shortName: 'LBM', sortOrder: 8 },
    { code: 'LY_DO_KHAC', nameVi: 'Lý do khác', nameEn: 'Other', shortName: 'LDK', sortOrder: 9 },
  ],

  MD_BENEFIT_TYPE: [
    { code: 'THUONG_BINH', nameVi: 'Thương binh', nameEn: 'War Invalid', shortName: 'TB', sortOrder: 1 },
    { code: 'BENH_BINH', nameVi: 'Bệnh binh', nameEn: 'Disabled Veteran', shortName: 'BB', sortOrder: 2 },
    { code: 'LIET_SI', nameVi: 'Liệt sĩ (thân nhân)', nameEn: 'Martyr (relative)', shortName: 'LS', sortOrder: 3 },
    { code: 'ANH_HUNG_LLVT', nameVi: 'Anh hùng LLVT nhân dân', shortName: 'AH', sortOrder: 4 },
    { code: 'NGUOI_HOAT_DONG_CM', nameVi: 'Người hoạt động CM trước 1945', shortName: 'HĐCM', sortOrder: 5 },
    { code: 'NGUOI_CO_CONG', nameVi: 'Người có công với cách mạng', shortName: 'NCC', sortOrder: 6 },
    { code: 'PHU_CAP_DOC_HAI', nameVi: 'Phụ cấp độc hại, nguy hiểm', nameEn: 'Hazard Allowance', shortName: 'PCĐH', sortOrder: 7 },
    { code: 'PHU_CAP_THAM_NIEN', nameVi: 'Phụ cấp thâm niên nghề', nameEn: 'Seniority Allowance', shortName: 'PCTN', sortOrder: 8 },
    { code: 'PHU_CAP_KHU_VUC', nameVi: 'Phụ cấp khu vực', nameEn: 'Regional Allowance', shortName: 'PCKV', sortOrder: 9 },
    { code: 'TRO_CAP_KHO_KHAN', nameVi: 'Trợ cấp khó khăn', nameEn: 'Hardship Subsidy', shortName: 'TCKK', sortOrder: 10 },
  ],

  MD_MILITARY_REGION: [
    { code: 'QUAN_KHU_1', nameVi: 'Quân khu 1', nameEn: 'Military Region 1', shortName: 'QK1', sortOrder: 1 },
    { code: 'QUAN_KHU_2', nameVi: 'Quân khu 2', nameEn: 'Military Region 2', shortName: 'QK2', sortOrder: 2 },
    { code: 'QUAN_KHU_3', nameVi: 'Quân khu 3', nameEn: 'Military Region 3', shortName: 'QK3', sortOrder: 3 },
    { code: 'QUAN_KHU_4', nameVi: 'Quân khu 4', nameEn: 'Military Region 4', shortName: 'QK4', sortOrder: 4 },
    { code: 'QUAN_KHU_5', nameVi: 'Quân khu 5', nameEn: 'Military Region 5', shortName: 'QK5', sortOrder: 5 },
    { code: 'QUAN_KHU_7', nameVi: 'Quân khu 7', nameEn: 'Military Region 7', shortName: 'QK7', sortOrder: 6 },
    { code: 'QUAN_KHU_9', nameVi: 'Quân khu 9', nameEn: 'Military Region 9', shortName: 'QK9', sortOrder: 7 },
    { code: 'QUAN_CHUNG_HAI_QUAN', nameVi: 'Quân chủng Hải quân', nameEn: 'Navy', shortName: 'QCHQ', sortOrder: 8 },
    { code: 'QUAN_CHUNG_PHONG_KHONG', nameVi: 'Quân chủng PK-KQ', nameEn: 'Air Defence - Air Force', shortName: 'QCPKKQ', sortOrder: 9 },
    { code: 'BIEN_PHONG', nameVi: 'Bộ đội Biên phòng', nameEn: 'Border Guard', shortName: 'BĐBP', sortOrder: 10 },
    { code: 'CANH_SAT_BIEN', nameVi: 'Cảnh sát biển', nameEn: 'Coast Guard', shortName: 'CSB', sortOrder: 11 },
    { code: 'CO_QUAN_BQP', nameVi: 'Cơ quan Bộ Quốc phòng', nameEn: 'MoD Headquarters', shortName: 'BQPTW', sortOrder: 12 },
  ],

  MD_BRANCH: [
    { code: 'BO_BINH', nameVi: 'Bộ binh', nameEn: 'Infantry', shortName: 'BB', sortOrder: 1 },
    { code: 'THIET_GIAP', nameVi: 'Thiết giáp', nameEn: 'Armour', shortName: 'TG', sortOrder: 2 },
    { code: 'PHAO_BINH', nameVi: 'Pháo binh', nameEn: 'Artillery', shortName: 'PB', sortOrder: 3 },
    { code: 'PHONG_KHONG', nameVi: 'Phòng không', nameEn: 'Air Defence', shortName: 'PK', sortOrder: 4 },
    { code: 'THONG_TIN', nameVi: 'Thông tin', nameEn: 'Signal', shortName: 'TT', sortOrder: 5 },
    { code: 'CONG_BINH', nameVi: 'Công binh', nameEn: 'Engineering', shortName: 'CB', sortOrder: 6 },
    { code: 'HOA_HOC', nameVi: 'Hóa học', nameEn: 'Chemical', shortName: 'HH', sortOrder: 7 },
    { code: 'HAU_CAN', nameVi: 'Hậu cần', nameEn: 'Logistics', shortName: 'HC', sortOrder: 8 },
    { code: 'KY_THUAT', nameVi: 'Kỹ thuật', nameEn: 'Technical', shortName: 'KT', sortOrder: 9 },
    { code: 'HAI_QUAN', nameVi: 'Hải quân', nameEn: 'Navy', shortName: 'HQ', sortOrder: 10 },
    { code: 'PHONG_KHONG_KHONG_QUAN', nameVi: 'PK – Không quân', nameEn: 'Air Force', shortName: 'PKKQ', sortOrder: 11 },
    { code: 'DACS_CONG', nameVi: 'Đặc công', nameEn: 'Special Forces', shortName: 'ĐC', sortOrder: 12 },
  ],

  MD_PARTY_DISCIPLINE: [
    { code: 'KHIEN_TRACH', nameVi: 'Khiển trách', nameEn: 'Warning', shortName: 'KT', sortOrder: 1 },
    { code: 'CANH_CAO', nameVi: 'Cảnh cáo', nameEn: 'Reprimand', shortName: 'CC', sortOrder: 2 },
    { code: 'CACH_CHUC', nameVi: 'Cách chức', nameEn: 'Removal from Office', shortName: 'CCh', sortOrder: 3 },
    { code: 'KHAI_TRU', nameVi: 'Khai trừ Đảng', nameEn: 'Expulsion', shortName: 'KTr', sortOrder: 4 },
  ],

  MD_PARTY_ROLE: [
    { code: 'BI_THU', nameVi: 'Bí thư', nameEn: 'Secretary', shortName: 'BT', sortOrder: 1 },
    { code: 'PHO_BI_THU', nameVi: 'Phó Bí thư', nameEn: 'Deputy Secretary', shortName: 'PBT', sortOrder: 2 },
    { code: 'UV_BCH', nameVi: 'Ủy viên BCH', nameEn: 'Standing Committee Member', shortName: 'UVBCH', sortOrder: 3 },
    { code: 'DANG_VIEN', nameVi: 'Đảng viên', nameEn: 'Party Member', shortName: 'ĐV', sortOrder: 4 },
    { code: 'DANG_VIEN_DU_BI', nameVi: 'Đảng viên dự bị', nameEn: 'Probationary Member', shortName: 'ĐVDB', sortOrder: 5 },
  ],

  MD_YOUTH_ORG: [
    { code: 'DOAN_TNCS', nameVi: 'Đoàn TNCS Hồ Chí Minh', nameEn: 'Ho Chi Minh Communist Youth Union', shortName: 'Đoàn', sortOrder: 1 },
    { code: 'HOI_CCB', nameVi: 'Hội Cựu chiến binh', nameEn: 'Veterans Association', shortName: 'CCB', sortOrder: 2 },
    { code: 'HOI_PN', nameVi: 'Hội Phụ nữ', nameEn: "Women's Association", shortName: 'HPN', sortOrder: 3 },
    { code: 'CONG_DOAN', nameVi: 'Công đoàn', nameEn: 'Trade Union', shortName: 'CĐ', sortOrder: 4 },
    { code: 'HOI_KHOA_HOC', nameVi: 'Hội Khoa học kỹ thuật', nameEn: 'Science & Technology Association', shortName: 'HKH', sortOrder: 5 },
  ],

  MD_PROFESSIONAL_TITLE: [
    { code: 'GIANG_VIEN_CAO_CAP', nameVi: 'Giảng viên cao cấp', nameEn: 'Senior Lecturer', shortName: 'GVCC', sortOrder: 1 },
    { code: 'GIANG_VIEN_CHINH', nameVi: 'Giảng viên chính', nameEn: 'Principal Lecturer', shortName: 'GVCh', sortOrder: 2 },
    { code: 'GIANG_VIEN', nameVi: 'Giảng viên', nameEn: 'Lecturer', shortName: 'GV', sortOrder: 3 },
    { code: 'NGHIEN_CUU_VIEN_CAO_CAP', nameVi: 'Nghiên cứu viên cao cấp', nameEn: 'Senior Researcher', shortName: 'NCVCC', sortOrder: 4 },
    { code: 'NGHIEN_CUU_VIEN_CHINH', nameVi: 'Nghiên cứu viên chính', nameEn: 'Principal Researcher', shortName: 'NCVCh', sortOrder: 5 },
    { code: 'NGHIEN_CUU_VIEN', nameVi: 'Nghiên cứu viên', nameEn: 'Researcher', shortName: 'NCV', sortOrder: 6 },
    { code: 'KY_SU_CAO_CAP', nameVi: 'Kỹ sư cao cấp', nameEn: 'Senior Engineer', shortName: 'KSCC', sortOrder: 7 },
    { code: 'KY_SU', nameVi: 'Kỹ sư', nameEn: 'Engineer', shortName: 'KS', sortOrder: 8 },
    { code: 'KY_THUAT_VIEN', nameVi: 'Kỹ thuật viên', nameEn: 'Technician', shortName: 'KTV', sortOrder: 9 },
  ],

  MD_UNIT_OF_MEASURE: [
    { code: 'CAI', nameVi: 'Cái', nameEn: 'Unit', shortName: 'cái', sortOrder: 1 },
    { code: 'BO', nameVi: 'Bộ', nameEn: 'Set', shortName: 'bộ', sortOrder: 2 },
    { code: 'KG', nameVi: 'Kilôgam', nameEn: 'Kilogram', shortName: 'kg', externalCode: 'kg', sortOrder: 3 },
    { code: 'TAN', nameVi: 'Tấn', nameEn: 'Tonne', shortName: 'tấn', externalCode: 't', sortOrder: 4 },
    { code: 'LIT', nameVi: 'Lít', nameEn: 'Litre', shortName: 'L', externalCode: 'L', sortOrder: 5 },
    { code: 'M3', nameVi: 'Mét khối', nameEn: 'Cubic Metre', shortName: 'm³', externalCode: 'm3', sortOrder: 6 },
    { code: 'M2', nameVi: 'Mét vuông', nameEn: 'Square Metre', shortName: 'm²', externalCode: 'm2', sortOrder: 7 },
    { code: 'M', nameVi: 'Mét', nameEn: 'Metre', shortName: 'm', externalCode: 'm', sortOrder: 8 },
    { code: 'KM', nameVi: 'Kilômét', nameEn: 'Kilometre', shortName: 'km', externalCode: 'km', sortOrder: 9 },
    { code: 'CUON', nameVi: 'Cuộn', nameEn: 'Roll', shortName: 'cuộn', sortOrder: 10 },
    { code: 'HOP', nameVi: 'Hộp', nameEn: 'Box', shortName: 'hộp', sortOrder: 11 },
    { code: 'THUNG', nameVi: 'Thùng', nameEn: 'Drum/Barrel', shortName: 'thùng', sortOrder: 12 },
    { code: 'CHIEC', nameVi: 'Chiếc', nameEn: 'Piece', shortName: 'chiếc', sortOrder: 13 },
    { code: 'KHU', nameVi: 'Khẩu (pháo, súng)', nameEn: 'Unit (weapon)', shortName: 'khẩu', sortOrder: 14 },
    { code: 'CHIEU_SINH', nameVi: 'Chiêu sinh (người)', nameEn: 'Person', shortName: 'người', sortOrder: 15 },
  ],

  MD_FUEL_TYPE: [
    { code: 'XANG_A95', nameVi: 'Xăng RON 95', nameEn: 'Petrol RON 95', shortName: 'A95', sortOrder: 1 },
    { code: 'XANG_A92', nameVi: 'Xăng RON 92', nameEn: 'Petrol RON 92', shortName: 'A92', sortOrder: 2 },
    { code: 'DAU_DIESEL', nameVi: 'Dầu diesel', nameEn: 'Diesel', shortName: 'DO', sortOrder: 3 },
    { code: 'DAU_MAY', nameVi: 'Dầu máy (dầu nhờn)', nameEn: 'Engine Oil', shortName: 'DM', sortOrder: 4 },
    { code: 'NHIEN_LIEU_HANG_KHONG', nameVi: 'Nhiên liệu hàng không', nameEn: 'Aviation Fuel', shortName: 'Jet-A', sortOrder: 5 },
    { code: 'GAS', nameVi: 'Khí gas (LPG)', nameEn: 'LPG', shortName: 'LPG', sortOrder: 6 },
  ],

  MD_MAINTENANCE_TYPE: [
    { code: 'BAO_DUONG_DINH_KY', nameVi: 'Bảo dưỡng định kỳ', nameEn: 'Scheduled Maintenance', shortName: 'BĐDK', sortOrder: 1 },
    { code: 'SUA_CHUA_NHO', nameVi: 'Sửa chữa nhỏ', nameEn: 'Minor Repair', shortName: 'SCN', sortOrder: 2 },
    { code: 'SUA_CHUA_TRUNG', nameVi: 'Sửa chữa trung', nameEn: 'Medium Repair', shortName: 'SCTr', sortOrder: 3 },
    { code: 'SUA_CHUA_LON', nameVi: 'Sửa chữa lớn', nameEn: 'Major Repair', shortName: 'SCL', sortOrder: 4 },
    { code: 'KIEM_TRA_KY_THUAT', nameVi: 'Kiểm tra kỹ thuật', nameEn: 'Technical Inspection', shortName: 'KTKT', sortOrder: 5 },
    { code: 'PHUC_HOI', nameVi: 'Phục hồi', nameEn: 'Restoration', shortName: 'PH', sortOrder: 6 },
  ],

  MD_EQUIPMENT_TYPE: [
    { code: 'VU_KHI', nameVi: 'Vũ khí', nameEn: 'Weapons', shortName: 'VK', sortOrder: 1 },
    { code: 'PHAO', nameVi: 'Pháo', nameEn: 'Artillery', shortName: 'Pháo', sortOrder: 2 },
    { code: 'XE_QUAN_SU', nameVi: 'Xe quân sự', nameEn: 'Military Vehicle', shortName: 'XQS', sortOrder: 3 },
    { code: 'KHI_TAI_THONG_TIN', nameVi: 'Khí tài thông tin', nameEn: 'Signal Equipment', shortName: 'KTTT', sortOrder: 4 },
    { code: 'KHI_TAI_QUAN_SU', nameVi: 'Khí tài quân sự khác', nameEn: 'Other Military Equipment', shortName: 'KTQS', sortOrder: 5 },
    { code: 'TRANG_BI_BAO_HO', nameVi: 'Trang bị bảo hộ', nameEn: 'Protective Equipment', shortName: 'TBBH', sortOrder: 6 },
    { code: 'TRANG_THIET_BI_CNTT', nameVi: 'Trang thiết bị CNTT', nameEn: 'IT Equipment', shortName: 'CNTT', sortOrder: 7 },
    { code: 'TRANG_BI_Y_TE', nameVi: 'Trang bị y tế', nameEn: 'Medical Equipment', shortName: 'YT', sortOrder: 8 },
    { code: 'TRANG_BI_PHONG_CHAY', nameVi: 'Trang bị phòng cháy', nameEn: 'Fire Protection', shortName: 'PCCC', sortOrder: 9 },
    { code: 'TRANG_BI_KHAC', nameVi: 'Trang bị khác', nameEn: 'Other', shortName: 'Khác', sortOrder: 10 },
  ],

  MD_MATERIAL_CATEGORY: [
    { code: 'NHIEN_LIEU', nameVi: 'Nhiên liệu, dầu mỡ', nameEn: 'Fuel & Lubricants', shortName: 'NL', sortOrder: 1 },
    { code: 'VU_KHI_DAM', nameVi: 'Vũ khí, đạn dược', nameEn: 'Weapons & Ammunition', shortName: 'VKĐD', sortOrder: 2 },
    { code: 'LUONG_THUC_THUC_PHAM', nameVi: 'Lương thực, thực phẩm', nameEn: 'Food & Provisions', shortName: 'LTTP', sortOrder: 3 },
    { code: 'QUAN_PHUC', nameVi: 'Quân phục, quân trang', nameEn: 'Uniforms & Gear', shortName: 'QP', sortOrder: 4 },
    { code: 'THIET_BI_KY_THUAT', nameVi: 'Thiết bị kỹ thuật', nameEn: 'Technical Equipment', shortName: 'TBKT', sortOrder: 5 },
    { code: 'DUOC_PHAM', nameVi: 'Dược phẩm, y tế', nameEn: 'Pharmaceuticals & Medical', shortName: 'DP', sortOrder: 6 },
    { code: 'VAT_TU_XAY_DUNG', nameVi: 'Vật tư xây dựng', nameEn: 'Construction Materials', shortName: 'VTXD', sortOrder: 7 },
    { code: 'VAN_PHONG_PHAM', nameVi: 'Văn phòng phẩm', nameEn: 'Stationery & Office Supplies', shortName: 'VPP', sortOrder: 8 },
  ],

  MD_HOMETOWN_REGION: [
    { code: 'MIEN_BAC', nameVi: 'Miền Bắc', nameEn: 'Northern Region', shortName: 'MB', sortOrder: 1 },
    { code: 'MIEN_TRUNG', nameVi: 'Miền Trung', nameEn: 'Central Region', shortName: 'MT', sortOrder: 2 },
    { code: 'MIEN_NAM', nameVi: 'Miền Nam', nameEn: 'Southern Region', shortName: 'MN', sortOrder: 3 },
    { code: 'TAY_NGUYEN', nameVi: 'Tây Nguyên', nameEn: 'Central Highlands', shortName: 'TN', sortOrder: 4 },
    { code: 'DONG_BAC', nameVi: 'Đông Bắc', nameEn: 'Northeast', shortName: 'ĐB', sortOrder: 5 },
    { code: 'TAY_BAC', nameVi: 'Tây Bắc', nameEn: 'Northwest', shortName: 'TB', sortOrder: 6 },
    { code: 'DONG_BANG_BB', nameVi: 'Đồng bằng Bắc Bộ', nameEn: 'Red River Delta', shortName: 'ĐBBB', sortOrder: 7 },
    { code: 'DONG_BANG_NB', nameVi: 'Đồng bằng Nam Bộ', nameEn: 'Mekong Delta', shortName: 'ĐBNB', sortOrder: 8 },
    { code: 'DUYEN_HAI', nameVi: 'Duyên hải miền Trung', nameEn: 'Central Coast', shortName: 'DHT', sortOrder: 9 },
  ],

  MD_RESEARCH_FIELD: [
    { code: 'KH_QS', nameVi: 'Khoa học quân sự', nameEn: 'Military Science', shortName: 'KHQS', sortOrder: 1 },
    { code: 'KH_KY_THUAT_QS', nameVi: 'Kỹ thuật quân sự', nameEn: 'Military Technology', shortName: 'KTQS', sortOrder: 2 },
    { code: 'HAU_CAN_KY_THUAT', nameVi: 'Hậu cần – Kỹ thuật', nameEn: 'Logistics Technology', shortName: 'HCKT', sortOrder: 3 },
    { code: 'KHOA_HOC_XA_HOI', nameVi: 'Khoa học xã hội nhân văn', nameEn: 'Social Sciences', shortName: 'KHXH', sortOrder: 4 },
    { code: 'KINH_TE_QUOC_PHONG', nameVi: 'Kinh tế quốc phòng', nameEn: 'Defence Economics', shortName: 'KTQP', sortOrder: 5 },
    { code: 'CNTT_VA_TRUYEN_THONG', nameVi: 'CNTT và Truyền thông', nameEn: 'ICT', shortName: 'CNTT', sortOrder: 6 },
    { code: 'KHOA_HOC_GIAO_DUC', nameVi: 'Khoa học giáo dục', nameEn: 'Education Science', shortName: 'KHGD', sortOrder: 7 },
    { code: 'Y_DUOC_QUAN_SU', nameVi: 'Y dược quân sự', nameEn: 'Military Medicine', shortName: 'YDQS', sortOrder: 8 },
    { code: 'MOI_TRUONG_BIEN', nameVi: 'Môi trường – Biển đảo', nameEn: 'Environment & Maritime', shortName: 'MTB', sortOrder: 9 },
  ],

  MD_SUBJECT_GROUP: [
    { code: 'KHOA_HOC_CO_BAN', nameVi: 'Khoa học cơ bản', nameEn: 'Basic Sciences', shortName: 'KHCB', sortOrder: 1 },
    { code: 'LY_LUAN_CHINH_TRI', nameVi: 'Lý luận chính trị', nameEn: 'Political Theory', shortName: 'LLCT', sortOrder: 2 },
    { code: 'QUAN_SU_CHUNG', nameVi: 'Quân sự chung', nameEn: 'General Military', shortName: 'QSC', sortOrder: 3 },
    { code: 'CHUYEN_NGANH_HAU_CAN', nameVi: 'Chuyên ngành Hậu cần', nameEn: 'Logistics Specialization', shortName: 'CNHC', sortOrder: 4 },
    { code: 'NGOAI_NGU', nameVi: 'Ngoại ngữ', nameEn: 'Foreign Languages', shortName: 'NN', sortOrder: 5 },
    { code: 'TIN_HOC', nameVi: 'Tin học', nameEn: 'Computer Science', shortName: 'TH', sortOrder: 6 },
    { code: 'THE_CHAT_QUOC_PHONG', nameVi: 'Thể chất – Quốc phòng', nameEn: 'Physical & Defence', shortName: 'TCQP', sortOrder: 7 },
    { code: 'THUC_TAP_THUC_TE', nameVi: 'Thực tập – Thực tế', nameEn: 'Internship & Fieldwork', shortName: 'TTTT', sortOrder: 8 },
  ],
}

// ── MAIN ─────────────────────────────────────────────────────────────────────

async function main() {
  const overwrite = SEED_META.allowOverwrite ? ' [OVERWRITE=true]' : ''
  const skipVer  = SEED_META.skipIfVersionMatch ? ' [SKIP_VERSION=true]' : ''
  console.log(`🌱 Seeding M19 Master Data v${SEED_META.version}${overwrite}${skipVer}\n`)

  let totalCreated = 0
  let totalUpdated = 0
  let totalSkipped = 0

  for (const cat of CATEGORIES) {
    const items = ITEMS[cat.code] ?? []
    const result = await upsertCategoryWithItems(prisma, cat, items, SEED_META)

    const line = items.length === 0
      ? `  ✅ ${cat.code.padEnd(28)} (category only, no items seeded yet)`
      : `  ✅ ${cat.code.padEnd(28)} +${result.created} new / ~${result.updated} upd / ⏭${result.skipped} skip`
    console.log(line)

    totalCreated += result.created
    totalUpdated += result.updated
    totalSkipped += result.skipped
  }

  console.log('\n════════════════════════════════════════════')
  console.log('  M19 MASTER DATA SEED HOÀN THÀNH')
  console.log('════════════════════════════════════════════')
  console.log(`  Categories:  ${CATEGORIES.length}`)
  console.log(`  Items mới:   ${totalCreated}`)
  console.log(`  Items cập nhật: ${totalUpdated}`)
  console.log(`  Items bỏ qua:   ${totalSkipped}  ← admin đã chỉnh hoặc đã ở version này`)
  console.log('════════════════════════════════════════════\n')
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
