/** M02 — Nhân sự (NHAN_SU). 6 thể thức + 1 hồ sơ cá nhân entity-bound. */

import type { TemplateSpec } from '../types';
import { DOTS, HEADER_PH } from './shared';

export const M02_SPECS: TemplateSpec[] = [
  {
    code: 'TPL_M02_BC_TONGKET',
    name: 'Báo cáo tổng kết công tác cán bộ',
    description: 'Mẫu báo cáo tổng kết công tác cán bộ theo kỳ/năm (Nghị định 30/2020).',
    docType: 'BC',
    category: 'NHAN_SU',
    module: 'M02',
    moduleSource: ['M02'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC-PCB',
    trichYeu: 'Tổng kết công tác cán bộ năm ......',
    body: [
      {
        heading: 'Phần I. KẾT QUẢ THỰC HIỆN',
        paragraphs: [
          `1. Công tác quân số, biên chế, điều động: ${DOTS}`,
          `2. Công tác quy hoạch, bổ nhiệm, đề bạt: ${DOTS}`,
          `3. Công tác đào tạo, bồi dưỡng cán bộ: ${DOTS}`,
          `4. Công tác chính sách cán bộ: ${DOTS}`,
        ],
      },
      {
        heading: 'Phần II. ĐÁNH GIÁ, NHẬN XÉT',
        paragraphs: [`1. Ưu điểm: ${DOTS}`, `2. Hạn chế, khuyết điểm: ${DOTS}`, `3. Nguyên nhân: ${DOTS}`],
      },
      { heading: 'Phần III. PHƯƠNG HƯỚNG, NHIỆM VỤ THỜI GIAN TỚI', paragraphs: [DOTS] },
      { heading: 'Phần IV. KIẾN NGHỊ, ĐỀ XUẤT', paragraphs: [DOTS] },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Thủ trưởng Học viện (để b/c);'],
    luuBoPhan: 'PCB',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M02_CV',
    name: 'Công văn (công tác cán bộ)',
    description: 'Mẫu công văn hành chính của cơ quan cán bộ (không có tên loại văn bản).',
    docType: 'CV',
    category: 'NHAN_SU',
    module: 'M02',
    moduleSource: ['M02'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'HVHC-PCB',
    trichYeu: '(trích yếu nội dung công văn)',
    kinhGui: DOTS,
    body: [{ paragraphs: [`Thực hiện ${DOTS}`, `${DOTS}`, `Phòng Cán bộ đề nghị ${DOTS}`] }],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như trên;'],
    luuBoPhan: 'PCB',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M02_KH',
    name: 'Kế hoạch công tác cán bộ',
    description: 'Mẫu kế hoạch công tác cán bộ (Mục đích/Yêu cầu, Nội dung, Tổ chức thực hiện).',
    docType: 'KH',
    category: 'NHAN_SU',
    module: 'M02',
    moduleSource: ['M02'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'KH-HVHC',
    trichYeu: 'Công tác cán bộ năm ......',
    body: [
      { heading: 'I. MỤC ĐÍCH, YÊU CẦU', paragraphs: [`1. Mục đích: ${DOTS}`, `2. Yêu cầu: ${DOTS}`] },
      {
        heading: 'II. NỘI DUNG KẾ HOẠCH',
        paragraphs: [`1. ${DOTS} (Thực hiện: ......; Thời gian: ......; Sản phẩm: ......)`, `2. ${DOTS}`],
      },
      {
        heading: 'III. TỔ CHỨC THỰC HIỆN',
        paragraphs: [
          `1. Trách nhiệm các cơ quan, đơn vị: ${DOTS}`,
          `2. Chế độ thông tin, báo cáo: ${DOTS}`,
          `3. Điều kiện bảo đảm: ${DOTS}`,
        ],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Các cơ quan, đơn vị (để t/h);'],
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M02_TTr',
    name: 'Tờ trình (công tác cán bộ)',
    description: 'Mẫu tờ trình đề nghị cấp trên phê duyệt về công tác cán bộ.',
    docType: 'TTr',
    category: 'NHAN_SU',
    module: 'M02',
    moduleSource: ['M02'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TTr-HVHC-PCB',
    trichYeu: 'Về việc ......',
    kinhGui: 'Thủ trưởng Học viện Hậu cần',
    body: [
      { heading: 'I. SỰ CẦN THIẾT', paragraphs: [DOTS] },
      { heading: 'II. NỘI DUNG ĐỀ NGHỊ', paragraphs: [`1. ${DOTS}`, `2. ${DOTS}`, `3. ${DOTS}`] },
      { heading: 'III. KIẾN NGHỊ', paragraphs: ['Kính đề nghị Thủ trưởng Học viện xem xét, quyết định./.'] },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như kính gửi (để b/c);'],
    luuBoPhan: 'PCB',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M02_QD_CANHAN',
    name: 'Quyết định (đối với một cán bộ)',
    description: 'Mẫu quyết định cá biệt đối với một cán bộ (gắn dữ liệu nhân sự).',
    docType: 'QD',
    category: 'NHAN_SU',
    module: 'M02',
    moduleSource: ['M02'],
    entity: 'personnel',
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'QĐ-HVHC',
    trichYeu: 'Về việc ...... đối với cán bộ',
    banHanhChucDanh: 'GIÁM ĐỐC HỌC VIỆN HẬU CẦN',
    canCu: [
      'Luật Sĩ quan Quân đội nhân dân Việt Nam',
      'Quyết định quy định chức năng, nhiệm vụ, quyền hạn của Học viện Hậu cần',
      'yêu cầu nhiệm vụ và năng lực cán bộ',
    ],
    theoDeNghi: 'Trưởng Phòng Cán bộ',
    body: [
      {
        heading: 'Điều 1.',
        paragraphs: [
          'Đối với đồng chí {hoTen}, cấp bậc {capBac}, chức vụ {chucVu}, đơn vị {donViCongTac}.',
          `Nội dung: ${DOTS}`,
        ],
      },
      {
        heading: 'Điều 2.',
        paragraphs: ['Quyền lợi, nghĩa vụ của đồng chí có tên tại Điều 1 thực hiện theo quy định hiện hành.'],
      },
      {
        heading: 'Điều 3.',
        paragraphs: [
          'Quyết định này có hiệu lực kể từ ngày ký. Thủ trưởng các cơ quan, đơn vị liên quan và đồng chí có tên tại Điều 1 chịu trách nhiệm thi hành Quyết định này./.',
        ],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Như Điều 3;'],
    placeholders: [...HEADER_PH, '{hoTen}', '{capBac}', '{chucVu}', '{donViCongTac}'],
  },
  {
    code: 'TPL_M02_TB',
    name: 'Thông báo (công tác cán bộ)',
    description: 'Mẫu thông báo của cơ quan cán bộ (kết thúc "để biết, thực hiện./.").',
    docType: 'TB',
    category: 'NHAN_SU',
    module: 'M02',
    moduleSource: ['M02'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TB-HVHC-PCB',
    trichYeu: '......',
    body: [
      {
        paragraphs: [
          `Căn cứ ${DOTS}`,
          'Phòng Cán bộ thông báo nội dung như sau:',
          `1. ${DOTS}`,
          `2. ${DOTS}`,
          'Phòng Cán bộ thông báo để các cơ quan, đơn vị biết, thực hiện./.',
        ],
      },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Các cơ quan, đơn vị (để t/h);'],
    luuBoPhan: 'PCB',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M02_BC_CANHAN',
    name: 'Sơ yếu lý lịch / Báo cáo cá nhân cán bộ',
    description: 'Mẫu sơ yếu lý lịch cán bộ (gắn dữ liệu nhân sự + bảng quá trình công tác).',
    docType: 'BC',
    category: 'NHAN_SU',
    module: 'M02',
    moduleSource: ['M02'],
    entity: 'personnel',
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC',
    trichYeu: 'Sơ yếu lý lịch cán bộ',
    body: [
      {
        heading: 'I. THÔNG TIN CÁ NHÂN',
        paragraphs: [
          'Họ và tên: {hoTen}',
          'Cấp bậc: {capBac}          Chức vụ: {chucVu}',
          'Ngày sinh: {ngaySinh}          Giới tính: {gioiTinh}',
          'Quê quán: {queQuan}',
          'Đơn vị công tác: {donViCongTac}',
          'Số hiệu quân nhân: {militaryId}',
          'Ngày vào Đảng: {ngayVaoDang}',
        ],
      },
      {
        heading: 'II. QUÁ TRÌNH CÔNG TÁC',
        loop: {
          key: 'congTac_list',
          columns: [
            { header: 'Từ tháng/năm', field: 'tuNgay', weight: 1, align: 'center' },
            { header: 'Đến tháng/năm', field: 'denNgay', weight: 1, align: 'center' },
            { header: 'Đơn vị công tác', field: 'noiCongTac', weight: 3 },
            { header: 'Chức vụ, công việc', field: 'congViec', weight: 3 },
          ],
        },
      },
      { heading: 'III. KHEN THƯỞNG - KỶ LUẬT', paragraphs: ['Khen thưởng: {khenThuong}', 'Kỷ luật: {kyLuat}'] },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG CÁN BỘ'],
    noiNhan: ['- Lưu hồ sơ cán bộ;'],
    luuBoPhan: 'PCB',
    placeholders: [
      ...HEADER_PH,
      '{hoTen}',
      '{capBac}',
      '{chucVu}',
      '{ngaySinh}',
      '{gioiTinh}',
      '{queQuan}',
      '{donViCongTac}',
      '{militaryId}',
      '{ngayVaoDang}',
      '{#congTac_list}',
      '{khenThuong}',
      '{kyLuat}',
    ],
  },
];
