/** M03 — Đảng viên (DANG_VIEN, CONFIDENTIAL). Header ghi đè theo cơ quan Đảng. */

import type { TemplateSpec } from '../types';
import { DOTS, PARTY_PH, DU_HEADER, CB_HEADER } from './shared';

export const M03_SPECS: TemplateSpec[] = [
  {
    code: 'TPL_M03_BC_TONGKET',
    name: 'Báo cáo tổng kết công tác xây dựng Đảng',
    description: 'Mẫu báo cáo tổng kết công tác Đảng theo kỳ/năm của Đảng ủy.',
    docType: 'BC',
    category: 'DANG_VIEN',
    module: 'M03',
    moduleSource: ['M03'],
    entity: null,
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    ...DU_HEADER,
    kyHieu: 'BC-ĐU',
    trichYeu: 'Tổng kết công tác xây dựng Đảng năm ......',
    body: [
      {
        heading: 'Phần I. KẾT QUẢ THỰC HIỆN',
        paragraphs: [
          `1. Công tác chính trị, tư tưởng: ${DOTS}`,
          `2. Công tác tổ chức, cán bộ, đảng viên: ${DOTS}`,
          `3. Công tác kiểm tra, giám sát, kỷ luật Đảng: ${DOTS}`,
          `4. Công tác dân vận và lãnh đạo các tổ chức quần chúng: ${DOTS}`,
        ],
      },
      {
        heading: 'Phần II. ĐÁNH GIÁ, NHẬN XÉT',
        paragraphs: [`1. Ưu điểm: ${DOTS}`, `2. Hạn chế, khuyết điểm: ${DOTS}`, `3. Nguyên nhân: ${DOTS}`],
      },
      { heading: 'Phần III. PHƯƠNG HƯỚNG, NHIỆM VỤ THỜI GIAN TỚI', paragraphs: [DOTS] },
      { heading: 'Phần IV. KIẾN NGHỊ, ĐỀ XUẤT', paragraphs: [DOTS] },
    ],
    chuKyChucVu: ['T/M ĐẢNG ỦY', 'BÍ THƯ'],
    noiNhan: ['- Đảng ủy cấp trên (để b/c);', '- Các chi bộ trực thuộc (để t/h);'],
    luuBoPhan: 'VPĐU',
    placeholders: PARTY_PH,
  },
  {
    code: 'TPL_M03_KH',
    name: 'Kế hoạch công tác xây dựng Đảng',
    description: 'Mẫu kế hoạch công tác Đảng (Mục đích/Yêu cầu, Nội dung, Tổ chức thực hiện).',
    docType: 'KH',
    category: 'DANG_VIEN',
    module: 'M03',
    moduleSource: ['M03'],
    entity: null,
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    ...DU_HEADER,
    kyHieu: 'KH-ĐU',
    trichYeu: 'Công tác xây dựng Đảng năm ......',
    body: [
      { heading: 'I. MỤC ĐÍCH, YÊU CẦU', paragraphs: [`1. Mục đích: ${DOTS}`, `2. Yêu cầu: ${DOTS}`] },
      { heading: 'II. NỘI DUNG KẾ HOẠCH', paragraphs: [`1. ${DOTS}`, `2. ${DOTS}`] },
      {
        heading: 'III. TỔ CHỨC THỰC HIỆN',
        paragraphs: [`1. Trách nhiệm các chi bộ: ${DOTS}`, `2. Chế độ thông tin, báo cáo: ${DOTS}`],
      },
    ],
    chuKyChucVu: ['T/M ĐẢNG ỦY', 'BÍ THƯ'],
    noiNhan: ['- Các chi bộ trực thuộc (để t/h);'],
    luuBoPhan: 'VPĐU',
    placeholders: PARTY_PH,
  },
  {
    code: 'TPL_M03_TTr_KETNAP',
    name: 'Tờ trình đề nghị kết nạp đảng viên',
    description: 'Mẫu tờ trình của chi bộ đề nghị Đảng ủy xét kết nạp đảng viên.',
    docType: 'TTr',
    category: 'DANG_VIEN',
    module: 'M03',
    moduleSource: ['M03'],
    entity: null,
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    ...CB_HEADER,
    kyHieu: 'TTr-CB',
    trichYeu: 'Đề nghị kết nạp đảng viên',
    kinhGui: 'Đảng ủy Học viện Hậu cần',
    body: [
      { heading: 'I. SỰ CẦN THIẾT', paragraphs: [`Qua quá trình theo dõi, bồi dưỡng quần chúng ưu tú ${DOTS}`] },
      {
        heading: 'II. NỘI DUNG ĐỀ NGHỊ',
        paragraphs: [
          'Họ và tên: ......          Ngày sinh: ......',
          `Quá trình phấn đấu, rèn luyện: ${DOTS}`,
          'Kết quả biểu quyết của chi bộ: ......./...... đồng chí đồng ý.',
        ],
      },
      {
        heading: 'III. KIẾN NGHỊ',
        paragraphs: ['Chi bộ kính đề nghị Đảng ủy xem xét, ra quyết định kết nạp đảng viên./.'],
      },
    ],
    chuKyChucVu: ['T/M CHI BỘ', 'BÍ THƯ'],
    noiNhan: ['- Như kính gửi;'],
    luuBoPhan: 'CB',
    placeholders: PARTY_PH,
  },
  {
    code: 'TPL_M03_QD',
    name: 'Quyết định (công tác Đảng)',
    description: 'Mẫu quyết định của Đảng ủy về công tác Đảng (3 điều).',
    docType: 'QD',
    category: 'DANG_VIEN',
    module: 'M03',
    moduleSource: ['M03'],
    entity: null,
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    ...DU_HEADER,
    kyHieu: 'QĐ-ĐU',
    trichYeu: 'Về việc ......',
    banHanhChucDanh: 'BAN THƯỜNG VỤ ĐẢNG ỦY HỌC VIỆN HẬU CẦN',
    canCu: [
      'Điều lệ Đảng Cộng sản Việt Nam',
      'Quy chế làm việc của Đảng ủy Học viện Hậu cần nhiệm kỳ ......',
    ],
    theoDeNghi: 'cơ quan chính trị',
    body: [
      { heading: 'Điều 1.', paragraphs: [`${DOTS}`] },
      { heading: 'Điều 2.', paragraphs: [`${DOTS}`] },
      {
        heading: 'Điều 3.',
        paragraphs: [
          'Quyết định này có hiệu lực kể từ ngày ký. Các chi bộ, đảng viên liên quan chịu trách nhiệm thi hành Quyết định này./.',
        ],
      },
    ],
    chuKyChucVu: ['T/M ĐẢNG ỦY', 'BÍ THƯ'],
    noiNhan: ['- Như Điều 3;'],
    luuBoPhan: 'VPĐU',
    placeholders: PARTY_PH,
  },
  {
    code: 'TPL_M03_TB_SINHHOAT',
    name: 'Thông báo lịch sinh hoạt chi bộ',
    description: 'Mẫu thông báo lịch sinh hoạt định kỳ của chi bộ.',
    docType: 'TB',
    category: 'DANG_VIEN',
    module: 'M03',
    moduleSource: ['M03'],
    entity: null,
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    ...CB_HEADER,
    kyHieu: 'TB-CB',
    trichYeu: 'Lịch sinh hoạt chi bộ ......',
    body: [
      {
        paragraphs: [
          'Thực hiện chế độ sinh hoạt Đảng định kỳ, Chi bộ thông báo lịch sinh hoạt như sau:',
          '1. Thời gian: ......',
          '2. Địa điểm: ......',
          `3. Nội dung: ${DOTS}`,
          '4. Thành phần: Toàn thể đảng viên trong chi bộ.',
          'Chi bộ thông báo để các đồng chí đảng viên biết, thực hiện./.',
        ],
      },
    ],
    chuKyChucVu: ['T/M CHI BỘ', 'BÍ THƯ'],
    noiNhan: ['- Các đảng viên (để t/h);'],
    luuBoPhan: 'CB',
    placeholders: PARTY_PH,
  },
  {
    code: 'TPL_M03_BC_TRICHNGANG',
    name: 'Trích ngang lý lịch đảng viên',
    description: 'Mẫu trích ngang đảng viên (gắn dữ liệu đảng viên M03).',
    docType: 'BC',
    category: 'DANG_VIEN',
    module: 'M03',
    moduleSource: ['M03'],
    entity: 'party_member',
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    ...CB_HEADER,
    kyHieu: 'BC-CB',
    trichYeu: 'Trích ngang lý lịch đảng viên',
    body: [
      {
        heading: 'THÔNG TIN ĐẢNG VIÊN',
        paragraphs: [
          'Họ và tên: {hoTen}',
          'Cấp bậc: {capBac}          Chức vụ: {chucVu}',
          'Đơn vị: {donVi}',
          'Ngày vào Đảng: {ngayVaoDang}          Ngày chính thức: {ngayChinhThuc}',
          'Chi bộ hiện tại: {chiBoHienTai}',
        ],
      },
    ],
    chuKyChucVu: ['T/M CHI BỘ', 'BÍ THƯ'],
    noiNhan: ['- Lưu hồ sơ đảng viên;'],
    luuBoPhan: 'CB',
    placeholders: [
      ...PARTY_PH,
      '{hoTen}',
      '{capBac}',
      '{chucVu}',
      '{donVi}',
      '{ngayVaoDang}',
      '{ngayChinhThuc}',
      '{chiBoHienTai}',
    ],
  },
];
