/** M05 — Chính sách / BHXH / Khen thưởng (CHE_DO / BAO_HIEM / KHEN_THUONG). */

import type { TemplateSpec } from '../types';
import { DOTS, HEADER_PH, QD_CAN_CU_HVHC } from './shared';

export const M05_SPECS: TemplateSpec[] = [
  {
    code: 'TPL_M05_QD_KHENTHUONG',
    name: 'Quyết định khen thưởng',
    description: 'Mẫu quyết định khen thưởng đối với một cán bộ (gắn dữ liệu nhân sự).',
    docType: 'QD',
    category: 'KHEN_THUONG',
    module: 'M05',
    moduleSource: ['M05', 'M02'],
    entity: 'personnel',
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'QĐ-HVHC',
    trichYeu: 'Về việc khen thưởng',
    banHanhChucDanh: 'GIÁM ĐỐC HỌC VIỆN HẬU CẦN',
    canCu: ['Luật Thi đua, khen thưởng', ...QD_CAN_CU_HVHC, 'thành tích đạt được'],
    theoDeNghi: 'Hội đồng Thi đua - Khen thưởng Học viện',
    body: [
      {
        heading: 'Điều 1.',
        paragraphs: [
          'Tặng ...... cho đồng chí {hoTen}, cấp bậc {capBac}, chức vụ {chucVu}, đơn vị {donViCongTac}.',
          `Lý do khen thưởng: ${DOTS}`,
        ],
      },
      { heading: 'Điều 2.', paragraphs: [`Mức tiền thưởng kèm theo (nếu có): ${DOTS}`] },
      {
        heading: 'Điều 3.',
        paragraphs: [
          'Quyết định này có hiệu lực kể từ ngày ký. Các cơ quan liên quan và đồng chí có tên tại Điều 1 chịu trách nhiệm thi hành Quyết định này./.',
        ],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Như Điều 3;', '- Hội đồng TĐKT;'],
    placeholders: [...HEADER_PH, '{hoTen}', '{capBac}', '{chucVu}', '{donViCongTac}'],
  },
  {
    code: 'TPL_M05_QD_CHEDO',
    name: 'Quyết định giải quyết chế độ chính sách',
    description: 'Mẫu quyết định giải quyết chế độ, chính sách đối với một cán bộ.',
    docType: 'QD',
    category: 'CHE_DO',
    module: 'M05',
    moduleSource: ['M05', 'M02'],
    entity: 'personnel',
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'QĐ-HVHC',
    trichYeu: 'Về việc giải quyết chế độ, chính sách',
    banHanhChucDanh: 'GIÁM ĐỐC HỌC VIỆN HẬU CẦN',
    canCu: ['các quy định hiện hành về chế độ, chính sách đối với quân nhân', ...QD_CAN_CU_HVHC],
    theoDeNghi: 'Trưởng Phòng Chính sách',
    body: [
      {
        heading: 'Điều 1.',
        paragraphs: [
          'Giải quyết chế độ ...... đối với đồng chí {hoTen}, cấp bậc {capBac}, đơn vị {donViCongTac}.',
          `Nội dung, mức hưởng: ${DOTS}`,
        ],
      },
      { heading: 'Điều 2.', paragraphs: [`Nguồn kinh phí và thời gian thực hiện: ${DOTS}`] },
      {
        heading: 'Điều 3.',
        paragraphs: [
          'Quyết định này có hiệu lực kể từ ngày ký. Các cơ quan liên quan và đồng chí có tên tại Điều 1 chịu trách nhiệm thi hành Quyết định này./.',
        ],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Như Điều 3;', '- Phòng Tài chính;'],
    placeholders: [...HEADER_PH, '{hoTen}', '{capBac}', '{donViCongTac}'],
  },
  {
    code: 'TPL_M05_TTr_KHENTHUONG',
    name: 'Tờ trình đề nghị khen thưởng',
    description: 'Mẫu tờ trình đề nghị cấp trên xét khen thưởng tập thể, cá nhân.',
    docType: 'TTr',
    category: 'KHEN_THUONG',
    module: 'M05',
    moduleSource: ['M05'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TTr-HVHC',
    trichYeu: 'Đề nghị khen thưởng',
    kinhGui: 'Thủ trưởng Học viện Hậu cần',
    body: [
      { heading: 'I. SỰ CẦN THIẾT', paragraphs: [`Căn cứ kết quả thực hiện nhiệm vụ ${DOTS}`] },
      {
        heading: 'II. NỘI DUNG ĐỀ NGHỊ',
        paragraphs: [`1. Đối tượng đề nghị khen thưởng: ${DOTS}`, `2. Hình thức khen thưởng: ${DOTS}`, `3. Thành tích tiêu biểu: ${DOTS}`],
      },
      { heading: 'III. KIẾN NGHỊ', paragraphs: ['Kính đề nghị Thủ trưởng Học viện xem xét, quyết định khen thưởng./.'] },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như kính gửi;', '- Hội đồng TĐKT;'],
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M05_BC_THIDUA',
    name: 'Báo cáo tổng kết thi đua, khen thưởng',
    description: 'Mẫu báo cáo tổng kết công tác thi đua, khen thưởng theo năm.',
    docType: 'BC',
    category: 'KHEN_THUONG',
    module: 'M05',
    moduleSource: ['M05'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC',
    trichYeu: 'Tổng kết công tác thi đua, khen thưởng năm ......',
    body: [
      {
        heading: 'Phần I. KẾT QUẢ THỰC HIỆN',
        paragraphs: [`1. Phong trào thi đua: ${DOTS}`, `2. Kết quả khen thưởng: ${DOTS}`, `3. Công tác kỷ luật: ${DOTS}`],
      },
      {
        heading: 'Phần II. ĐÁNH GIÁ, NHẬN XÉT',
        paragraphs: [`1. Ưu điểm: ${DOTS}`, `2. Hạn chế: ${DOTS}`, `3. Nguyên nhân: ${DOTS}`],
      },
      { heading: 'Phần III. PHƯƠNG HƯỚNG, NHIỆM VỤ', paragraphs: [DOTS] },
      { heading: 'Phần IV. KIẾN NGHỊ, ĐỀ XUẤT', paragraphs: [DOTS] },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Cấp trên (để b/c);', '- Các cơ quan, đơn vị (để t/h);'],
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M05_CV_BHXH',
    name: 'Công văn về bảo hiểm xã hội',
    description: 'Mẫu công văn trao đổi, đề nghị về bảo hiểm xã hội của cán bộ.',
    docType: 'CV',
    category: 'BAO_HIEM',
    module: 'M05',
    moduleSource: ['M05'],
    entity: null,
    classification: 'CONFIDENTIAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'HVHC-PCS',
    trichYeu: 'giải quyết chế độ bảo hiểm xã hội',
    kinhGui: DOTS,
    body: [{ paragraphs: [`Thực hiện quy định về bảo hiểm xã hội ${DOTS}`, `${DOTS}`, `Học viện Hậu cần đề nghị ${DOTS}`] }],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như trên;'],
    luuBoPhan: 'PCS',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M05_TB_CHEDO',
    name: 'Thông báo về chế độ, chính sách',
    description: 'Mẫu thông báo nội dung chế độ, chính sách tới các đơn vị.',
    docType: 'TB',
    category: 'CHE_DO',
    module: 'M05',
    moduleSource: ['M05'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TB-HVHC-PCS',
    trichYeu: 'Chế độ, chính sách ......',
    body: [
      {
        paragraphs: [
          `Căn cứ ${DOTS}`,
          'Phòng Chính sách thông báo nội dung như sau:',
          `1. ${DOTS}`,
          `2. ${DOTS}`,
          'Phòng Chính sách thông báo để các cơ quan, đơn vị biết, thực hiện./.',
        ],
      },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Các cơ quan, đơn vị (để t/h);'],
    luuBoPhan: 'PCS',
    placeholders: HEADER_PH,
  },
];
