/** M09 — Nghiên cứu khoa học (legacy, NCKH). Toàn bộ skeleton. */

import type { TemplateSpec } from '../types';
import { DOTS, HEADER_PH, QD_CAN_CU_HVHC } from './shared';

export const M09_SPECS: TemplateSpec[] = [
  {
    code: 'TPL_M09_BC_TONGKET',
    name: 'Báo cáo tổng kết hoạt động khoa học',
    description: 'Mẫu báo cáo tổng kết hoạt động nghiên cứu khoa học theo năm.',
    docType: 'BC',
    category: 'NCKH',
    module: 'M09',
    moduleSource: ['M09'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC-PKHQS',
    trichYeu: 'Tổng kết hoạt động khoa học năm ......',
    body: [
      {
        heading: 'Phần I. KẾT QUẢ THỰC HIỆN',
        paragraphs: [
          `1. Đề tài, nhiệm vụ khoa học: ${DOTS}`,
          `2. Công trình, bài báo công bố: ${DOTS}`,
          `3. Hội thảo, hội nghị khoa học: ${DOTS}`,
          `4. Kinh phí nghiên cứu: ${DOTS}`,
        ],
      },
      {
        heading: 'Phần II. ĐÁNH GIÁ, NHẬN XÉT',
        paragraphs: [`1. Ưu điểm: ${DOTS}`, `2. Hạn chế: ${DOTS}`, `3. Nguyên nhân: ${DOTS}`],
      },
      { heading: 'Phần III. PHƯƠNG HƯỚNG, NHIỆM VỤ', paragraphs: [DOTS] },
      { heading: 'Phần IV. KIẾN NGHỊ, ĐỀ XUẤT', paragraphs: [DOTS] },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Cấp trên (để b/c);', '- Các đơn vị (để t/h);'],
    luuBoPhan: 'PKHQS',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M09_KH_NCKH',
    name: 'Kế hoạch nghiên cứu khoa học',
    description: 'Mẫu kế hoạch hoạt động nghiên cứu khoa học năm.',
    docType: 'KH',
    category: 'NCKH',
    module: 'M09',
    moduleSource: ['M09'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'KH-HVHC',
    trichYeu: 'Hoạt động khoa học năm ......',
    body: [
      { heading: 'I. MỤC ĐÍCH, YÊU CẦU', paragraphs: [`1. Mục đích: ${DOTS}`, `2. Yêu cầu: ${DOTS}`] },
      { heading: 'II. NỘI DUNG KẾ HOẠCH', paragraphs: [`1. Đề tài, nhiệm vụ: ${DOTS}`, `2. Công bố, hội thảo: ${DOTS}`] },
      {
        heading: 'III. TỔ CHỨC THỰC HIỆN',
        paragraphs: [`1. Trách nhiệm các đơn vị: ${DOTS}`, `2. Kinh phí, điều kiện bảo đảm: ${DOTS}`],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Các đơn vị (để t/h);'],
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M09_TTr_DETAI',
    name: 'Tờ trình đề nghị phê duyệt đề tài',
    description: 'Mẫu tờ trình đề nghị phê duyệt đề tài/nhiệm vụ khoa học.',
    docType: 'TTr',
    category: 'NCKH',
    module: 'M09',
    moduleSource: ['M09'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TTr-HVHC',
    trichYeu: 'Đề nghị phê duyệt đề tài khoa học',
    kinhGui: 'Thủ trưởng Học viện Hậu cần',
    body: [
      { heading: 'I. SỰ CẦN THIẾT', paragraphs: [DOTS] },
      {
        heading: 'II. NỘI DUNG ĐỀ NGHỊ',
        paragraphs: [`1. Tên đề tài: ${DOTS}`, `2. Chủ nhiệm, đơn vị chủ trì: ${DOTS}`, `3. Mục tiêu, sản phẩm, kinh phí: ${DOTS}`],
      },
      { heading: 'III. KIẾN NGHỊ', paragraphs: ['Kính đề nghị Thủ trưởng Học viện xem xét, phê duyệt./.'] },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như kính gửi;'],
    luuBoPhan: 'PKHQS',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M09_QD_DETAI',
    name: 'Quyết định giao/nghiệm thu đề tài',
    description: 'Mẫu quyết định giao hoặc nghiệm thu đề tài khoa học.',
    docType: 'QD',
    category: 'NCKH',
    module: 'M09',
    moduleSource: ['M09'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'QĐ-HVHC',
    trichYeu: 'Về việc giao/nghiệm thu đề tài khoa học',
    banHanhChucDanh: 'GIÁM ĐỐC HỌC VIỆN HẬU CẦN',
    canCu: ['quy chế quản lý hoạt động khoa học và công nghệ', ...QD_CAN_CU_HVHC],
    theoDeNghi: 'Trưởng Phòng Khoa học Quân sự',
    body: [
      { heading: 'Điều 1.', paragraphs: [`Giao/nghiệm thu đề tài: ${DOTS}`, `Chủ nhiệm, đơn vị chủ trì: ${DOTS}`] },
      { heading: 'Điều 2.', paragraphs: [`Kinh phí, thời gian, sản phẩm: ${DOTS}`] },
      {
        heading: 'Điều 3.',
        paragraphs: ['Quyết định này có hiệu lực kể từ ngày ký. Các cơ quan, cá nhân liên quan chịu trách nhiệm thi hành Quyết định này./.'],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Như Điều 3;'],
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M09_TB_NCKH',
    name: 'Thông báo (hoạt động khoa học)',
    description: 'Mẫu thông báo về hoạt động khoa học tới các đơn vị.',
    docType: 'TB',
    category: 'NCKH',
    module: 'M09',
    moduleSource: ['M09'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TB-HVHC-PKHQS',
    trichYeu: '......',
    body: [
      {
        paragraphs: [
          `Căn cứ ${DOTS}`,
          'Phòng Khoa học Quân sự thông báo nội dung như sau:',
          `1. ${DOTS}`,
          `2. ${DOTS}`,
          'Phòng Khoa học Quân sự thông báo để các cơ quan, đơn vị biết, thực hiện./.',
        ],
      },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Các cơ quan, đơn vị (để t/h);'],
    luuBoPhan: 'PKHQS',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M09_CV_NCKH',
    name: 'Công văn (hoạt động khoa học)',
    description: 'Mẫu công văn trao đổi, đề nghị về hoạt động khoa học.',
    docType: 'CV',
    category: 'NCKH',
    module: 'M09',
    moduleSource: ['M09'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'HVHC-PKHQS',
    trichYeu: '(trích yếu nội dung công văn)',
    kinhGui: DOTS,
    body: [{ paragraphs: [`Thực hiện ${DOTS}`, `${DOTS}`, `Học viện Hậu cần đề nghị ${DOTS}`] }],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như trên;'],
    luuBoPhan: 'PKHQS',
    placeholders: HEADER_PH,
  },
];
