/** M10 — Giáo dục đào tạo (DAO_TAO). Có 2 mẫu gắn dữ liệu học viên. */

import type { TemplateSpec } from '../types';
import { DOTS, HEADER_PH, QD_CAN_CU_HVHC } from './shared';

export const M10_SPECS: TemplateSpec[] = [
  {
    code: 'TPL_M10_BC_TONGKET',
    name: 'Báo cáo tổng kết công tác đào tạo',
    description: 'Mẫu báo cáo tổng kết công tác giáo dục đào tạo theo kỳ/năm học.',
    docType: 'BC',
    category: 'DAO_TAO',
    module: 'M10',
    moduleSource: ['M10'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC-PĐT',
    trichYeu: 'Tổng kết công tác đào tạo năm học ......',
    body: [
      {
        heading: 'Phần I. KẾT QUẢ THỰC HIỆN',
        paragraphs: [
          `1. Công tác tuyển sinh, quân số học viên: ${DOTS}`,
          `2. Chương trình, kế hoạch đào tạo: ${DOTS}`,
          `3. Kết quả học tập, rèn luyện: ${DOTS}`,
          `4. Công tác tốt nghiệp: ${DOTS}`,
        ],
      },
      {
        heading: 'Phần II. ĐÁNH GIÁ, NHẬN XÉT',
        paragraphs: [`1. Ưu điểm: ${DOTS}`, `2. Hạn chế: ${DOTS}`, `3. Nguyên nhân: ${DOTS}`],
      },
      { heading: 'Phần III. PHƯƠNG HƯỚNG, NHIỆM VỤ NĂM HỌC TỚI', paragraphs: [DOTS] },
      { heading: 'Phần IV. KIẾN NGHỊ, ĐỀ XUẤT', paragraphs: [DOTS] },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Cấp trên (để b/c);', '- Các khoa, đơn vị (để t/h);'],
    luuBoPhan: 'PĐT',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M10_KH_DAOTAO',
    name: 'Kế hoạch đào tạo',
    description: 'Mẫu kế hoạch công tác đào tạo năm học.',
    docType: 'KH',
    category: 'DAO_TAO',
    module: 'M10',
    moduleSource: ['M10'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'KH-HVHC',
    trichYeu: 'Công tác đào tạo năm học ......',
    body: [
      { heading: 'I. MỤC ĐÍCH, YÊU CẦU', paragraphs: [`1. Mục đích: ${DOTS}`, `2. Yêu cầu: ${DOTS}`] },
      { heading: 'II. NỘI DUNG KẾ HOẠCH', paragraphs: [`1. Kế hoạch giảng dạy: ${DOTS}`, `2. Kiểm tra, thi, đánh giá: ${DOTS}`] },
      {
        heading: 'III. TỔ CHỨC THỰC HIỆN',
        paragraphs: [`1. Trách nhiệm các khoa, đơn vị: ${DOTS}`, `2. Điều kiện bảo đảm: ${DOTS}`],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Các khoa, đơn vị (để t/h);'],
    luuBoPhan: 'PĐT',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M10_QD_HOCVIEN',
    name: 'Quyết định (đối với học viên)',
    description: 'Mẫu quyết định cá biệt đối với một học viên (gắn dữ liệu học viên).',
    docType: 'QD',
    category: 'DAO_TAO',
    module: 'M10',
    moduleSource: ['M10'],
    entity: 'student',
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'QĐ-HVHC',
    trichYeu: 'Về việc ...... đối với học viên',
    banHanhChucDanh: 'GIÁM ĐỐC HỌC VIỆN HẬU CẦN',
    canCu: ['quy chế đào tạo hiện hành', ...QD_CAN_CU_HVHC],
    theoDeNghi: 'Trưởng Phòng Đào tạo',
    body: [
      {
        heading: 'Điều 1.',
        paragraphs: ['Đối với học viên {hoTen}, mã học viên {mssv}, lớp {lop}.', `Nội dung: ${DOTS}`],
      },
      { heading: 'Điều 2.', paragraphs: ['Quyền lợi, nghĩa vụ của học viên có tên tại Điều 1 thực hiện theo quy chế đào tạo.'] },
      {
        heading: 'Điều 3.',
        paragraphs: ['Quyết định này có hiệu lực kể từ ngày ký. Các cơ quan, đơn vị liên quan và học viên có tên tại Điều 1 chịu trách nhiệm thi hành Quyết định này./.'],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Như Điều 3;'],
    placeholders: [...HEADER_PH, '{hoTen}', '{mssv}', '{lop}'],
  },
  {
    code: 'TPL_M10_TB_HOCVIEN',
    name: 'Thông báo (học viên)',
    description: 'Mẫu thông báo tới học viên (lịch học, lịch thi, kết quả...).',
    docType: 'TB',
    category: 'DAO_TAO',
    module: 'M10',
    moduleSource: ['M10'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TB-HVHC-PĐT',
    trichYeu: '......',
    body: [
      {
        paragraphs: [
          `Căn cứ ${DOTS}`,
          'Phòng Đào tạo thông báo nội dung như sau:',
          '1. Thời gian: ......',
          '2. Địa điểm: ......',
          `3. Nội dung: ${DOTS}`,
          'Phòng Đào tạo thông báo để các khoa, đơn vị và học viên biết, thực hiện./.',
        ],
      },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Các khoa, đơn vị, học viên (để t/h);'],
    luuBoPhan: 'PĐT',
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M10_BC_KETQUA_HV',
    name: 'Báo cáo kết quả học tập học viên',
    description: 'Mẫu báo cáo/bảng kết quả học tập của một học viên (gắn dữ liệu).',
    docType: 'BC',
    category: 'DAO_TAO',
    module: 'M10',
    moduleSource: ['M10'],
    entity: 'student',
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC',
    trichYeu: 'Kết quả học tập học viên',
    body: [
      {
        heading: 'I. THÔNG TIN HỌC VIÊN',
        paragraphs: ['Họ và tên: {hoTen}', 'Mã học viên: {mssv}          Lớp: {lop}', 'Ngày sinh: {ngaySinh}          Giới tính: {gioiTinh}'],
      },
      {
        heading: 'II. KẾT QUẢ HỌC TẬP',
        loop: {
          key: 'ketQua_list',
          columns: [
            { header: 'Môn học', field: 'monHoc', weight: 4 },
            { header: 'Điểm', field: 'diem', weight: 1, align: 'center' },
            { header: 'Xếp loại', field: 'xepLoai', weight: 2, align: 'center' },
          ],
        },
      },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG ĐÀO TẠO'],
    noiNhan: ['- Lưu hồ sơ học viên;'],
    luuBoPhan: 'PĐT',
    placeholders: [...HEADER_PH, '{hoTen}', '{mssv}', '{lop}', '{ngaySinh}', '{gioiTinh}', '{#ketQua_list}'],
  },
  {
    code: 'TPL_M10_CV_DAOTAO',
    name: 'Công văn (công tác đào tạo)',
    description: 'Mẫu công văn trao đổi, đề nghị về công tác đào tạo.',
    docType: 'CV',
    category: 'DAO_TAO',
    module: 'M10',
    moduleSource: ['M10'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'HVHC-PĐT',
    trichYeu: '(trích yếu nội dung công văn)',
    kinhGui: DOTS,
    body: [{ paragraphs: [`Thực hiện ${DOTS}`, `${DOTS}`, `Học viện Hậu cần đề nghị ${DOTS}`] }],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như trên;'],
    luuBoPhan: 'PĐT',
    placeholders: HEADER_PH,
  },
];
