/** M20–M26 — Miền Khoa học. Category dùng NCKH / TONG_HOP (không tạo mới). */

import type { TemplateSpec } from '../types';
import { DOTS, HEADER_PH, QD_CAN_CU_HVHC } from './shared';

export const SCIENCE_SPECS: TemplateSpec[] = [
  // ── M20 Science Activities ──
  {
    code: 'TPL_M20_KH_HOATDONG',
    name: 'Kế hoạch hoạt động khoa học',
    description: 'Mẫu kế hoạch hoạt động khoa học (M20).',
    docType: 'KH',
    category: 'NCKH',
    module: 'M20',
    moduleSource: ['M20'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'KH-HVHC',
    trichYeu: 'Hoạt động khoa học năm ......',
    body: [
      { heading: 'I. MỤC ĐÍCH, YÊU CẦU', paragraphs: [`1. Mục đích: ${DOTS}`, `2. Yêu cầu: ${DOTS}`] },
      { heading: 'II. NỘI DUNG KẾ HOẠCH', paragraphs: [`1. Đề tài, nhiệm vụ khoa học: ${DOTS}`, `2. Hội thảo, công bố: ${DOTS}`] },
      { heading: 'III. TỔ CHỨC THỰC HIỆN', paragraphs: [`1. Phân công thực hiện: ${DOTS}`, `2. Kinh phí, điều kiện bảo đảm: ${DOTS}`] },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Các đơn vị (để t/h);'],
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M20_BC_TONGKET',
    name: 'Báo cáo tổng kết hoạt động khoa học',
    description: 'Mẫu báo cáo tổng kết hoạt động khoa học (M20).',
    docType: 'BC',
    category: 'NCKH',
    module: 'M20',
    moduleSource: ['M20'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC',
    trichYeu: 'Tổng kết hoạt động khoa học năm ......',
    body: [
      {
        heading: 'Phần I. KẾT QUẢ THỰC HIỆN',
        paragraphs: [`1. Đề tài, nhiệm vụ: ${DOTS}`, `2. Công bố, sản phẩm khoa học: ${DOTS}`, `3. Hợp tác, hội thảo: ${DOTS}`],
      },
      { heading: 'Phần II. ĐÁNH GIÁ, NHẬN XÉT', paragraphs: [`1. Ưu điểm: ${DOTS}`, `2. Hạn chế: ${DOTS}`, `3. Nguyên nhân: ${DOTS}`] },
      { heading: 'Phần III. PHƯƠNG HƯỚNG, NHIỆM VỤ', paragraphs: [DOTS] },
      { heading: 'Phần IV. KIẾN NGHỊ, ĐỀ XUẤT', paragraphs: [DOTS] },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Cấp trên (để b/c);', '- Các đơn vị (để t/h);'],
    placeholders: HEADER_PH,
  },
  // ── M23 Science Councils ──
  {
    code: 'TPL_M23_BB_HOIDONG',
    name: 'Biên bản họp Hội đồng khoa học',
    description: 'Mẫu biên bản họp hội đồng khoa học (gắn dữ liệu hội đồng M23).',
    docType: 'BC',
    titleOverride: 'BIÊN BẢN',
    category: 'TONG_HOP',
    module: 'M23',
    moduleSource: ['M23'],
    entity: 'scientific_council',
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BB-HĐKH',
    trichYeu: 'Họp Hội đồng khoa học',
    body: [
      {
        heading: 'I. THÔNG TIN CHUNG',
        paragraphs: [
          'Tên hội đồng: {tenHoiDong}',
          'Mã đề tài: {maDeTai}',
          'Tên đề tài: {tenDeTai}',
          'Thời gian họp: {ngayHop}',
          'Chủ tịch hội đồng: {chuTich}          Thư ký: {thuKy}',
        ],
      },
      {
        heading: 'II. THÀNH PHẦN HỘI ĐỒNG',
        loop: {
          key: 'thanhVien_list',
          columns: [
            { header: 'STT', field: 'stt', weight: 1, align: 'center' },
            { header: 'Họ và tên', field: 'hoTen', weight: 4 },
            { header: 'Học hàm/vị', field: 'hocHam', weight: 2 },
            { header: 'Vai trò', field: 'vaiTro', weight: 2, align: 'center' },
            { header: 'Phiếu', field: 'phieuBau', weight: 2, align: 'center' },
          ],
        },
      },
      {
        heading: 'III. KẾT QUẢ',
        paragraphs: ['Điểm trung bình: {diemTrungBinh}          Kết quả: {ketQua}', 'Kết luận của hội đồng: {ketLuan}'],
      },
    ],
    signatures: [
      { chucVu: ['THƯ KÝ'], kyGhiChu: '(Ký, ghi rõ họ tên)', hoTen: '{thuKy}' },
      { chucVu: ['CHỦ TỊCH HỘI ĐỒNG'], kyGhiChu: '(Ký, ghi rõ họ tên)', hoTen: '{chuTich}' },
    ],
    placeholders: [
      '{quocHieu}',
      '{tieuNgu}',
      '{tenCoQuanCapTren}',
      '{tenCoQuanBanHanh}',
      '{tenHoiDong}',
      '{maDeTai}',
      '{tenDeTai}',
      '{ngayHop}',
      '{chuTich}',
      '{thuKy}',
      '{diemTrungBinh}',
      '{ketQua}',
      '{ketLuan}',
      '{#thanhVien_list}',
    ],
  },
  {
    code: 'TPL_M23_QD_HOIDONG',
    name: 'Quyết định thành lập Hội đồng khoa học',
    description: 'Mẫu quyết định thành lập hội đồng khoa học (M23).',
    docType: 'QD',
    category: 'TONG_HOP',
    module: 'M23',
    moduleSource: ['M23'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'QĐ-HVHC',
    trichYeu: 'Về việc thành lập Hội đồng khoa học',
    banHanhChucDanh: 'GIÁM ĐỐC HỌC VIỆN HẬU CẦN',
    canCu: ['quy chế quản lý hoạt động khoa học và công nghệ', ...QD_CAN_CU_HVHC],
    theoDeNghi: 'Trưởng Phòng Khoa học Quân sự',
    body: [
      { heading: 'Điều 1.', paragraphs: [`Thành lập Hội đồng ...... gồm các đồng chí có tên sau: ${DOTS}`] },
      { heading: 'Điều 2.', paragraphs: [`Nhiệm vụ của Hội đồng: ${DOTS}`] },
      {
        heading: 'Điều 3.',
        paragraphs: ['Quyết định này có hiệu lực kể từ ngày ký. Các đồng chí có tên tại Điều 1 và cơ quan liên quan chịu trách nhiệm thi hành Quyết định này./.'],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Như Điều 3;'],
    placeholders: HEADER_PH,
  },
  // ── M24 Science Budgets ──
  {
    code: 'TPL_M24_TTr_KINHPHI',
    name: 'Tờ trình đề nghị kinh phí khoa học',
    description: 'Mẫu tờ trình đề nghị phê duyệt kinh phí cho nhiệm vụ khoa học (M24).',
    docType: 'TTr',
    category: 'TONG_HOP',
    module: 'M24',
    moduleSource: ['M24'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TTr-HVHC',
    trichYeu: 'Đề nghị phê duyệt kinh phí khoa học',
    kinhGui: 'Thủ trưởng Học viện Hậu cần',
    body: [
      { heading: 'I. SỰ CẦN THIẾT', paragraphs: [DOTS] },
      {
        heading: 'II. NỘI DUNG ĐỀ NGHỊ',
        paragraphs: [`1. Tên nhiệm vụ/đề tài: ${DOTS}`, `2. Tổng kinh phí đề nghị: ${DOTS}`, `3. Dự toán chi tiết: ${DOTS}`],
      },
      { heading: 'III. KIẾN NGHỊ', paragraphs: ['Kính đề nghị Thủ trưởng Học viện xem xét, phê duyệt kinh phí./.'] },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như kính gửi;', '- Phòng Tài chính;'],
    placeholders: HEADER_PH,
  },
  {
    code: 'TPL_M24_QD_GIAINGAN',
    name: 'Quyết định duyệt/giải ngân kinh phí khoa học',
    description: 'Mẫu quyết định phê duyệt/giải ngân kinh phí nhiệm vụ khoa học (M24).',
    docType: 'QD',
    category: 'TONG_HOP',
    module: 'M24',
    moduleSource: ['M24'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'QĐ-HVHC',
    trichYeu: 'Về việc duyệt/giải ngân kinh phí khoa học',
    banHanhChucDanh: 'GIÁM ĐỐC HỌC VIỆN HẬU CẦN',
    canCu: ['quy định quản lý tài chính đối với hoạt động khoa học và công nghệ', ...QD_CAN_CU_HVHC],
    theoDeNghi: 'Trưởng Phòng Tài chính',
    body: [
      { heading: 'Điều 1.', paragraphs: [`Duyệt/giải ngân kinh phí cho nhiệm vụ: ${DOTS}`, `Số tiền: ${DOTS}`] },
      { heading: 'Điều 2.', paragraphs: [`Nguồn kinh phí và thời gian thực hiện: ${DOTS}`] },
      {
        heading: 'Điều 3.',
        paragraphs: ['Quyết định này có hiệu lực kể từ ngày ký. Các cơ quan liên quan chịu trách nhiệm thi hành Quyết định này./.'],
      },
    ],
    chuKyChucVu: ['GIÁM ĐỐC'],
    noiNhan: ['- Như Điều 3;', '- Phòng Tài chính;'],
    placeholders: HEADER_PH,
  },
  // ── M25 Science Works & Library ──
  {
    code: 'TPL_M25_BC_HOSO_NHAKH',
    name: 'Hồ sơ / Báo cáo nhà khoa học',
    description: 'Mẫu hồ sơ nhà khoa học (gắn dữ liệu hồ sơ M21/M25 scientist profile).',
    docType: 'BC',
    titleOverride: 'HỒ SƠ NHÀ KHOA HỌC',
    category: 'NCKH',
    module: 'M25',
    moduleSource: ['M25', 'M21'],
    entity: 'scientist_profile',
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'BC-HVHC',
    trichYeu: '',
    body: [
      {
        heading: 'I. THÔNG TIN CHUNG',
        paragraphs: [
          'Họ và tên: {hoTen}          Quân hàm: {quanHam}',
          'Học hàm: {hocHam}          Học vị: {hocVi}',
          'Đơn vị: {donVi}',
          'Chuyên ngành chính: {chuyenNganhChinh}',
        ],
      },
      {
        heading: 'II. CHỈ SỐ KHOA HỌC',
        paragraphs: [
          'Chỉ số h-index: {hIndex}          i10-index: {i10Index}',
          'Tổng công trình: {tongCongTrinh}          Tổng trích dẫn: {tongTrichDan}',
          'Số đề án chủ nhiệm: {soDeAnChuNhiem}          Số đề án tham gia: {soDeAnThamGia}',
        ],
      },
      {
        heading: 'III. QUÁ TRÌNH ĐÀO TẠO',
        loop: {
          key: 'hocVan_list',
          columns: [
            { header: 'STT', field: 'stt', weight: 1, align: 'center' },
            { header: 'Học vị', field: 'hocVi', weight: 2 },
            { header: 'Chuyên ngành', field: 'chuyenNganh', weight: 3 },
            { header: 'Cơ sở đào tạo', field: 'coSo', weight: 3 },
            { header: 'Từ năm', field: 'tuNam', weight: 1, align: 'center' },
            { header: 'Đến năm', field: 'denNam', weight: 1, align: 'center' },
          ],
        },
      },
      {
        heading: 'IV. QUÁ TRÌNH CÔNG TÁC',
        loop: {
          key: 'congTac_list',
          columns: [
            { header: 'STT', field: 'stt', weight: 1, align: 'center' },
            { header: 'Chức vụ', field: 'chucVu', weight: 3 },
            { header: 'Đơn vị', field: 'donVi', weight: 4 },
            { header: 'Từ năm', field: 'tuNam', weight: 1, align: 'center' },
            { header: 'Đến năm', field: 'denNam', weight: 1, align: 'center' },
          ],
        },
      },
      {
        heading: 'V. KHEN THƯỞNG',
        loop: {
          key: 'khenThuong_list',
          columns: [
            { header: 'STT', field: 'stt', weight: 1, align: 'center' },
            { header: 'Tên giải/danh hiệu', field: 'tenGiai', weight: 4 },
            { header: 'Cấp', field: 'cap', weight: 2, align: 'center' },
            { header: 'Năm', field: 'nam', weight: 1, align: 'center' },
          ],
        },
      },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG KHOA HỌC QUÂN SỰ'],
    noiNhan: ['- Lưu hồ sơ khoa học;'],
    luuBoPhan: 'PKHQS',
    placeholders: [
      ...HEADER_PH,
      '{hoTen}',
      '{quanHam}',
      '{hocHam}',
      '{hocVi}',
      '{donVi}',
      '{chuyenNganhChinh}',
      '{hIndex}',
      '{tongCongTrinh}',
      '{#hocVan_list}',
      '{#congTac_list}',
      '{#khenThuong_list}',
    ],
  },
  // ── M26 Science Search, AI & Reports ──
  {
    code: 'TPL_M26_TB_KETQUA',
    name: 'Thông báo kết quả khoa học',
    description: 'Mẫu thông báo kết quả hoạt động khoa học tới các đơn vị (M26).',
    docType: 'TB',
    category: 'NCKH',
    module: 'M26',
    moduleSource: ['M26'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'TB-HVHC-PKHQS',
    trichYeu: 'Kết quả ......',
    body: [
      {
        paragraphs: [
          `Căn cứ ${DOTS}`,
          'Phòng Khoa học Quân sự thông báo kết quả như sau:',
          `1. ${DOTS}`,
          `2. ${DOTS}`,
          'Phòng Khoa học Quân sự thông báo để các cơ quan, đơn vị biết, thực hiện./.',
        ],
      },
    ],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Các cơ quan, đơn vị (để t/h);'],
    luuBoPhan: 'PKHQS',
    placeholders: HEADER_PH,
  },
  // ── M21 Science Resources ──
  {
    code: 'TPL_M21_CV_TIEMLUC',
    name: 'Công văn về tiềm lực khoa học',
    description: 'Mẫu công văn trao đổi, báo cáo về tiềm lực khoa học (M21).',
    docType: 'CV',
    category: 'NCKH',
    module: 'M21',
    moduleSource: ['M21'],
    entity: null,
    classification: 'INTERNAL',
    rbacCode: 'EXPORT_DATA',
    kyHieu: 'HVHC-PKHQS',
    trichYeu: 'tiềm lực khoa học',
    kinhGui: DOTS,
    body: [{ paragraphs: [`Thực hiện ${DOTS}`, `${DOTS}`, `Học viện Hậu cần đề nghị ${DOTS}`] }],
    chuKyChucVu: ['TRƯỞNG PHÒNG'],
    noiNhan: ['- Như trên;'],
    luuBoPhan: 'PKHQS',
    placeholders: HEADER_PH,
  },
];
