#!/bin/bash
# HVHC BigData - Critical Fixes Script
# Auto-generated by DeepAgent AI
# Date: $(date)

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== HVHC BigData - Critical Fixes ===${NC}"
echo ""

# 1. Redis Installation
echo -e "${YELLOW}[1/4] Installing Redis...${NC}"
if ! command -v redis-cli &> /dev/null; then
    sudo apt-get update -qq
    sudo apt-get install redis-server -y -qq
    echo -e "${GREEN}✓ Redis installed${NC}"
else
    echo -e "${GREEN}✓ Redis already installed${NC}"
fi

sudo systemctl start redis 2>/dev/null || true
sudo systemctl enable redis 2>/dev/null || true

if redis-cli ping &> /dev/null; then
    echo -e "${GREEN}✓ Redis is running${NC}"
else
    echo -e "${RED}✗ Redis failed to start${NC}"
    exit 1
fi
echo ""

# 2. SMTP Configuration
echo -e "${YELLOW}[2/4] Configuring SMTP...${NC}"
ENV_FILE="/home/ubuntu/hvhc_bigdata_management/nextjs_space/.env"

if grep -q "SMTP_HOST" "$ENV_FILE"; then
    echo -e "${GREEN}✓ SMTP already configured${NC}"
else
    cat >> "$ENV_FILE" << EOF

# SMTP Configuration - Added $(date)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=hvhc.bigdata@gmail.com
SMTP_PASSWORD=CHANGE_THIS_PASSWORD
SMTP_FROM=noreply@hvhc.edu.vn
SMTP_SECURE=false
EOF
    echo -e "${GREEN}✓ SMTP configured${NC}"
    echo -e "${YELLOW}⚠️  Remember to update SMTP_PASSWORD in .env${NC}"
fi
echo ""

# 3. Database Indexes
echo -e "${YELLOW}[3/4] Adding Database Indexes...${NC}"
SCHEMA_FILE="/home/ubuntu/hvhc_bigdata_management/nextjs_space/prisma/schema.prisma"

if grep -q "@@index.*maHocVien" "$SCHEMA_FILE"; then
    echo -e "${GREEN}✓ Indexes already exist${NC}"
else
    cd /home/ubuntu/hvhc_bigdata_management/nextjs_space
    
    # Backup schema
    cp "$SCHEMA_FILE" "$SCHEMA_FILE.backup.$(date +%s)"
    
    # Add indexes (need to edit schema manually or use prisma format)
    echo -e "${YELLOW}⚠️  Please add indexes manually to schema.prisma:${NC}"
    echo ""
    echo "model KetQuaHocTap {"
    echo "  // ... existing fields ..."
    echo "  @@index([maHocVien])"
    echo "  @@index([maMon])"
    echo "  @@index([namHoc, hocKy])"
    echo "  @@index([diemTongKet])"
    echo "}"
    echo ""
    echo "model FacultyProfile {"
    echo "  // ... existing fields ..."
    echo "  @@index([email])"
    echo "  @@index([departmentId])"
    echo "}"
    echo ""
    echo "model User {"
    echo "  // ... existing fields ..."
    echo "  @@index([email])"
    echo "  @@index([role])"
    echo "  @@index([lastLoginAt])"
    echo "}"
    echo ""
    echo -e "${YELLOW}After adding, run: yarn prisma migrate dev --name add_performance_indexes${NC}"
fi
echo ""

# 4. Restart Next.js
echo -e "${YELLOW}[4/4] Restarting Next.js...${NC}"
cd /home/ubuntu/hvhc_bigdata_management/nextjs_space

pkill -f "next dev" 2>/dev/null || true
sleep 2

yarn dev > /tmp/nextjs-dev.log 2>&1 &
DEV_PID=$!
echo -e "${GREEN}✓ Next.js started (PID: $DEV_PID)${NC}"
echo ""

# Wait for server to start
echo -e "${YELLOW}Waiting for server to start...${NC}"
sleep 8

if curl -s http://localhost:3000 > /dev/null; then
    echo -e "${GREEN}✓ Server is responding${NC}"
else
    echo -e "${RED}✗ Server not responding${NC}"
    echo "Check logs: tail -f /tmp/nextjs-dev.log"
fi
echo ""

echo -e "${GREEN}=== All critical fixes completed ===${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Update SMTP_PASSWORD in .env"
echo "  2. Add database indexes to schema.prisma"
echo "  3. Run: yarn prisma migrate dev --name add_performance_indexes"
echo "  4. Test performance at localhost:3000"
echo "  5. Monitor Redis: redis-cli monitor"
echo ""
echo "View logs: tail -f /tmp/nextjs-dev.log"
